### ISSUE TITLE
Vyjádření k provozní závadě - nová záložka

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#1]
Dodělat další záložku s popisem od Jirky Horkého. Předpokládám že to bude extra tabulka z důvodu vyhledávání.

U provozní dispečerů a analýzy pak doplníme nahoře do menu další odkaz s názvem "Vyjádření k provozní závadě". Je to v podstatě formulář stejný jako DP, ale je upravený pro dispečerské sály tady v Praze. Číslování je obdobné jako u PD s tím, že to platí pro ten daný sál tzn. PD1 =  DS4A, PD2 =  DS3D, PD3 = DS4B, PD5 = DS3C s tím, že čísla jsou řady dle čísla provozního dispečera. Odkaz na testovací stránku už jsem psal do toho původního povídání na google, kde jsem sepisovali podrobnosti, ale jinak je to zde:   http://www.oorp.szdc.cz/web/pz/pzavada.php?oblast=2&typ=0&prijemce=0

**Comment by Sundin18** [comment]
Jestli to dobře chápu, tak by se udělala stejná stránka jako jsou dispečerské příkazy, jen by nebyli předvyplnění příjemci ve formuláři?

**Comment by Sentinel65** [comment]
Ne, musí se udělat "nová" stránka s formulářovými prvky [podle tohoto odkazu]http://www.oorp.szdc.cz/web/pz/pzavada.php?oblast=2&typ=0&prijemce=0(url). A předvyplní se příjemci tak, jak jsou v tom testu tzn. DS3A, DS3C, DS3D atd. Podle těch příjemců, stejně jako to je v těch Dispečerských příkazech, se musí v DB pak nastavit mailová adresa, kam se automaticky zašle výstup z toho formuláře.

**Comment by Sentinel65** [comment]
Ještě doplním, až toto bude hotové, tak je třeba pro **Dispečerské příkazy** a **Vyjádření k provozní závadě** "zprovoznit" odesílání těchto dat přes poštovní službu webu na definované adresy. To budeme muset taky pořádně otestovat.

**Comment by Sundin18** [comment]
Jirko @Sentinel65 to vyjádření k provozní závadě vydává kdo? Provozní dispečer? A komu? Podle výpisu příjemců také i provoznímu dispečerovi?

**Comment by Sentinel65** [comment]
Vyjádření k provozní závadě vydává jednak provozní dispečer - traťovému dispeřerovi, nebo to může být také analyzátor, který může dát toto vyjádření jak traťovému dispečerovi, tak i provoznímu dispečerovi.  PD toto vydává traťovému dispečerovi v rámci svého dispečerského sálu. Analyzátor to může dát komukoli.

**Comment by Sundin18** [comment]
A s číslováním je to tedy jak přesně? Provozní dispečer (např. PD1) může poslat DP nějakému výpravčímu do stanice. To bude číslo 1001, pak pošle provozní závadu na svůj dispečerský sál DS4A a ta bude mít taky číslo 1001?

**Comment by Sentinel65** [comment]
Číslování je stejné jako u PD. Každému provoznímu přísluší konkrétní sál:

PD1 = DS4A             = 1000
PD2 = DS3A, DS3D  = 2000
PD3 = DS4B             = 3000
PD4 =                       = 4000
PD5 = DS3C             = 5000
PD6 =                       = 6000
PD7 =                       = 7000
Analýza                     = 9000

**Comment by Sundin18** [comment]
Tak ono je to i teď mezi DP a stanoviskem k narušení GVD. Jen tedy pořád si nejsem jist tím číslováním. Takže PD1 může vydat v jednom měsíci s číslem 1001 jak dispečerský příkaz, tak i vyjádření k provozní závadě.

**Comment by Sentinel65** [comment]
Ano je to nezávisle na sobě.

**Comment by Sentinel65** [comment]
Stanovisko k narušení to jsou ty 9999 jde pouze k analyzátorovi a ten z toho pak vytváří dokument, který přeposílá dopravcům.

**Comment by Sentinel65** [comment]
Petře, tady dávám na ukázku výstup z té provozní závady tak, jak je teď po vyplnění formuláře zaslána poštou adresátovi.

![VKPZ](https://user-images.githubusercontent.com/54531291/64322368-bba0e680-cfc2-11e9-82cd-b994b70c368a.png)

**Comment by Sundin18** [comment]
Ju, díky. Dnes bych to měl dodělat a vystavit k testování.

**Comment by Sundin18** [comment]
Tak hotovo. Nechal jsem to pod odkazem dispečerské příkazy. Nejprve je nutno vybrat, zda formulář chcete vyplnit jako dispečerský příkaz, stanovisko k narušení GVD, nebo vyjádření k provozní závadě (má pouze oblast Praha). Pak už je vše stejné jako dosud. Verze 19.09.9

**Comment by Sentinel65** [comment]
Tak první poznatky Petře:

1) můžeš to nechat takto dohromady, ale ...
2) je naprosto nutné, aby pro provozního a analýzu z těch uložených záznamů bylo hned zřejmé, co je DP a co PZ, zvláště pokud to může mít stejná pořadová čísla
3) takže navrhuji udělat samostatnou tabulku pro ty PZ 
4) stanovisko k narušení GVD jsi mohl nechat, jak bylo předtím jen jako checkbox s tím, že se předvyplní číslo DP na 9999, to bych vrátil zpět (stanovisko je součástí DP)
5) takže by byly jen 2 volby Dispečerský příkaz (včetně stanoviska) a Vyjádření k provozní závadě
6) volba Vyjádření k provozní závadě by měla formulář, který jsi udělal, ale také **uplně samostanou tabulku záznamů**
7) ještě k tomu formuláři Vyjádření k provozní závadě, myslel jsem, že jsi pochopil, jak tam nastavit ta komba a jejich kombinaci s předvolbou sálů (příjemce). Jde o to eliminovat možnost překlepnutí se v tom kombu. Analýza si to bude muset pohlídat, má vše. 

Takže v kombu **pracoviště** bude seznam:
PD1, PD2, PD3, PD4, PD5, PD6, PD7, analýza

V kombu **příjemce** však bude pouze to, co jsem ti už psal tzn.
PD1 bude mít pouze **DS4A** = 1000
PD2 bude mít **DS3A, DS3D** = 2000
PD3 bude mít **DS4B**            = 3000
PD4 zatím nemá sál            = 4000
PD5 bude mít **DS3C**            = 5000
PD6 zatím nemá sál            = 6000
PD7 se musíme domluvit ještě  = 7000
Analýza bude mít **DS3A, DS3C, DS3D, DS4A, DS4B, PD1, PD2, PD3, PD4, PD5, PD6, PD7** = **9000** /pozor máš tam ted nastaveno 8001/

Tak snad jsem ti ted moc nezamotal hlavu.

**Comment by Sundin18** [comment]
Jestli můžu, tak bych nechal tabulku jednu. Až bude mít nad sebou filtr, bude si moci uživatel předvolit,že chce zobrazit třeba jen DP nebo PZ. A dal bych tam navíc sloupec s označením, případně i barevně odlišil řádky.

U toho číslování takový "kacířský návrh". Co kdyby čísla všech DP, PZ by se číslovaly od 1 do ...(jako je to u MU). Číslo by se pak skládalo z toho čísla (ID) a pak kód pracoviště např. PD1 PHA. Takže by byly DP např. 1 PD2 PHA, 2 PD1 UNL, 3 PD1 PHA atd...

**Comment by Sentinel65** [comment]
Ty mi dáváš chlape ... 
Netuším, jak to máš vymyšlené ten filtr, takže se bojím, až to uděláš, že ti to shodíme ze stolu (nejen já, ale tohle budou posuzovat hlavně analýza a provozní) a budeš to muset předělávat.  Zkus to nějak popsat, klidně nakresli tabulku co já vím. Kazdopádně to musí být přehlednéa jednoduché se v tom vyznat, časem tam bude spousta záznamů.

To číslování, nejde jen o to, jak to bude prezentované v uložené tabulce, jako je to teď celkem hodně jednoduše, ale budou z toho výstupy do mailu a tam bych rád, aby z toho čísla bylo jednoznačně identifikovatelné, o co se jedná. 
Tzn. nejen pořadové číslo, ale i číselné označení měsíce, pracoviště, lokalita a o co jde, jestli PZ nebo DP. 
Zkus dát návrh smysuplného a jednoduchého označení, než začneš něco dělat, ať se to nepředělává několikrát. Tohle musíme mezi sebou nejdříve pořadně vykomunikovat.
Teď se posílá do předmětu mailu například Provozní závada číslo: PHA9003/08 - DS4A.
Jirka bude zítra v Ústí, ty máš prej taky denní, tak pokud by byla chvilka, možná by bylo lepší si na deset minut zavolat a domluvit se, než si psát romány....   :-)

**Comment by Sundin18** [comment]
Ok, zítra se domluvíme.

**Comment by Sentinel65** [comment]
Je pravda, že teď když je databáze, tak nemusíme striktně držet ty série čísel podle jednotlivých pracovišť.

ID_MM_TYP_PRAC_LOC_ADRESS
1_09_DP_PD1_PHA_DS4A

Je to sice krkolomné a dlouhé, ale obsahuje vše. Třeba něco navrhne Jirka..

**Comment by Sentinel65** [comment]
Bavili jsme se s Přemkem a v tom formátu čísla DP /PZ/ by nemuselo být číslo měsíce, takže formát by byl:

ID_TYP_PRAC_LOC_ADRESAT

Číslování by se **resetovalo 1. dnem nového roku**. Jinak by to šlo za sebou jako u čísel jednacích. Ještě je to třeba probrat v pondělí s vedoucím analýzy.

**Comment by Sundin18** [comment]
Aj, tak to je pro mě horší varianta než co je doteď :-/.

**Comment by Sentinel65** [comment]
Proč? Však sloupec s číslem tam již je (pokud chápu, tak to teď není ID záznamu), tak ho podle datumu jen vynuluješ.

**Comment by Sundin18** [comment]
Akorát tedy to číslo bude přiděleno až při ukládání do DB, nebude předepsané v tom formuláři. Aby nemohlo dojít, když by byly rozepsány ve stejnou chvíli dva dispečeráky, že dostanou stejné číslo.

**Comment by Sentinel65** [comment]
Tak určitě, nevím jak jinak to ošetřit. Provozní to číslo nepotřebuje ve chvíli, když to píše a po uložení to bude mít v databázi a do výstupu zaslaném v mailu se to natáhne z databáze.

**Comment by Sundin18** [comment]
Tak hotovo, číslování jsem zatím ponechal. (Verze 19.09.10). Jinak jsem musel změnit DB, takže tím pádem došlo k smazání vašich účtů. Proto se prosím znovu zaregistrujte a já vám pak dám oprávnění a oblasti. Díky.

**Comment by Sentinel65** [comment]
No ta registrace spíše nefunguje. Když vyplním údaje a dám Registrovat, tak to nic neudělá, žádná hláška, jestli to porovnává jméno (email) registrace. Když zadám mail a heslo pro přihlášení, tak tám sice vidím své jméné, ale píše, že nemám oprávnění.

**Comment by Sundin18** [comment]
Však to je správně, administrátor ti pak přidělí oblast a funkci. Teď jsem ti to vše nastavil. Prosím odhlaš se a zase přihlas a už budeš mít zase práva a oblasti jako předtím.

**Comment by Sentinel65** [comment]
K těm filtrům v DP a PZ:

1. až bude naplněna databáze uživatelů s přiřazením praviště podle IP adresy, tak pak bych byl rád kdyby ten filtr toho daného pracoviště byl automaticky nastavený (kombo "Všechny", PD1 atd.
2. input **vydal** nevyhledává to hned po zadání dvou třech písmen, ale čeká na Enter (nefunguje ani klepnutí myši mimo daný input). Chybí křížek na zrušení filtru
3. filtr **datum** neumí od - do, udělej to prosím tě stejně jako u Závady a mimořádnosti
4. filtr **číslo** navrhuji zrušit ty šipky nahoru, dolu (těžko budeme klikat šipkou po jedné do tisíců, pokud už tam něco mám napsat, je to rychlejší), opět je třeba dolnit křížek pro zrušení filtru
5. v DP i PZ ještě není úplně kompletována vazba (přednastavené volby) pracoviště - příjemce, to jak jsme  se domlouvali, že ti dodají VO
6.  ve výpisu **Vyjádření k provozní závadě** ve sloupci **Typ** je obráceně ta zkratka ZP, správně **PZ**
7. ve formuláři **Vyjádření k provozní závadě** pracoviště Analýza PHA u příjemce chybí všichni příjemci, jak jsem je vypisoval tzn. **DS3A, DS3C, DS3D, DS4A, DS4B, PD1, PD2, PD3, PD4, PD5, PD6, PD7** tam to oprav prosím tě

Více asi až se zase naplní databáze ...

**Comment by Sundin18** [comment]
Hotovo, verze 19.09.11

**Comment by Sentinel65** [comment]
U PZ v tom pravém filtru (kombu) by měla analýza vidět vše, nevidí nic.

**Comment by Sentinel65** [comment]
Formulář - je společný pro DP i PZ a koukám, že tam je rozsah jenom aktuální měsíc.
Může se stát, že DP či PZ bude uživatel zadávat po půlnoci  z posledního dne měsíce na první den následujicího měsíce, v tuhle chvíli tam nemá jak zadat předchozí den.
Příklad dne 1.9.  v 00:20 se dostane k informaci, že byl narušen GVD tam a tam u vlaku toho a toho v čase 23:45 dne 31.8. , ale formulář mu neumožnuje v tuto chvíli zadat den předchozího měsíce.

**Comment by Sentinel65** [comment]
Formulář **Vyjádření k provozní závadě** - pokud tam je  **jeden jediný příjemce** nešlo by, aby byl **automaticky označen** ?

**Comment by Sundin18** [comment]
Teď nevím, co myslíš tím, že v kombu vidí jen, co vytvoří? Myslíš kombo nad tabulkou dispečeráků?
To pořádové číslo, smažu, to jsem měl pro svoji potřebu a pak to zapomněl vymazat. Ten input vyhledává pouze příjmení toho, kdo napsal DP.
Datum u události kdy nastala mohu zvolit do minulosti jakýkoliv, jen ne do budoucnosti. Tzn., že nemohu napsat DP na zítřek.
Ju, to by snad šlo, když je jen jeden příjemce.

**Comment by Sentinel65** [comment]
Ano to kombo vpravo nad tabulkou DP a PZ, implicitně tam je "Všichni"
Pokud to vyhledává **jen příjmení**, je třeba to napsat jako Tool tip.
Do budoucnosti datum v tom kalendáři není třeba, ale do minulosti ano ...
Fajn

**Comment by Sundin18** [comment]
Přihlášil jsem se jako Analýza Praha a v tom kombu "všichni" mám pak vypsaná další pracoviště.
Tooltip dopíšu.

**Comment by Sentinel65** [comment]
V om kombu je to v pořádku, já jsem měl na mysli, to že analýza měla vidět všechny záznamy všech a ty to tam máš tak, že každý vidí jen to, co vytvořil a pod filtrem Všechny je pak vidět vše, Tak už to nech to je OK

**Comment by Sentinel65** [comment]
> To pořádové číslo, smažu, to jsem měl pro svoji potřebu a pak to zapomněl vymazat.

To klidně vymaž, ale jak jsem psal u Závady a mimořádné události, bylo by dobré, aby tam někde bylo vidět také ID záznamu DB, pokud by bylo třeba něco dohledávat, je to nejprůkaznější údaj, jak to najít přímo (ne hledat podle čísla DP /PZ/, datuku, jména apod.)

**Comment by Sundin18** [comment]
Ok, proto jsem si i říkal,že číslo DP,PZ by bylo id číslo. Proto ta změna číslování.

**Comment by Sentinel65** [comment]
jj ale to uvidíme jak se k tomu ještě vyjádří analýza, atím nemám odezvu

**Comment by zachyunl** [comment]
Číslování nechte zatím tak jak je uděláno. Chci to pustit pražské analýze k testům, je to tak s Přemkem Plachým domluveno. Počkáme co ještě Petr udělá dneska o noční za úpravy a Sentinel65 se zítra domluví s Honzou Frajerem, s tím že mu to ukáže a pobaví se hlavně o tom číslování, případně nějakých jiných nápadech.

**Comment by zachyunl** [comment]
Příkazy a závady - filtrovat dle datumu má anglické menu 
![image](https://user-images.githubusercontent.com/47257941/64526587-0349aa00-d304-11e9-896e-3cddfcb17d46.png)

**Comment by Sundin18** [comment]
Opraveno, doplněno (verze 19.09.12)

**Comment by Sentinel65** [comment]
Petře, stejný typ kalendáře tzn. aktuální a minulý měsíc je třeba upravit i ve formulářích DP a PZ.
Upraveno je to jenom ve filtrování nad tabulkou.

**Comment by Sundin18** [comment]
Ve formuláři je kalendář pro výběr určitého data a času pro uložení. Nad tabulkou je jen pro výběr pro vyhledávání.

**Comment by Sentinel65** [comment]
Jasně to chápu, ale jak jsem psal ...

> Formulář - je společný pro DP i PZ a koukám, že tam je rozsah jenom aktuální měsíc.
Může se stát, že DP či PZ bude uživatel zadávat po půlnoci z posledního dne měsíce na první den následujicího měsíce, v tuhle chvíli tam nemá jak zadat předchozí den.
Příklad dne 1.9. v 00:20 se dostane k informaci, že byl narušen GVD tam a tam u vlaku toho a toho v čase 23:45 dne 31.8. , ale formulář mu neumožnuje v tuto chvíli zadat den předchozího měsíce.

Proto je třeba upravit ten kalendář nejen ve vyhledávání, ale i ve formuláři.

**Comment by Sundin18** [comment]
Pod tím titulkem toho kalendáře je napsaný měsíc a vedle toho měsíce nalevo i napravo jsou šipky, kterými se pohybuju po měsících dopředu a dozadu. Případně lze kliknout i na ten měsíc a vyskočí tabulka s měsíci, takže lze i přímo vybrat měsíc. Takže šipkou si zobrazím např. srpen 2019 a můžu zadat čas z minulého měsíce než píšu zápis.

**Comment by Sentinel65** [comment]
To zobrazení u menšího displeje je špatné.

**Comment by Sundin18** [comment]
Pak je tedy potřeba scrollovat stránkou trochu dolů, aby se kalendář zobrazil dolů od formulářového pole.

**Comment by Sentinel65** [comment]
jj jak říkám na velkém monitoru to problém nebude

**Comment by Sundin18** [comment]
pro ty radio buttony udělám více místa nebo je dám doleva, to je v poho.

**Comment by Sentinel65** [comment]
spíše je zarovnej vlevo

**Comment by Sundin18** [comment]
tak jsou vlevo a formulářové pole s datumem jsem posunul trochu výše, takže by se měl teď zobrazovat automaticky dolů pod.

**Comment by zachyunl** [comment]
Petře https://github.com/Sundin18/backend/issues/1#issuecomment-529443467, nešlo by udělat filtrování dle datumů u DP stejně jako u mimořádností? Teď tam máme pouze tento měsíc a minulý měsíc. Přijde mi to z pohledu uživatele zbytečně nekomfortní, protože jim budeme cpát v každé záložce jinou možnost filtrů. Co když si bude chtít vedení filtrovat DP po týdnu, nebo to budou využívat i na konference.

**Comment by Sundin18** [comment]
Ok, dám tam stejný tlačítka

**Comment by Sentinel65** [comment]
Takže teď jsem domluvil s Honzou Frajerem z AJŘ PHA a Radkem Bejšákem jako vrcholovou analýzou a návrh na číslování DP a PZ je takový, že by se to číslovalo od začátku kalendářního roku od čísla 1 až do konce kalendářního roku vše tak, jak se to bude zapisovat do DB napříč OJ CDP PHA (UNL) a PRE, nedělal by se rozdíl mezi DP a PZ. Prostě by to šlo jedno za druhým. Stejně jako jsou čísla jednací. Počínajem prvním dnem nového roku by se číslování vynulovalo a jelo by se na novo.
V tom případě by ve formuláři DP a PZ bylo pole s Číslem zašedlé a disabled a objevilo by se tam jen ve chvíli, kdyby se prováděla  oprava.  

Jak jsme se domluvili s Petrem číslo by bylo přiděleno až při ukládání do DB.
> Akorát tedy to číslo bude přiděleno až při ukládání do DB, nebude předepsané v tom formuláři. Aby nemohlo dojít, když by byly rozepsány ve stejnou chvíli dva dispečeráky, že dostanou stejné číslo.

Návrh formátu čísla pro prezentaci ven (výstupní formát emailu) je následujicí:

ID_TYP_PRAC_LOC_ADRESAT
1_PZ_PD1_PHA_DS4A
2_DP_PD1_UNL_PO Most
3_DP_PD3_PRE_OŘ Olomouc
4_PZ_PD3_PHA_DS3C
5_DP_PD1_PRE_PO Brno
atd.

Případně, pokud by se k tomu ještě vyjadřoval Přerov a vedení se tam může doplnit měsíc (rok), to už asi nebude takový problém.

Petře, vidíš teď nyní v tomto pro tebe nějaký problém ?

**Comment by Sundin18** [comment]
Asi bych vynechal jméno příjemce v čísle DP, protože příjemců může být víc než jeden a pak by to bylo velice dlouhé.
Pak mi pořád uniká smysl toho číslování,  proč musí být  každý rok od 1 a  pak budeme zobrazovat dvě čísla ( id a cislo). Ale to jen na okraj ;-)

**Comment by Sentinel65** [comment]
ID je číslo záznamu v DB, které vůbec nekoresponduje s pořadovým číslem. Samozřejmě prioritní je prezentace pořadového čísla. To ID číslo jsem nemyslel nikam posílat, jen ho zobrazit jako  #NUM pro účely ryhlého dohledání v DB, kdyby bylo potřeba, tak jak to je v Závadách a mimořádnostech.

Takhle vypadá aktuálně výpis DP posílaný mailem. V předmětu by nově bylo už jen to číslo bez jakéhokoli textu (protože složené číslo by samo osobě už by v sobě mělo vše), takže až tak dlouhé by to myslím nebylo. Teď jsem se schválně ptal na analýze a Honza mi sám potvrdil, že případů, kdy je třeba případně DP poslat současně na vícero OJ je během roku v řádu jednotek (myšleno nepřekročilo ani číslo 5) !

![DP_PZ](https://user-images.githubusercontent.com/54531291/64605068-9f86b600-d3c3-11e9-8114-abebeb67e0da.png)

K těm adresátům ve formuláři DP se Honza vyjádřil, že by je neškatulkoval podle pracoviště, ale nechal je všechny jako výběr pro všechna pracoviště stejná. Tady bych to teda rozdělil aspoň podle lokalit (PHA, UNL a PRE), protože to kombo se seznamem by bylo jinak poměrně dlouhé.

**Comment by Sundin18** [comment]
Tak ono ID mám taky nastavené, že je to v podstatě pořadové číslo. Zkrátka tam nevidím výhodu toho čísla oproti ID číslu. A i je s ním méně "práce" při ukládání a získávání z DB. Ale už toho nechám ;-)

**Comment by Sundin18** [comment]
Hotovo (Verze 19.09.13)

**Comment by Sentinel65** [comment]
Uf uf ... není to dobře ...
Začíná toho být hodně, budeme muset ty úpravy /opravy/ dělat po částech:

**Vyjádření k provozní závadě**:

> Takže v kombu **pracoviště** bude seznam:
PD1, PD2, PD3, PD4, PD5, PD6, PD7, analýza

V kombu **příjemce** však bude pouze to, co jsem ti už psal tzn.
PD1 bude mít pouze DS4A
PD2 bude mít DS3A, DS3D
PD3 bude mít DS4B
PD4 zatím nemá sál
PD5 bude mít DS3C
PD6 zatím nemá sál
PD7 se musíme domluvit ještě
Analýza bude mít DS3A, DS3C, DS3D, DS4A, DS4B, PD1, PD2, PD3, PD4, PD5, PD6, PD7

**Comment by Sundin18** [comment]
Takže v provozních závadách bude výběr příjemců závislý na výběru pracoviště. V dispečerácích nikoliv, tam jen na oblasti (Praha, Ústí, Přerov)

**Comment by Sentinel65** [comment]
**Dispečerské příkazy**  (platí tedy POUZE pro DP)

**Lokalita PHA**:

**Pracoviště**: PD1, PD2, PD3, PD4, PD5, PD6, PD7, Analýza PHA 
**Příjemce**:  viz obrázek

![PHA_DP_adresat](https://user-images.githubusercontent.com/54531291/64606663-08bbf880-d3c7-11e9-8ab4-36951e6985d3.png)

**Lokalita UNL**:

**Pracoviště**: PD1, PD2, PD3, Analýza PHA
**Příjemce**: viz obrázek

![UNL_DP_adresat](https://user-images.githubusercontent.com/54531291/64606651-02c61780-d3c7-11e9-94d6-66cf6d174abd.png)

**Lokalita PRE**:

**Pracoviště**: PD1, PD2, PD3, PD4, PD5, PD6, Analýza PRE
**Příjemce**: viz obrázek

![PRE_DP_adresat](https://user-images.githubusercontent.com/54531291/64606632-f346ce80-d3c6-11e9-9141-9300f9e30e4b.png)

**Comment by Sentinel65** [comment]
**Stanovisko k narušení GVD**  

**Lokalita PHA**:

Pracoviště: PD1, PD2, PD3, PD4, PD5, PD6, PD7, Analýza PHA
Příjemce:   Analýza PHA

**Lokalita UNL**:

Pracoviště: PD1, PD2, PD3, Analýza PHA
Příjemce:   Analýza PHA

**Lokalita PRE**:

Pracoviště: PD1, PD2, PD3, PD4, PD5, PD6, Analýza PRE
Příjemce:   Analýza PRE

**Comment by Sentinel65** [comment]
Ještě jsem si všiml u těch Dispečerských příkazů, jak jsou ty obrázky s příjemci. Tak tam u všech lokalit vynech a nepiš do příjemců **Ostatní příjemci**.
To je označení příjemce v ostrých DP, který de facto překlápí ten dispečerský příkaz do stanoviska k narušení GVD, které chodí rovnou a pouze na analýzu.

**Comment by Sentinel65** [comment]
**Dispečerské příkazy**

**Lokalita PRE**
Ještě doplnit příjemce: 
CDP Přerov OŘ
CDP Přerov DŘ
TUDC

**Lokalita UNL**
Ještě doplnit příjemce: 
PO Plzen (nebyl v seznamu, co jsem ti poslal)

**Lokalita PHA**
Ještě doplnit příjemce:
PO Plzen

Ze seznamu příjemce smazat (ty dispečerské sály jsou jen u provozní závady):
DS3A
DS3C
DS3D
DS4A
DS4B
PD1 PHA
PD2 PHA

**Comment by Sundin18** [comment]
Tak snad hotovo (Verze 19.09.15). Už jen chybí to automatický předvyplnění příjemce, když je pouze jeden, ale to k testování nevadí a časem to dodělám.

**Comment by Sentinel65** [comment]
Tak ještě malinké drobnosti

**Lokalita PHA**

DP+ST+PZ

V položce Pracoviště dej položku Analýza PHA až na konec seznamu

**Lokalita UNL**

DP

V položce Příjemce dej PO Plzeň za PO Louny a před OŘ Ústí na Labem

**Lokalita PRE**

DP+ST

V položce Pracoviště dej položku Analýza PRE až na konec seznamu

**Comment by Sundin18** [comment]
Tak snad už doplněno a opraveno.

**Comment by Sentinel65** [comment]
Ted už to vypadá OK
