### ISSUE TITLE
Závady a mimořádné události - doplnění položek

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#10]
Závady a mimořádné události: po diskusi s VD tady u nás,  sice nevím jak se na to budou tvářit v Přerově, předpokládám ale, že nebudou zásadně proti, bych doplnil do formuláře ještě jako nepovinné ty položky o zastavení provozu asi takto: "Zastavení provozu (Z)", "Pokyn vydal" (zde by bylo kombo s předvolbami PČR, HZS, Nehodová pohotovost, Nehodový dozor, Odborná správa OŘ a výpravčí), "Zastavení provozu (U)", "Pokyn vydal" (zde by bylo kombo s předvolbami PČR, HZS, Nehodová pohotovost, Nehodový dozor, Odborná správa OŘ a výpravčí), "Doba trvání ZP" (v minutách) s tím, že by byly ošetřeny stavy, aby nešlo ukončit MU bez ukončení ZP

**Comment by Sentinel65** [comment]
Jen znovu doplním úpravu pro pojmenování položek, aby to korespondovalo s formulářem: pod řadkem **Doba trvání** by byl další řádek:

**Zahájeno [ZP]:**   datum a čas, vedle pak **Pokyn vydal:** kombo s předvolbami (PČR, HZS, Nehodová pohotovost, Nehodový dozor, Odborná správa OŘ, výpravčí), hned vedle pak **Doba trvání** (v min)
Další řádek **Ukončeno [ZP]:** Zastavený provoz (červeně podbarvený s bílým textem) nebo datum a čas, vedle pak **Pokyn vydal:** kombo s předvolbami (PČR, HZS, Nehodová pohotovost, Nehodový dozor, Odborná správa OŘ, výpravčí)

Podbarvení textu "Šetření trvá" změň prosím tě na jinou, než červenou (ta bude výhradně pro ten "Zastavený provoz"), klidně na hnědou (ta by k té šedé mohla jít) a všechny tyto texty s prvním písmenem velkým ("závada trvá" = velké Z), ať je to vše stejné

**Comment by Sentinel65** [comment]
A k tomu ještě malinkatá kosmetická úprava - zarovnání textu verze v šedé liště podle obrázku, aby bylo zároveň s logem a vpravo zarovnání loginu podle tlačítko **Žádost o registraci | Odhlásit se**.

![Lista01](https://user-images.githubusercontent.com/54531291/63845326-1e263100-c98a-11e9-86b2-1c498e2c66ef.png) 
![Lista02](https://user-images.githubusercontent.com/54531291/63845338-22eae500-c98a-11e9-9be2-4030a0d978cf.png)

**Comment by zachyunl** [comment]
Teď koukám na tu lištu a musíme změnit na barvu, která odpovídá korporátu. Zrovna jsem si na toto téma nedávno dopisoval s Přemkem. 

Zde je oficiální vyjádření

_Hezký den, pane Zachaři,_

_logo pro webové stránky, vychází z konceptu webových stránek SŽDC a je nutné tento koncept
dodržet. Každá oblast činností naší organizace nese specifikum vizuálního stylu. U webových stránek
je to buď logo v základní variantě na bílém podkladě, tak jak je Homepage webu a nebo pokud je tam pruh, je tmavě modrý a logo celé oranžové._


_S přáním hezkého dne_

_Šárka Bérová_

**Comment by Sentinel65** [comment]
No teď se koukám na stránky www.szdc.cz a je otázka, co se myslí tím pruhem ! U webových stránek
je to buď **logo v základní variantě na bílém podkladě** = toto máme v souladu ! S tím pruhem to chápu tak, že nemáš logo na bílem podkladě, ale je tam široký pruh, který má být tmavě modrý a **v něm je to oranžové logo**. Dle mého tedy nic neporušujeme.

**Comment by Sundin18** [comment]
Taky si myslím, že to máme v souladu.

**Comment by zachyunl** [comment]
Nemůžu si pomoci, ale máme to blbě. Viz například KAZAS http://www.rcp.szdc.cz/aplikace/kazas/default.aspx nebo hlavní stránky www.szdc.cz. Vše je popsáno v manuálu http://intranet.szdc.cz/Sablony/Nov%C3%A9%20logo%20a%20implementace/V%C5%A1eobecn%C3%A9%20informace%20k%20nov%C3%A9mu%20logu%20a%20vizu%C3%A1ln%C3%ADmu%20stylu/Nov%C3%A1%20vizu%C3%A1ln%C3%AD%20identita%20informace%20pro%20zam%C4%9Bstnance.pdf.

Petře jaké písmo používáš? To tam je také popsáno.

**Comment by Sentinel65** [comment]
Ty seš hroznej beran Jirko :-D

Podívej se na [tento odkaz](https://www.szdc.cz/documents/50004227/50158371/SZDC_manual-vizualniho-stylu_2019_vyd1_20190628.pdf/8bce6827-6633-4b38-baee-c2405cdf4c25) a na stranu 97 a napiš mi, jakou barvu podkladu má obrázek vpravo nahoře.

**Comment by zachyunl** [comment]
Jirko pás s logem nezpochybňuju, ten máme již takto posvěcen a Petr ho kdysi kvůli tomu upravoval. Co zpochybňuju, tak ostatní sladění barev na stránce. To je téměř celé blbě.

**Comment by Sentinel65** [comment]
V tom logo manuálu je také jeden návrh stránky, kde je šedé pozadí. A to, že prezentujeme pod logem rovnou databázovou aplikaci se šedým podkladem tomu neodporuje.

**Comment by Sentinel65** [comment]
Hlavně, že v tom logo manuálu píšou, aby to bylo příjemné pro uživatele. Ptal se někdo uživatele, co to udělá s jeho zrakem, když bude v přítmí celou noc koukat na webové stránky s bílým podkladem ?

**Comment by zachyunl** [comment]
Souhlasím uzavírám diskuzi o barvách a řešme nejdříve funkčnost.

**Comment by Sundin18** [comment]
Hotovo - verze 19.08.3

**Comment by Sentinel65** [comment]
Vpravo v sekci Stav dej prosím tě tu položku Zastavený provoz hned pod tu položku Vše, beru to podle důležitosti, pak se může požadavek uzavřít.

**Comment by Sundin18** [comment]
Hotovo - verze 19.08.4

**Comment by Sentinel65** [comment]
U té změny se položky načítají, jak mají. Seznam položek v sekci **Stav** už je ok, požadavek možno uzavřít.

**Comment by Sentinel65** [comment]
To levé kombo s filtry prosím ještě doplnit takto:

"ID"
"Zahájeno"
"Ukončeno"
"Zahájeno (ZP)"
"Ukončeno (ZP)"
"Aktualizováno"

**Comment by Sundin18** [comment]
Hotovo (verze 19.09.3)

**Comment by Sundin18** [comment]
Ok, jinak to ID koresponduje s časem, kdy byl vytvořen zápis.

**Comment by Sundin18** [comment]
Hotovo, dal jsem to jako "Zapsal", je to takové ne tolik ajťácké :) (verze 19.09.5)

**Comment by Sentinel65** [comment]
Sice to není tolik ajťácké, ale lidi se budou okamžitě ptát na význam. Přejmenuj to prosím tě na "Pořadové číslo". Díky

**Comment by Sentinel65** [comment]
Opraveno, zavírám
