### ISSUE TITLE
Testovací server

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#100]
Jirko, musíme se domluvit na testování, na té 38 nemůžeme testovat normálně, protože ty Příkazy chodí ven do stanic. Takže se tam buď podhodí moje adresy všude a bude to chodit jen mně,případně i vám oběma a ta synchronizace dat by se udělala jinde.

**Comment by zachyunl** [comment]
To je otázka co je vždy potřeba testovat. Může se např. pro testy vypnout úplně Postfix a pak se nebude nic odesílat, ale zase když ho poté zapneme, tak to odejde vše dávkou. 
Petře ty máš emailové adresy v kódu, nebo to je vše narvané v databázi a ty to jenom kódem linkuješ?

**Comment by Sundin18** [comment]
Je to v DB

**Comment by zachyunl** [comment]
Předpokládám record_emails a record_email_region?

**Comment by zachyunl** [comment]
Rychlé řešení je, že vyblokuju na postfixu relay. Tzn. nebudou se odesílat žádné emaily, ale již nic takového neotestujeme. Nebo se můžou upravit zmiňované tabulky přes které jdou emaily. Ale jakmile zesynchronizuju databáze, tak se to přepíše. Časově nejnáročnější bude na to připravit aplikaci a napsat něco, že si např. v administraci budu přepínat, že emaily jdou buď přes běžné tabulky jako nyní, nebo tam bude další tabulka pouze s testovacíma emailovýma účtama, kterou si přepnu.

**Comment by Sundin18** [comment]
Tabulka record_emails a operating_districts. Já bych asi vypnul tu synchronizaci a pak zmenim v tabulkách emaily třeba. Jsi říkal,že se to synchronizuje ještě někam jinam.

**Comment by zachyunl** [comment]
Synchronizace je vypnutá od víkendu, zatím jsem jí nepouštěl. O zálohu teď Petře nejde ta mi primárně běží na 10.99.164.33, tam to běží stále, teď jsem to kontroloval. Jde o to, že když budeš hrabat do DB, nebo něco testovat, tak nebudou aktuální data. Nevím co je spíše potřeba zda emaily, nebo aktuální data.

**Comment by Sundin18** [comment]
Tak dát je tam spousta na testování. Je mi to jedno, klidně se může vypnout pošta. Jde hlavně o to, aby nechodila pošta,  když tam píšeme záznamy apod. nebo aby chodila na naše emaily třeba.

**Comment by zachyunl** [comment]
Dobře vypínám posílání emailů na 38. Raději to testněte.

**Comment by Sentinel65** [comment]
Jirko, ideální to je testovat na aktuálních datech. Lze tu synchronizaci nastavit z ostrého na tu 38, aby se ta tabulka s mailama nesynchronizovala a měli jsme na té 38 nastavené v DB naše maily na testování ?

**Comment by zachyunl** [comment]
Uvidím musím to otestovat, až bude více času. Našel jsem v parametrech toto "Replicate_Ignore_Table", takže to vypadá, že by to mělo jít.

**Comment by zachyunl** [comment]
Nastavil jsem do vyjímek na synchronizace tyto tabulky: 
Replicate_Ignore_Table | szdc.record_emails, szdc.operating_districts
Nevím co chcete zachovat a změnit za emailové adresy, tak to případně upravte a dejte vědět, ať zazálohuji upravené tabulky. Postfix mám zatím vypnutý.

**Comment by Sundin18** [comment]
Ok, já tam tedy nastavím všude email na Jirku @Sentinel65 . Email, co se posílá hlavním dispečerům mám nastavený přímo v kódu, tak to taky změním.

**Comment by Sentinel65** [comment]
ten e-mail je správně:  sentinel.h@gmail.com

**Comment by Sundin18** [comment]
jj, já použil jen tvojí přezdívku tady z githubu, když jste oba Jirkové :-)

**Comment by Sundin18** [comment]
Tak adresy jsou v tabulkách změněny.

**Comment by Sentinel65** [comment]
Tak to ale chce teď asi vypnout synchronizaci, dokud Jirka neupraví ten script se synchronizací, aby se ty maily v tabulce nepřepisovaly zase.

**Comment by zachyunl** [comment]
Synchronizace ma jiz vyjimku na tabulky pustenou, jenom nevim zda je hotova i zmena, kde se posilalo na UD primo z kodu? Postfix pustim, az to bude komplet.
