### ISSUE TITLE
DP - "Vydal"

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#103]
Dnes byla připomínka, že v přehledu DP nesvítí kdo DP vydal, ale kdo na něj naposledy "šáhnul". Buď přejmenujeme položku "Vydal" na něco, nebo předáláme algoritmus.

Např. opravovaný příkaz č. 13

**Comment by Sentinel65** [comment]
Pokud máme zachovat data o tom, kdo primárně příkaz vydal, tak se neobejdeme bez dalšího sloupce v tabulce, kdo záznam aktualizoval naposledy. Nemuselo by se to zobrazovat přímo v tabulce se seznamem příkazů, ale jako další položka v Detailu.

**Comment by Sundin18** [comment]
Na 38, je tedy přidáno pole se jménem vydal, které se nebude v čase oprav příkazu měnit a ponese původní jméno z "originálu" přikazu. Položka vytvořil, bude obsahovat jméno toho, kdo příkaz upravil nebo zrušil. Verze 20.01.09. Ty jména k vydal, tam budu muset asi dopsat ručně, protože u některé příkazy již mají vydané opravy.

**Comment by Sentinel65** [comment]
Tak na 38 to funguje,  jméno tabulce v seznamu toho, kdo jako první příkaz vydal zůstává, jen bych u něj doplnil ten datum, čas a CN, jako je to u toho, kdo vytvořil.

![image](https://user-images.githubusercontent.com/54531291/71994871-cbaf2800-3239-11ea-8422-b7f51ffc25a5.png)

**Comment by Sentinel65** [comment]
A jinak pozor, je třeba udělat ještě úpravu i v těle emailu, který se odesílá a v jeho příloze.
Tam je text s mým jménem. Díspečerský příkaz sepsal vedoucí (provozní) dispečer:

![image](https://user-images.githubusercontent.com/54531291/71995275-a1aa3580-323a-11ea-8298-6303a1661f9a.png)

A tady příloha PDF:

![image](https://user-images.githubusercontent.com/54531291/71995395-cbfbf300-323a-11ea-8abb-e718417523ea.png)


Tzn. přidat tam ten řádek ohledně změny:
**Změnu dispečerského příkazu sepsal vedoucí (provozní) dispečer:**

**Comment by Sentinel65** [comment]
A samozřejmě to samé, pokud to posílá přímo analyzátor.

**Comment by Sundin18** [comment]
A musí být u té opravy u "vydal" být jméno pc? To se dá dohledat v historii toho příkazu. Já takhle budu muset vymyslet, jak tu proměnou získat nebo jestli nebudu muset kvůli tomu přidat další sloupec od DB.

**Comment by zachyunl** [comment]
Honza by to rád dostal na tuto stránku. Petře vejdou se tam oba údaje? Kdo to původně vydal a kdo udělal úpravu?
![image](https://user-images.githubusercontent.com/47257941/71997349-0915b480-323e-11ea-9b82-3ed483881799.png)

**Comment by Sentinel65** [comment]
Už to začíná. Je zajímavé, že do konce roku to nikomu nevadilo a při tom jsme jim říkali, ať se na to podívají a otestují si vše a dají připomínky. Když už to je hotové a spustí se to, tak požadují zmšny, co si vyžadují podstatné zásahy do DB.

Pokud tam má být kdo vydal a kdo opravil, tak tio je na samostatné sloupce.
Nemyslím, že je nutné, aby v tabulce, muselo být, kdo opravil, to je vidět v samotném detailu.
Tam bych asi jenom opravil to jméno položky Vydal a místo Vytvořil bych dal Opravil.

**Comment by Sundin18** [comment]
Já tam nechám jen jméno a čas toho původního. Pokud by někdo chtěl zjistit jméno pc, tak se podívá do historie toho příkazu. Já to přejmenuji. Sloupec opravil přidám do náhledu tabulky.

**Comment by Sentinel65** [comment]
ok

**Comment by Sentinel65** [comment]
> Honza by to rád dostal na tuto stránku. Petře vejdou se tam oba údaje? Kdo to původně vydal a kdo udělal úpravu?

Zrovna sloupec **Opravil** tam není 2x důležitý, protože ten údaj bude v Detailu. 
Pokud tam bude, tak mi pak vysvětli, k čemu se váže ten sloupec Datum události ? Ke sloupci **Vydal** nebo ke sloupci **Opravil** ? Sami si zaděláváme na problémy.
Je třeba počítat s tím, že tam budeme muset mít v tabulce v seznamu sloupec, kde uvidí, že ten příkaz je vyřízený.

**Comment by Sundin18** [comment]
Datum události je, kdy se stal ten případ, kvůli, kterému příkaz vydávám. Např. uvázne trať na trati v 15:10, tak bude čas události v 15:10, ale příkaz napíšu třeba v 15:45. Jinak tedy na 38 je to nahrané k nahlédnutí.

**Comment by Sentinel65** [comment]
Stránka na notebook při 100 procentech zobrazení v prohlížeči. Zatím tam není záznam, kdy by byl člověk s titulem.

![image](https://user-images.githubusercontent.com/54531291/72001753-5b5ad380-3246-11ea-9dc9-6c2cf8df61b6.png)

**Comment by Sentinel65** [comment]
Mrkněte se na 38 pod Prahou na PZ 24, ST 24, DP 38 kde jsem to psal pod účtem VD Ing. Čutkou

**Comment by zachyunl** [comment]
> > Honza by to rád dostal na tuto stránku. Petře vejdou se tam oba údaje? Kdo to původně vydal a kdo udělal úpravu?
> 
> Zrovna sloupec **Opravil** tam není 2x důležitý, protože ten údaj bude v Detailu.
> Pokud tam bude, tak mi pak vysvětli, k čemu se váže ten sloupec Datum události ? Ke sloupci **Vydal** nebo ke sloupci **Opravil** ? Sami si zaděláváme na problémy.
> OK, Petr mě upozornil, že sloupec Datum události se neváže k času, kdy se příkaz vydá nebo pořídí.
> Ale už jen z toho obrázku, co Jirka poslal, je vidět že na menších obrazovkách se to bude zalamovat.
> Sloupec Vydal i Opravil navíc budou obsahovat i tituly, což ty sloupce ještě více rozšíří.
> 
> Je třeba počítat s tím, že tam budeme muset mít v tabulce v seznamu sloupec, kde uvidí, že ten příkaz je vyřízený.
> Stejně z 99 procent každý klikne na Detail, protože z té hlavičky v řádku nic nevyčte. Pro mne je tam ten sloupec Opravil naprosto zbytečný.

Na tom sloupci opravil ani Honza nijak moc netrval, jeho pálilo hlavně, že není vidět na první pohled, kdo to vydal. Klidně bych ten sloupec také vyhodil, když to máme v detailu.

**Comment by Sentinel65** [comment]
Však to teď Petr opravil, ve sloupci vydal zůstane jméno i po opravě, v detailu pak bude vidět kdo opravu provedl. Jinak jsem koukal, že i v těle mailu je to opravené včetn přílohy.
Pokud se domluvíme, že by z té tabulky tensloupec Opravil vyhodil, tak to může na ostrý.

Ještě dotaz, při tom testování a laborování s těmi příkazy - pokud v originál příkazu napíšu nějaký text a přidám tam přílohu, pak v opravách, pokud tu přílohu tam znovu nedám, tam není logicky vidět. Jen se ptám, jestli to je dobře. Jestli by v těch opravovaných v Detailu neměla být viděšt nebo aspoň nějaký odkaz, že v tom půvpodním je.

**Comment by zachyunl** [comment]
Ještě co s tím datem, tam by mělo být datum vydání DP a dalších typů?

**Comment by Sentinel65** [comment]
Nerozumím ? Jaké datum myslíš ?

**Comment by zachyunl** [comment]
Datum události, kdy nastal daný případ. Zdali to nepředělat na datum vydání příkazu? To je jen dotaz.

**Comment by Sentinel65** [comment]
> OK, Petr mě upozornil, že sloupec Datum události se neváže k času, kdy se příkaz vydá nebo pořídí.
Je to datum události, ke které se ten příkaz váže. Nechal bych to pojmenované, jak to je.

Co s tou přílohou Jirko ?

**Comment by Sentinel65** [comment]
Ještě jeden návrh pro Petra, který stojí za úvahu a ušetřil by v tom řádku nějaké to místo.
Co místo těch tlačítek Detail, Opravit a Zrušit použít piktogramy nebo nějaké významově odpovídajicí ikony, na které když najedeš myší, tak zobrazí Tool Tip a klasickým popiskem. Zadal jsem na Google dotaz na icon detail png, icon repair png a icon delete png, ty by odpovídaly.

**Comment by Sundin18** [comment]
Ikonky tam můžu dát. Dokonce jsem je tam měl, když jsem to prvně dělal. Pak jsem to dal ukázat jednomu kolegovi, co by raději a on se přiklonil k těm tlačítkům, že z nich bylo hned jasné o co jde. Ale samozřejmě, když s tím pak člověk pracuje, tak mu to dojde i z ikony, co se pod tím míní. Dát je tam klidně můžu.

**Comment by zachyunl** [comment]
> Ještě jeden návrh pro Petra, který stojí za úvahu a ušetřil by v tom řádku nějaké to místo.
> Co místo těch tlačítek Detail, Opravit a Zrušit použít piktogramy nebo nějaké významově odpovídajicí ikony, na které když najedeš myší, tak zobrazí Tool Tip s klasickým popiskem. Zadal jsem na Google dotaz na icon detail png, icon repair png, icon delete png a icon pdf png, ty by odpovídaly.
> A udělat barevný mutace by neměl být problém.

Jirko nápad dobrý, ale mám z toho obavy. Spíše se nepřeklíním. Neděláme technický web a mám obavy o lidi. Oba víte co máme za různou skladbu lidí na SŽDC a někdy ta kvalita není zrovna ideální. Jsou to hlavně provozní pracovníci a ne technici.

**Comment by Sentinel65** [comment]
Je to jedna z variant, jak ušetřit místo, kdyby se ho nedostávalo. Zatím to nech. Zruš tam ten sloupec Opravil a ještě to otestuju

**Comment by zachyunl** [comment]
> > OK, Petr mě upozornil, že sloupec Datum události se neváže k času, kdy se příkaz vydá nebo pořídí oprava
> 
> Je to datum a čas události, ke které se ten příkaz váže. Nechal bych to pojmenované, jak to je.
> 
> Co s tou přílohou Jirko ?

Co myslíš přesně s přílohou? V emailu nebo kde přesně?

**Comment by Sentinel65** [comment]
Jirko, ne ne v e-mailu, ale v těch příkazech

**Comment by zachyunl** [comment]
Ta příloha je oříšek, asi bych to prodiskutoval ještě s analýzou a nějakými vedoucími dispečery. Nechce se mi to rozhodovat z fleku, protože to budeme zase x-krát předělávat. Péťa má zítra denní, tak se poptáme v Ústí a hodíme tel. dotaz do Prahy a případně do Přerova.

**Comment by Sentinel65** [comment]
No já jsem to zmínil z toho důvodu, že v originále tu přílohu nějaký aktivní dispečer dá, pak po změně služby se přijde na to, že v tom příkaze byla nepřesnost nebo se do toho vloží analýza a změní to, ale tu přílohu už pochopitelně ikdo nepřidá v opravě. Tak jestli by tam na ní v těch opravách nemělo být aspoň nějak upozorněno. Jak v samotném detailu příkazu, ak v těch mailech.

**Comment by Sundin18** [comment]
Na 38 je to s ikonkama :-)

**Comment by Sentinel65** [comment]
Tak s tím Petře ještě počkej, na ten ostrý to dáme, až všechny tyhle věci dořešíme.

**Comment by Sentinel65** [comment]
No pěkné, za mě bych to tam nechal.

**Comment by zachyunl** [comment]
Pěkné to možná je, ale jak jsem již psal děláme to pro lidi netechnické. Zítra to schválně ukážu holkám na analýze a jsem zvědavej na jejich prvotní reakci. Vy si vážně myslíte, že lidi staršího data to dají? Já o tom nejsem přesvědčenej. Vezměte si co máme za starší lidi na analýzách a ty s Tímto dělají intenzívně. Hlavně když jim to budeme pořád měnit pod rukama, tak nás za chvíli zabijou. Dělejme vážně jenom nutné úpravy a nepřekopávejme moc design, popisky a další věci viditelné prvním pohledem.

**Comment by Sentinel65** [comment]
Byl to návrh, který jsme ani jeden neviděli, tak nám ho Petr podhodil. Myslím si, pokud s tím dělají každý den, že by si na ty ikonky zvykli. Zeptej se jich a uvidíme. Každopádně to zabírá daleko méně místa než ty 4 tlačítka.

**Comment by Sundin18** [comment]
Dejte mi pak vědět, co tedy přesně nahrát na ten ostrý server a jestli tam nechat emailovou adresu na ústeckou analýzu. Zítra to kdyžtak nahraju na ostrý, ať jim chodí i ty dispečeráky.

**Comment by Sentinel65** [comment]
Zatím s tím počkej, až se to finálně domluví s Honzou. Zítra s ním promluvíme a dáme vědět.
