### ISSUE TITLE
ZaMU tvorba PDF

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#104]
Opět máme BUG v ZaMU, když dám **Vybrat vše** a chci dát **Vytvořit PDF**, tak se nic neděje.
To samé i na 38. Nejde to ve chvíli, kdy záznam obsahuje přiřazený příkaz !

**Comment by Sundin18** [comment]
hotovo, k vyzkoušení na 38 (verze 20.01.07)

**Comment by Sentinel65** [comment]
Na 38 ok
