### ISSUE TITLE
Vyčistit kód od emailových adres a vše řešit pouze přes DB

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#105]

**Comment by Sentinel65** [comment]
Pokus by to šlo, hodně by nám to zjednodušilo práci a změny by byly rychleji realizované

**Comment by Sundin18** [comment]
Jediná adresa,která je na tvrdo napsaná v kódu, je adresa na ústředního dispečera. Dnes bych měl dodělat ti posílání příkazů na analýzy.

**Comment by Sentinel65** [comment]
Lze to udělat tak, aby to nebylo v kódu, ale dal se udělat odkaz na DB ?

**Comment by Sundin18** [comment]
Ano, tak to je dělané. Jak říkám, jediný je ten ústřední dispečer, ale na to pak udělám tabulku v DB, takže bude taky přes DB.

**Comment by Sentinel65** [comment]
Dobře
