### ISSUE TITLE
ZaMU námět

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#107]
Další námět po dnešním zjištění, že v **Neprojetých trasách** se nevyplňuje položka **ZaMU číslo**.
V Přerově to plně pochopili a zatím tam mají vyplněno vše - pravda těch záznamů tam mají daleko méně.
V Praze to opět žije svým "vlastním životem". Dnes jsem ráno rozeslal VD a provozním mail s postupem, jak to **ZaMU číslo** v Neprojetých trasách mají vyplňovat. Někteří to pochopili a začali to dělat.
Pak jsem narazil na další kategorii problému, kdy v **Neprojetých trasách** je důvod Dispozice dopravce, ale v ZaMU se tento zápis vůbec neobjeví, takže logicky v Neprojetých trasách není co přiřadit. Mluvil jsem s Honzou Frajerem a ten mi potvrdil, že toto by v ZaMU mělo určitě být. Zítra si sednou s Jirkou Urbanem a vykomunikují si to.

Mám obavu, jak to obvykle bývá, když se něco převede na elektronickou podobu, že ty lidi spolu přestávají normálně komunikovat. Něco se hlásí přímo VD, něco patrně ví dříve PD.

Mám návrh udělat něco podobného jako je u příkazů, tzn. že se tam objevují Nepřiřazené příkazy u VD, tak by se tam udělalo i pro ty Neprojeté příkazy. Dokud by nebylo spárované číslo ze ZaMU v Neprojetých trasách, tak by mu tam viselo pořadové číslo NT.

Nebo tomu necháme chvíli čas a uvidíme, jak se projeví vzájemná domluva analýzy a VO.

**Comment by Sundin18** [comment]
Toto jsme právě včera s Jirkou @zachyunl řešili (tam vznikl i ten námět kvůli NAD) a já dokonce na tom už začal pracovat. Problém je, že to není tak snadné, jak to na první pohled vypadá a vyžaduje si to více času (tipuju 2-3 dny) a vždycky se objevil nějaký bug nebo návrh na změnu, co si žádalo přednost. Ještě ti k tomu zavolám ;-).

**Comment by Sentinel65** [comment]
No proto jsem to psal, asi není vždy nutné okamžitě na nečem začít hned dělat, ale vykomunikovat to mezi sebou a analýzou. OK jen ve 13 hodin jdu k doktorovi.

**Comment by zachyunl** [comment]
Neboj my to komunikovali i dnes s Analýzou a přímo Honzou Frajerem, který tady je. Dokonce připustil sám nahrazení "zeleňáku" v nějaké vzdálené budoucnosti. Oni tam píšou něco s NADkou a pak to dále posílají. Musíme zjistit všechny detaily co, kdo a jak s tím pracuje. Sám jsem mu řekl, že to je na delší vývoj v rámci měsíců. Nikdo neočekává, že se to všechno udělá okamžitě. Tu NADku bych opravdu vzal ze všech stran a co nejvíce informací, hlavně budeme potřebovat zeshora. Prý s tím snad pracuje i přímo Mirek, dále Radek Bejšák a asi někdo další. Něco se prý odesílá v nějaké redukované formě na ČD a možná i na jiné směry.

**Comment by Sentinel65** [comment]
No to je ale to, co jsem psal. Že budeme snažit upravovat Šedivák, aby byl poplatnej tomu jejich zeleňáku :-) Data pro ten zeleňák by se měli primárně zjišťovat v ISOŘ aplikacích.

**Comment by zachyunl** [comment]
Nech to, až uděláme analýzu zeleňáku, čekám až mi pošle nějaký data Lenka, ať se máme z čeho odpíchnout. Já si osobně myslím, že to je mix. šediváku a ISOŘ aplikacích. Uvidíme co s tím.

**Comment by Sentinel65** [comment]
Opravdu bych se Honzi zeptal, odkud primárně čerpá data pro ten jejich zeleňák. Pokud ti odpoví, že ze Šediváku, tak je tady něco hodně špatně.

**Comment by Sundin18** [comment]
Na 38 je nasazena verze 20.01.10. Nově tam je zobrazování neprojetých tras v položce "Vlivy" v záznamu ZaMU, které jsou přiřazené k záznamu v ZaMU. Je tam text "Odřeknuto: .... ". Tento text je tam okoukaný z toho, jak to tam zapisovala analýza. Tak mrkněte, jestli je to dobrý nápad.
Přiřazení neprojeté trasy se tedy nejeví jako změna záznamu.

**Comment by Sentinel65** [comment]
Petře, funguje to pěkně, je dobře že to je bez té změny záznamu.
