### ISSUE TITLE
Příkazy - rušení záznamu - důvod zrušení

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#108]
Při rušení záznamu je další námět, ještě nějak udělat při rušení možnost zadat důvod rušení (nepovinně). Toto by se hodilo primárně analýze u všech typů příkazů.

**Comment by Sentinel65** [comment]
Pořídit /  Zrušit příkaz může analyzátor, vedoucí dispečer, provozní dispečer.
Nápad - kliknutím na **tlačítko Zrušit** by se vyvolalo okno, kde by byla textová volba tří možností (nebo víc, pokud si analýza vymyslí). Jednu z těch voleb by uživatel použil a pak by se mu následně objevilo varovné okno, které tam už je teď tj. Chcete opravdu zrušit záznam #xx. Do mailu by se vybrala ta textová část, kterou uživatel vybral.

**Comment by zachyunl** [comment]
Tam jde o to, že nastávají situace, které jsou popsatelné. Např. jsem zrušil DP, protože bylo dodatečně zjištěno, že to je problematika jiného subjektu. A tento text by rádi někam zapisovali, aby to bylo dohledatelné i v budoucnu a vidělo to oddělení Radka a případně dalších.

**Comment by Sentinel65** [comment]
No není problém, pokud ty situace dokáží krátce a výstižně popsat, dá se to tam jako jedna z  voleb.

**Comment by zachyunl** [comment]
Tady si myslím, že to bude spíše na volné textové pole. Podle mě nejsme schopni popsat situace, které mohou v reálu nastávat.
