### ISSUE TITLE
Příkazy - odpověď

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#109]
Dostat do systému odpovědi na Příkazy (všechny typy)
**Opět na hlubší analýzu a neřešit okamžitě, ale zjistit více informací.**
Funkcionalita pravděpodobně pouze pro analýzu, kde by bylo nějaké tlačítko "Odpověď", kam by analyzátor založil již doručenou odpověď od dopravce, z PO apod. Odpovědi jsou různého typu a většinou formou emailu, ale někdy to je i jako příloha. Zde pozor na oprávnění, aby to bylo vidět pouze pro analýzu a vyjmenované kontrolní orgány. Myšleno odpověď aby neviděl PD, VD apod.

Tímto bychom měli v systému uzavřený kompletní cyklus "Příkazů" od vzniku až po skutečné vyřízení.

**Comment by Sentinel65** [comment]
Řešení se myslím není až tak hrozně složité.
Napadá mě přidat do formuláře u příkazu až dolů další možnost "Vybrat soubor", která by byla pojmenovaná třeba "Odpověď" a byla by **viditelná pouze pro roli analyzátor (administrátor)**
V Detailu příkazu by se pak jako je to u přílohy, kde se objeví odkaz "Příloha ke stažení", objevil odkaz "Odpověď ke stažení", která by byla opět viditelná jen pro definované role Analyzátor, Kontrolér analýzy, Kontrolér CDP, Administrátor.

**Comment by zachyunl** [comment]
JJ toto je přesně ta cesta, kterou bychom měli jít. Jde jim primárně o to, že dnes nemají v šediváku přehled o vyřízených událostech, protože mi to ukončujeme v DB ještě před odesláním na subjekty a z pohledu "produktu" to nemáme dotažené až do finále, kdy vlastně "produkt" zaniká.
