### ISSUE TITLE
Dispečerské příkazy - seznam

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#11]
Já jen abych to nezapomněl :smile: Dispečerské příkazy: vpravo jak je ten seznam, tak si uvědomuji, že už nebude třeba to těm provozním přeposílat do mailu kvůli pořadovému číslu DP, protože DB jim už to sama automaticky nabídne. Ale v tom případě ten seznam tam bude bobtnat a bude třeba tam udělat taky nějaké filtry (jaké DP byly vydány v konkétní den, jaké DP vydal konkrétní zaměstnanec, jaké DP byly pořízeny konkrétním pracovištěm).

**Comment by Sentinel65** [comment]
Bude potřeba udělat řazení sloupců a také vyhledávání aspoň podle data a jména.
Zaujala mě ale možnost propojení - pokud by to šlo opět pouze pro definované role - tak udělat v Závady a mimořádné události v položce Číslo DP:  zobrazené číslo jako klikací odkaz, které by rovnou otevřelo detail toho DP.

**Comment by Sundin18** [comment]
Filtr na tabulku DP mám rozpracovaný, ale pak jsem se věnoval těm issues s vyšší prioritou. To propojení bylo právě takhle zamýšleno do budoucna jako takové "vylepšení" ;-)

**Comment by zachyunl** [comment]
Oki toto zatím počká.

**Comment by Sundin18** [comment]
Vytvořeny filtry na tabulku DP (Verze 19.09.10)

**Comment by Sentinel65** [comment]
Jak to ted zkouším testovat a píšu tam vymyšlené záznamy, tak jsem ve formuláři **Závady a mimořádnosti**  narazil na problém, když tam **do záznamu přidávám číslo DP, tak z té nabídky, která se mi ukáže podle těch čísel nerozezná** PD (VD nebo AJŘ) **co je dp a co PZ**. Takže to budeme muset ještě pozměnit nebo to nějak rozlišit.

**Comment by Sundin18** [comment]
Jj, to mám v úmyslu k tomu číslu ještě dodat, jak to pak budu "napojovat"

**Comment by zachyunl** [comment]
Konečně se mi podařilo přemluvit Postfix. Přes telnet jsem již schopen odesílat emaily, tak to Petře můžeš příležitostně zkusit napojit na aplikaci.

**Comment by Sentinel65** [comment]
Ještě se vracím k těm filtrům pro DP. ST. PZ

Teď je nastavené, že dle výběru pracoviště a radio buttonu (DP, ST, PZ) si vyberu vpravo filtr  (Všechny, a dále dle pracoviště). 
Jenom chci upozornit, že počítáme s rolemi, které budou nad těmito pracovišti (provozní, analýza), zde je myšleno vedení CDP a O11, tak bude potřeba nastavit role tak, aby se např. vedení CDP PHA v případě DP, ST a PZ nezobrazoval vůbec formulář, ale jenom výpis záznamů databáze a to všechny dohromady DP, ST, PZ za obě oblasti PHA i UNL. 
O11 pak zase pouze jenom výpis záznamů, ale tentokrát už za obě CDP.
Je to jiné zobrazení dat z DB do tabulky podle přidělené role a s příslušným řazením, tříděním a filtrováním.
