### ISSUE TITLE
ZaMU - připomínky ústředního dispečera

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#110]
Asi nejde o klasický BUG, ale:

- ÚD by byl rád, kdyby jsem mu ze ZaMU neposílali na mail změnu záznamu, kterou vyvolá **Ukončení šetření** od analyzátora
- filtr **Stav** vpravo zobrazuje číselné hodnoty POUZE viditelných položek na stránce. Stalo se jim, že neviděli **Zastavený provoz** někde na přerovsku, protože byl v pořadí až někde na další stránce, kterou musel rolovat. Dájí se ty hodnoty v tom filtru **Stav** nastavit přímo z DB, aniž by rozhodovalo, zda je ten záznam na stránce viditelný či ne ?

**Comment by Sundin18** [comment]
1. hotovo (verze 19.01.09)
2. v procesu

**Comment by Sentinel65** [comment]
Ok vyzkouším, jen dotaz pro jaké role je tabautomatická akualizace na 10 minut ?

**Comment by Sundin18** [comment]
pro všechny

**Comment by Sentinel65** [comment]
A je tam ošetřeno, aby se neshodil rozepsaný záznam ?

**Comment by Sentinel65** [comment]
Na té 38 ten refresh asi neotestujeme, když je vypnutá synchronizace.
Nechal jsem to na pohledu ZaMU skoro půl hodiny s otevřeným oknem s vyplněným zápisem nového záznamu a nic se nedělo. Netuším jak to má fungovat, to by bylo taky dobré napsat, abych věděl, zda to reaguje správně nebo ne.

**Comment by Sundin18** [comment]
Na ostrém to funguje. Napiš si číslo #ZaMU, které máš úplně nahoře stránky a za 10 minut se podívej, bude tam jiné. Tedy za předpokladu, že tam někdo něco přidá. Seřaď si to pro jistotu podle "Aktualizováno" nebo podle "Čísla ZaMU", protože podle zahájeno se nemusí nový záznam dostat nahoru.

**Comment by Sundin18** [comment]
Na 38 to můžeme ozkoušet, že tam něco přidám já a ty se pak podíváš za nějakou dobu ;-)

**Comment by Sentinel65** [comment]
Jo na ostrým to vyzkouším.
Pořád jsi mi neodpověděl na to, jak se to chová, když má VD rozepsaný záznam.

**Comment by zachyunl** [comment]
Petr má asi předávku. Neboj nic mu to neshodí i při rozepsané činnosti. Probíhá to jako když si představíš 2 vrstvy na sobě. Jedna je pro případný zápis a druhá zažádá o aktualizaci dat. Jsou tam 2 podmínky, jedna na data a druhá na vyžádání celkového čísla z DB na zastavený provoz. Více technicky to umí Petr.

**Comment by Sentinel65** [comment]
ok

**Comment by Sundin18** [comment]
Ona se neaktualizuje stránka jako taková. Jen se udělá nový dotaz na záznamy a ty se zaktualizují. Takže se to děje i při otevřeném modálním okně.

**Comment by Sentinel65** [comment]
teď mi začaly chodit maily z ostrého ze ZaMU a tam jsem si teda všiml, že v tom textu v těle zprávy nemáme vůbec ten řádek Kdo poslal, odkud a v kolik.

![image](https://user-images.githubusercontent.com/54531291/72727378-10688680-3b8b-11ea-91c0-073974cfa8e9.png)

Už jen pro kontrolu, jak ta pošta chodí by tam chtělo ten řádek v tom těle mailu mít včetně těch oprav, tzn. datum a čas - jméno titul - computer name

**Comment by Sundin18** [comment]
To tam nikdy nebylo.

**Comment by Sentinel65** [comment]
Asi nebylo, ale když se teď koukám, jak mi ty maily chodí, tak si říkám, jak se v tom vůbec mohou vyznat. 
A když pak kontroluju co z těch mailů chodí, tak by tam ta řádka dost pomohla.

**Comment by Sundin18** [comment]
Já osobně bych se jen podíval na číslo ZaMU, vyhledal ho v Šediváku a zjistil, co se změnilo. Nic jiného bych v tom emailu nepotřeboval asi.

**Comment by Sentinel65** [comment]
No takto to asi nedělají myslím, proč jinak by chtěli nastavovat druh a velikost fontu v tom mailu ?
Myslím, že si z toho kopírují ten text asi ...
OK, zatím to nech bejt

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.13
