### ISSUE TITLE
Příkazy - shrnutí

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#111]
Mluvil jsem teď s Honzou Frajerem, takže tady popíšu nějaký souhrn toho, co jsme domluvili (je to projednané i analýzou v Přerově):

1. Odesílání mailu ze všech příkazů za oblast Ústí nad Labem tedy Petře vrať na adresu CDPUNLanalyza@szdc.cz, s tím, že  tam Petr N nebo Jirka Z udělají v Outlooku pravidlo na přeposílání všech příkazů na schránku CDPPHAanalyza@szdc.cz, to se může udělat hned na tom ostrým
2. **sloupec Opravil** zůstane tedy
3. Pro roli analyzátor doplnit do formuláře checkbox **Nepřiřazovat k záznamu**, aby se příkaz vytvořil a okamžitě s ním se nastavil i ten příznak Nepřiřazovat k záznamu, aby se nemusela dělat oprava. 
4. V seznamu příkazů sloupec Datum události změnit na **Datum vydání**
5. Údaj **Datum  události** bude po domluvě pouze v Detailu
6. Ukazoval jsem Honzovi na jeho PC na 38 **ty ikony v příkazech a není proti tomu**, aby tam byly, když se na ně najede myší, jsou tam popisky
7. Doplnil bych tam **ikonku sponky** jako index, že **v jednom z příkazů (originál, opravy) je vložena příloha** (včetně popisku po najetí myši na ikonu) - tohle Petr vyřešil těmi spojenými ikonkami 
8. Abychom ušetřili místo v řádku a další ikonu, tak text řádku by se označil např. zelenou barvou, že příkaz je kompletně vyřešený plus ToolTip při najetí myši na řádek vypsat **"Příkaz vyřešen"**
9. K tomu je potřeba ve formuláři přidělat řádek a v něm checkbox **Příkaz vyřešen**, který bude viditelný pouze pro analyzátora (administrátora)
10. Jak jsme se domlouvali, ve formuláři pod text Příloha přidat další volbu **Odpověď** s možností vložení přílohy (navíc formáty dokumentů MS Office a PDF) opět max 5 MB, toto opět **_viditelné pouze pro roli analyzátora a administrátora_**, je třeba počítat s tím, že těch vložených příloh může být víc. V seznamu příkazů nastavit viditelnost příloh s odpovědí opět **POUZE pro role analyzátora a administrátora**. Bavili jsme se, že by to bylo i pro Kontrolóra analýzy, ale k této roli už jsou přiřazeni i lidi od Martina Neumaiera. Ty odpovědi mohou obsahovat citlivé údaje, takže pokud bychom to rozšířili i na Kontrolora analýzy, bylo by třeba vytvovořit novou rolu BonusMalus pro to druhé oddělení a nastavit to tak, aby ty přílohy s odpovědí prostě neviděli. Toto se musí pořádně promyslet.
11. Toto na 38 již máme, při opravě příkazu se nemění jméno toho, kdo vydal origimál příkaz, ale v detailu se objeví řádek **Opravil** se jménem, datumem a časem a CN
12. **zrušení příkazu** - tady je požadavek na to, aby mohli volnou formou zapsat důvod zrušení příkazu, tzn. po kliknutí na ikonu Zrušit, by se mělo objevit okno, kde by volnou formou napsali důvod zrušení, pak přes tlačíko OK by se objevilo ono varovné okno, které tam již máme. Teprve po odklepnutí dalšího OK by se záznam uložil, odeslal by se email s textem proměnné, kterou vyplnili jako důvod. **Po zrušení záznamu** chce Honza, aby se v **Detailu** objevil další řádek **Důvod zrušení**, kde by byl také ten text. 
13. Ještě by jim pomohlo, kdyby v **příkazech ST (POUZE tady)** byl řádek nějak označen.  Zase to můžeme udělat barvou textu v řádku plus ToolTip při najetí myši na řádek vypsat **"Zpoždění do 5 minut"**) za předpokladu, že položka **Doba zpoždění** by byla menší než 5 minut. Radek říkal, že tyto záznamy by se dopravcům snad ani neposílaly, pouze bychom je evidovali, tak aby to analyzátor hned viděl z toho seznamu. tzn. do 5 minut (mimo) označit, nad 5 minut (včetně) neoznačovat.
14. Do vyhledávání dle datumu (kalendář) přidat filtr za konkrétní kalendářní rok.
15. Vše nejdříve na 38 pořádně otestovat.

Tak schůzka dneska 15.1.2020 proběhla a Radek Bejšák s těmito připomínkami a požadavky souhlasí.
Jinak jsem se dozvěděl, jak vlastně pracují. Ty Neprojeté trasy je jeden ze záznamů, kde je předpoklad, že tam nebude moc chyb, protože se to dělá de facto ručně. Kolikrát jim přijde požadavek na sestavu třeba za uplynulý rok, nebo podle tratí (ty jsme s úspěchem zrušili při přechodu na nový Šedivák :-)  ale to byl jen jeden případ, nebo chtějí seznam Neprojetých, který se váže ke konkrétní události - toto dneska již máme, stačí vyhledat v Neprojetých konkrétní číslo záznamu a zobrazí se všechny řádky, u nichž toto číslo je nastaveno. Nebo chtějí Neprojeté trasy podle dopravce. Ten sloupec tam bohužel nemáme, divím se, že to nechtěli, zase tam něco musí ručně psát, takto to mohl být jeden z filtrů.

**Comment by Sundin18** [comment]
1. hotovo (verze 20.01.09)
2. hotovo (verze 20.01.09)
3. hotovo (verze 20.01.09)
4. hotovo(verze 20.01.09)
5. hotovo(verze 20.01.09)
6. v procesu
7. v procesu
8. v procesu
9. hotovo(verze 20.01.09)
10. v procesu

**Comment by Sundin18** [comment]
Je to nahrané na 38

**Comment by Sentinel65** [comment]
Petře, není to tak, jak jsem psal. Jednak jsi spojil tu ikonu "sponka" s detailem dohromady, což jsem nechtěl a za druhé a to podstatné, psal jsem, že by se ta ikonka měla objevit ve chvíli, kdy v originále nebo opravách příkazu bude příloha s stejným textem. Teď jsem opravil na 38 DP 30 pod Prahou a ta ikona tam není vidět. Ale když si otevřeš ty původní, tak ve 4. opravě je příloha.

**Comment by Sentinel65** [comment]
Pokud dokážeš rozlišit u te spojené ikony, že příkaz nemá přílohu a bude tam popis Detail a originál nebo opravy přílohu mají a v popisu bude Detail a originál příkazu nebo opravy obsahují přílohu, tak ta spojená ikona nevadí

**Comment by Sundin18** [comment]
Ta ikonka detail se váže na aktuální příkaz. Takže pokud ten nemá přílohu, není tudíž ikonka zobrazena. Jestli tomu dobře rozumím, ty chceš, aby se ikonka sponky zobrazovala vždy, když je v jakékoliv opravě příkazu nebo v jeho aktuálním stavu obsažena příloha?

**Comment by Sentinel65** [comment]
Ano

**Comment by zachyunl** [comment]
> Mluvil jsem teď s Honzou Frajerem, takže tady popíšu nějaký souhrn toho, co jsme domluvili (je to projednané i analýzou v Přerově):

> * na 38 z těch příkazů vyhoď ten **sloupec Opravil**
Jirko jenom jedna poznámka, Honza Frajer hovoří za všechny ved. směny, provozní dispečery, kontroléry CDP? Uvědom si, že tento zásah ovlivní všechny tyto lidi. Např. Petrovi Novotnému se tato položka líbila a chce jí tam. Já s tím také nemám problém a když byl u toho Milan Jakubec, tak se mu položka také zamlouvala a holky z analýzy z Ústí byly také pro, když jsme porovnávali ostrý server s testovacím. Takže to máš 5 názorů.
Proto říkám a trvám na tom, že jakékoliv takovéto změny budou konzultovány a schváleny na všech směrech a hlavně se nebudou dělat takovéto úpravy denně. Není vážně důvod to stále měnit uživatelům pod rukama, pokud se nejedná o nějaký bug.

**Comment by Sentinel65** [comment]
Ano ano, ale uvědom si jednu skutečnost, jak píšeš 5 názorů, a všem podle jasného klíče asi těžko vyhovíme. Na jednu stranu se to snažíme udělat přehledné a také čitelné. A řekli jsme si, že do toho řádku přibudou další údaje (index přílohy a index vyřešeného příkazu). A opravdu údaj o tom, kdo kdy opravil příkaz asi nemusí být nutně přímo v řádku v seznamu, když je obsažený v Detailu, nemluvě o  tom, že ty opravy asi nebudou až tak časté, i když se vyskytují. A druhá věc, většinu těch oprav si dělá vydavatel sám, v menším množství pak přímo analýza. Pokud se kdokoli z těch 5 lidí na ten seznam podívá, určitě si klikne na Detail, protože z toho samotného řádku nic moc nevyčte.
Tohle je také o prioritách a důležitosti zobrazovaných údajů a tady zastávám názor, že ten sloupec Opravil nění až tak stěžejní. Do teď to tam nebylo a nikomu to nevadilo, až když s tím přišel Honza.
Je to úplně to samé, jako když jsem pak změnil název sloupce Datum události na Datum vydání, protože to je pro analýzu stěžejní údaj, podle kteréhio zjišťují 10 denní lhůtu na odpověď.

**Comment by zachyunl** [comment]
Ano teď jsi si na to přesně odpověděl - přehledné. Vedoucího dispečerů bude přesně zajímat ten rozdíl jestli je stejné jméno kdo DP vydal a kdo do toho dodatečně hrábnul. Sám jsi dělal jejich vedoucího, tak si to představ v praxi. Nebudeš prolézat položku po položce v detailu, tam půjdeš až uvidíš něco podezřelého na první dobrou.

**Comment by Sundin18** [comment]
Ikonka přílohy zobrazena. Pokud je příloha v aktuálním záznamu, tak se zobrazuje v tlačítku detailu, a pokud je příloha součástí z některých opravených příkazů, tak je součástí tlačítka "Původní". Je to vidět na 38.

**Comment by Sentinel65** [comment]
Jirko neblázni a nebazíruj na prkotinách. Tohle opravdu není věc, kvůli které bychom se měli dohadovat,
VD si každopádně každej příkaz otevře přes Detail, když se mu zobrazí v Nepřiřazených příkazech, už jenom proto, aby věděl co vlastně má zapsat do záznamu v ZaMU, nebo který záznam patří pro daný příkaz. Takže prvotně stejně vidí Detail, který přiřadí do ZaMU a pak už ho to moc nezajímá.

Daleko podstatnější věci jsou k řešení než pitomej sloupec Opravil. Teď když jsem ti to psal, tak jsem se podíval na ostrý a zjišťoval, koli těch oprav z těch 44 (1 je zrušenej) příkazů tam je. Celkem 11. A když jsem si je začal jeden po druhém rozklikávat, abych zjistil co tam je, tak jsem se nestačil divit.
Schválně si to projeď.

Petře, tpo j prosím tě i pro tebe, protože mám pocit, že se tam nějak pondila data:

ST 8 -  v originále chybí jméno, kdo vydal, v seznamu v řádku je, v 1. opravě je Lenka Jakubcová, ve 2. opravě je položka Vydal opět prádzná, v DEtailu pak to jméno v položce Vydal opět je
PZ 32 - je tam priginál, 1. oprava a Detail, kde je text stejný a čas vytvoření záznamu také 7.1.2020 11:03
ST 33 - originál a 3 opravy naprosto stejný text a různé časy, chybí jméno v položce Vydal, v Detailu pak dopsaná poznámka, položka VYdal vyplněná původním jménem z originálu
ST 36 - úplně to samé jako ST 33

**Comment by Sentinel65** [comment]
Petře děláte si srandu s tím podělwným sloupcem ?

**Comment by Sentinel65** [comment]
Chjo, jestli vám teda nevadí, že tam ji 2x ikona sponky, tak b bylo aspoň vhodné, aby se tam uzpůsobily ty popisky v Toolo Tipu. 
Detail samostatně bez přípony - Detail 
Detail s přílohou - Detail obsahuje přílohu
Původní samostatně bez přílohy - Původní 
Původní s přílohou - Původní obsahuje přílohu
Kdyby tam byla ta ikonka sponky samostatně s popisem Originál nebo opravy obsahují přílohu, nebylo by to jednodušší ?


![image](https://user-images.githubusercontent.com/54531291/72084069-23fe2c80-3303-11ea-97c1-a186670f0a78.png)

**Comment by zachyunl** [comment]
Já nebazíruju na prkotinách jenom se Ti snažím vysvětlit následující:
* Se systémem pracuje dnes přes 300 lidí, jasně že aktivních méně, ale je nežádoucí jim tam dělat každou chvíli změny
* Je nutné se na problematiku dívat z více úhlů pohledu a neřešit to okamžitě za každou cenu. Vždy má řešení více možností. 
* Nechci se dostat do situace, že si na nás někdo bude za chvíli stěžovat, že to děláme diletantsky
* Máme tam tuším 9 rolí, ale v řešeních vytrhujeme a upřednostňujeme jenom část
* VD jsem myslel vedoucího dispečerů třeba Petra Novotného, který má právě roli kontrolera
* je to kolektivní projekt
* Dnes jsem náhodou poslouchal diskuzi k e-neschopenkám a výtky od doktora. Nevzali je do řešitelského týmu. Pořád jim podhazují nové verze. Systém stojí třeba 3/4hod než se něco zaktualizuje. Prostě hrůza z pohledu uživatele.

**Comment by Sentinel65** [comment]
V pořádku, stejně mi nevymluvíš, že ten sloupec tam je zbytečně. Pokud se někdo ozve, že je něco špatně a VO to bude kontrolovat, tak jde VŽDY po kokrétním příkazu.

Spíš ať se Petr podívá na ta data u těch příkazů z ostrého, co jsem vypsal.

**Comment by Sundin18** [comment]
Musel jsem udělat opravy těch příkazů, abych doplnil, kdo příkaz vytvořil. Vyplnil jsem to jen do těch konečných, do oprav ne. Možná to tam doplním, jak bude čas. Stejně tyhle příkazy za chvíli budou v zapomnění. 
Když udělám ikonku samostatně, tak to bude působit jako tlačítko a na první dobrou to bude lidi plést a věřím, že každý se pak bude na to snažit klikat. Tohle si myslím je docela k pochopení, ale klidně tam doplním ty popisky.

**Comment by Sundin18** [comment]
Jinak teď jsem jen pro zajímavost ukázal ty ikonky kolegovi a překvapil, protože pochopil hned, že si myslí, že to obsahuje nějakou přílohu, aniž by to někdy jindy viděl.

**Comment by Sentinel65** [comment]
Ale jo, je mi jasné, že většina lidí to z těch ikon snadno pochopí. Ale pro jistotu ty popisky tam dej a ty ikony tedy nech, jak to je. 
Podívej se na PZ 43 na 38, ještě že jsme ta tlačíka vyměnili za ty ikony.

**Comment by zachyunl** [comment]
> V pořádku, stejně mi nevymluvíš, že ten sloupec tam je zbytečně. Pokud se někdo ozve, že je něco špatně a VO to bude kontrolovat, tak jde VŽDY po konkrétním příkazu.
> 
> Spíš ať se Petr podívá na ta data u těch příkazů z ostrého, co jsem vypsal.

Jirko ale to není myšleno na reakce ex post, právě že toto je ideální nástroj na proaktivní přístup pro vedoucí zaměstnance, aby měli možnost určité kontroly. Nevím jestli jsi mluvil s někým z vedoucích z tohoto úhlu pohledu? V tomto bych řekl, že máme zatím rezervy, protože jsme to od začátku nijak moc neřešili. Ono se dá očekávat, že to časem přijde, až tam nateče nějaké větší dat. Petr N. z toho byl nadšený, že si pustí Příkazy když přijde do práce a na první pohled vidí něco podezřelého. Jinak vychvaloval vyhledávání, že se to nedá srovnat s původní verzí.
Očekávám že se možná budeme zabývat i nějakými statistickými sestavami, možná nějakými pohledy na míru apod., třeba se bude vymýšlet i něco dynamického ale to všechno ukáže čas. Teď bych to chtěl nechat minimálně do jara, ať tam natečou data. Pak nějaká porada s lidmi ve stylu co jsme měli v listopadu.

**Comment by Sentinel65** [comment]
Ano Petr N přijde do práce, pustí si Příkazy a na první pohled vidí něco podezřelého - patrně dle datumu tam jsou nové příkazy, jsi určitě myslel. Výborně a co udělá ??? Podívá se do Detailu. Nutně musí, protože ten řádek mu sám o sobě nic neřekne. K tomu tam opravdu ten sloupec Opravil se jménem nemusí být, už i proto, že u něj nemá datum a čas, tyto údaje má stejně v Detailu.

**Comment by zachyunl** [comment]
Podezřelé je právě samo o sobě pokud vydal DP Zachař a Horký ho opravil. Toto ho praští do oka a řeší už detail, který nevidí.

**Comment by Sentinel65** [comment]
Ale jo dobře.

**Comment by Sundin18** [comment]
Tak je to tedy i na ostrým (verze 19.01.09) - sloupec opravil, ikonka přílohy

**Comment by zachyunl** [comment]
![image](https://user-images.githubusercontent.com/47257941/72179264-d823b400-33e4-11ea-9b33-93b9e2da716c.png)
Nemělo by zde být v položce vydal i CN počítače?

**Comment by Sentinel65** [comment]
Ano měl

**Comment by Sentinel65** [comment]
Ale Petr tam má problém uvést CN v obou sloupcích myslím. Takže by to asi bylo lepší u toho Vydal

**Comment by Sundin18** [comment]
Je to doplněno na obou 38 i ostrý. Verze 20.01.10

**Comment by zachyunl** [comment]
Mám obavy, že tam je bug. Nejde zobrazit detail u všech typů od 9.1.2020 nějaké polední hodiny. Ranní příkazy ještě zobrazím a odpolední a dále ne.

**Comment by Sentinel65** [comment]
> Je to doplněno na obou 38 i ostrý. Verze 20.01.10

To bude nejpravděpodobněji touto "opravou", to je poslední, co se v příkazech dělalo.

**Comment by Sentinel65** [comment]
Tak mám poznatek, na 38 jsem zkusil u DP 44 opravu příkazu, poté co se oprava uložila, tak na tom uloženém DP 44 již zobrazení Detailu funguje.

**Comment by Sundin18** [comment]
Na 38 oprava zobrazení detailu Příkazu v případě, že nemá žádnou opravu. Verze 20.01.11

**Comment by Sentinel65** [comment]
I po této opravě nefunguje korektně viz . Watsapp tzn u těch které neměly opravu se po opravě v původném nezvrazí u Vydal nic viz. DP 18 v původním 1. Oprava

**Comment by Sundin18** [comment]
U bodu 10 je problém, pokud bude mezi analýzou a příjemcem pokračovat komunikace. Ani tak není problém ukládat více odpovědí k jednomu příkazu, ale jak uchovávat další dotazy analýzy?
Napadá mě možnost, že by si při ukládání další odpovědi přidali k jejímu textu i svůj dotaz.

**Comment by Sentinel65** [comment]
Komunikace s dopravci probíhá na úrovni Spisové služby, tzn. že i analýza si může svůj vlastní dokument vložit jako odpověd.
Otázka je, jestli by spíše šlo odkaz zobrazit s textem a formátem Odpoved1_datumcas.
Každopádně ohledně+ tohoto můžeme analyzátory ještě pořádně vyzpovídat.

**Comment by zachyunl** [comment]
Co mám informaci, tak to není vždy na úrovni spisovky. Buď je to věc závažnosti informací, nebo možná zvyková. Co byl Honza Frajer v Ústí, tak když jsme to rozebírali, tak hovořil o klasickém emailu

**Comment by Sentinel65** [comment]
Ne ne, od nás k dopravcům to je **VŽDY na úrovni Spisové služby**. Dopravci nic neukládá, aby nám poslal odpověd na mail příslušné podatelny, čímž by se ta odpověď do té spisovky dostala automaticky. Takže bohužel to zpětně posílají většinou mailem.

**Comment by Sentinel65** [comment]
Nebudu zákládat nové issues, nějak mi uteklo, že jste se tam domluvili na změně formátu vygenerovaného PDF u Provozní závady.
Dneska přišel Luděk Baško (pro Petra vedoucí oddělení dálkového řízení) s Honzou Frajerem. že by chtěli ty odpovědi také vkládat jako přílohu.
Takže nakonec aby se to moc nekomplikovalo, tak v případě dálkového řízení si vedoucí připraví šablonu formuláře ve wordu, kde jen dopíše o jaký příkaz (číslo, typ a ze kterého dne to je) jde, napíše k tomu v tom wordu nějaké své vysvětlení, převede word do PDF a po domluvě s analýzou, která s tím vyjádřením bude souhlasit to nahraje jako přílohu "Odpověď" ke konkrétnímu příkazu.
Takže v Detailu se můžou ve finále objevit odkazy **"Příloha ke stažení" a "Odpověď ke stažení"**

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.19). Vzhledem k tomu, že nám samotný příkaz začal "bobtnat", tak jsem to pojal trochu jinak s tím, že se samotný příkaz otevře na samostatné stránce, už ne jen jako okno. Stránka je rozdělena do 3 sloupců. 
1. sloupec - obsahuje samotný příkaz (stejné zobrazení jako bylo v modálním okně) - vidí všichni
2. sloupec - obsahuje stav příkazu + akce, které lze na příkazu dělat (nepřiřazovat k záznamu, zrušit přiřazení k ZaMU, přidat odpověď, ukončit příkaz). Akce (tlačítka) se zobrazují podle role uživatele.
3. sloupec - obsahuje výpis odpovědí. Lze ukládat text i přílohu. Odpovědí lze ukládat neomezeně.

Vše je tedy na 38 k testování.

**Comment by Sentinel65** [comment]
Tak k tomu, co sji udělal pár připomínek od Honzi:

1. V Deatilu v pravém okně změn popisek Odpovědi na **"Projednání"**
2. Nahrané přílohy (originál příkaz, včetně jeho oprav) v Detailu vlevo přejmenuj z Příloha ke stažení tak, aby se **zobrazoval název souboru** 
3. Nahrané odpovědi v Detailu v okně Projednání přejmenuj z Soubor s odpovědí tak, aby se  **zobrazoval název souboru** 
4. Doplnit na tabulku  Výpisu dispečerských příkazů filtr, který by měl volbu zobrazení buď ukončené, neukončené nebo všechny příkazy

**Comment by Sundin18** [comment]
Ok, jen k těm názvům souborům. Přidám k nim raději časové razítko, aby se nestalo, že by se uložil soubor se stejným názvem jako už nějaký uložený předchozí soubor, protože jinak by mohlo dojít k přepsání toho uloženého souboru.

**Comment by Sentinel65** [comment]
Ano samozřejmě

**Comment by Sentinel65** [comment]
Ještě bych tam malinko upravil ty nadpisy u těch oken, když dáš Přidat odpověď:

1.DP - Odpověď na projednání DP #xxx
2.ST - Odpověď na projednání ST #xxx
3.PZ - Odpověď na projednání PZ #xxx

**Comment by Sentinel65** [comment]
Ještě jedna a to důležitá věc, kterou musíme prověřit.
Na té 38 ještě nastav, aby role **Analyzátor, Kontrolér analýzy a Kontrolér CDP** viděli v Detailu i to pravé okno **Projednání**.
Jinak ostatní role, které mají pohled Příkazy k dispozici v Detailu uvidí jen to levé okno.

**Comment by Sundin18** [comment]
Hotovo

**Comment by Sentinel65** [comment]
Petře mrkni se na to číslování oprav, dle mého pokud udělám podruhé opravu, tzn. aktuální detail je 2. oprava a v původním vidím originál + 1. opravu, tak celkově by mělo být počítadlo Počet oprav: 2

**Comment by Sentinel65** [comment]
Jinak ještě jedna poznámka ! Dej si POZOR při překlápění, protože generování PZ do PDF na 38 máme jiné, než na ostrém !!! Tam se to nějak upravovalo a není to shodné na ostrém a testovacím.

**Comment by Sundin18** [comment]
Opraveno.
To pdf je jiné, protože teď jsem v jiné větvi než ta co je na ostrém a tuhle větev jsem vytvořil ještě dříve než došlo k té změně pdf. Až tuhle větev sloučím do té co je na ostrém, tak pdf bude stejné jako na ostrém.

**Comment by Sentinel65** [comment]
Narazil jsem na jeden malý BUG. V momentě kdy dám **"Ukončit příkaz"** a v Detailu pak kliknu na checkbox, tak to hodí v prohlížeči hlášku 404 Not Found. Provede se další oprava a zruší se Ukončení příkazu. Takže by to po tom Ukočení přáíkazu chtělo, ten checkbox v Detailu udělat Disabled

**Comment by Sentinel65** [comment]
Tak to ještě testuji a mám pocit, že v tom Detailu když kliknu na ten checkbox "Nepřiřazovat k záznamu" je bez vazby na to, jestli je to nebo není ukončené. Prostě to kdykoli hodí chybu 404 Not Found

**Comment by Sundin18** [comment]
Tak je to znepřístupněné

**Comment by Sentinel65** [comment]
Ale ta chyba je tam Petře pořád, jakmile na 38 kliknu v Detailu na "Nepřiřazovat k záznamu", tak mi to hodí toto okno viz. obrázek. To je ta chyba, o které jsem psal.

![image](https://user-images.githubusercontent.com/54531291/74320221-8a51f100-4d80-11ea-8f12-fdae4df5781e.png)

**Comment by Sundin18** [comment]
Aha, tak to jsme si nerozuměli. Je to opravené

**Comment by Sentinel65** [comment]
Tak teď už to vypadá ok, napiš changelog nezapoměň, že je už únor, takže 20.01.19 určitě ne.
Dopiš tam i to 20.01.18 a teď nevím, jestli to bylo ještě v lednu, nebo už v únoru, ale mysím že ještě v lednu

**Comment by Sentinel65** [comment]
Tak jsem ještě našel chybičku. Při zrušení příkazu, když tam píšu důvod zrušení, se tento sice napíše do DB a je pak vidět v Detailu, ale mailem se odešle  text, kde je původní text zasláno omylem, nikoliv to, co jsem tam napsal já.
Při té příležitosti ještě uprav ten text v tom okně, kam se píše důvod zrušení v záhlaví:

Místo Rušení příkazu čislo xxx tam dej **"Rušení příkazu  #xxx"**, ať to máme stejné s textem u těch odpovědí.

**Comment by Sundin18** [comment]
Opraveno

**Comment by Sentinel65** [comment]
Fajn tak na tém 38 už to je, jak má být. Můžeš to dát na ostrý.

**Comment by Sentinel65** [comment]
Dneska jsem obdržel další připomínky:

1. Příkaz, který je v seznamu příkazu **zrušený**, nesmí mít v Detailu tlačítko "Ukončit příkaz" **respektive by toto tlačítko mělo být "disabled"** jako je checkobx "Nepřiřazovat k záznamu" , z logiky věci, jestli něco zruším, nemohu to pak ukončovat. Mrkni např. na DP 272.
2. Filtr nad seznamem příkazů (Všechny příkazy, Neukončené, Ukončené) rozšířit o filtr **Platné příkazy** (tj. ty které jsou ukončené, neukončené a nezrušené !)  a **Zrušené příkazy** (tj. pouze zrušené)

**Comment by Sundin18** [comment]
Hotovo, verze 20.02.02 (na 38)

**Comment by Sentinel65** [comment]
Vypadá to v pořádku

**Comment by Sentinel65** [comment]
Petře, mrkni se na ty filtry - myslím, že v ZaMU jsi něco podobného nastavoval, aby když si v příkazech zadám např. filtr **Platné** /ale i kterýkoli jiný/ a podívám se do Detailu a pak dám zpět, aby mi tam ten filtr zůstal nastavený.

Zatím to zkus jen na lokále a dej to kdyžtak na 38.

**Comment by Sundin18** [comment]
hotovo, verze 20.02.05

**Comment by Sentinel65** [comment]
No nevím, zatím mi to funguje pouze u filtru Všechny příkazy /Ukončené, Neukončené atd./ U ostatních filtrů to nefunguje.  Netuším, co jsi nastavoval, jestli všechny nebo jen ten poslední.
Jde mi o to, aby mi aspoň jeden nastavený /třeba ten první/ filtr držel, když dám detail a pak zpět na příkazy.

**Comment by Sundin18** [comment]
Jen ten poslední

**Comment by Sentinel65** [comment]
A jde to nastavit u toho, který zvolím jako první ? Nebo teda u těch filtrů podle typu, pracoviště a ten poslední podle stavu ?

**Comment by Sundin18** [comment]
Můžu nastavit každý filtr.

**Comment by Sentinel65** [comment]
Tak to zkus, ale pozor Petře, teď jsem na 38 narazil na chybu, netuším jestli to souvisí s tou úpravou filtrů, ale když chci v Detailu otevřít přílohu Projednání, tak to jen problikne a nic, na ostrém se mi po kliknutí levým tlačítkem myši nabídne ke stažení ta příloha, na 38 ne. Tam to jde jen pravým tlačítkem na odkaz a Uložit jako.

**Comment by Sundin18** [comment]
To je tím, že na 38 nejsou uloženy soubory, proto se nezobrazují.

**Comment by Sentinel65** [comment]
Aha, tak to jo ...ok. Vyzkoušej to nastavení u každého filtru, dej to na 38 a až to otestuju, tak to dáme na ostrý.

**Comment by Sundin18** [comment]
tak je to tam

**Comment by Sentinel65** [comment]
Funguje mi filtr stav (napravo), pracoviště, ale nefunguje typ, ten se vrací na všechny ... rozuměj když to zkombinuji dohromady, ty dva zmíněný drží, typ se vrátí na všechny

**Comment by Sundin18** [comment]
jo, to je zase jiná tabulka trochu, to je u kontroléra analýzy

**Comment by Sentinel65** [comment]
ano :-)

**Comment by Sentinel65** [comment]
Jinak filtry u normální analýzy jsou ok tam to drží

**Comment by Sentinel65** [comment]
U role kontrolér CDP je to taky OK

**Comment by Sentinel65** [comment]
To je divný, však role kontrolér CDP a kontrolér analýzy mají ty filtry stejné, ale asi to máš v rozdílných tabulkách

**Comment by Sundin18** [comment]
je to stejná tabulka, ale pro analýzu už nějaký konkretní typ příkazu, pro kontroléra žádný

**Comment by Sentinel65** [comment]
U kontroléra CDP to funguje pěkně u všeho

**Comment by Sundin18** [comment]
hotovo

**Comment by Sentinel65** [comment]
Vypadá to dobře

**Comment by Sentinel65** [comment]
Tak dneska na analýze nový požadavek, celkem oprávněný. 
Ve formuláři lze přidat přílohu, která nějkým způsobem dokumentuje ten příkaz. V Detailu pak následně lze přidat přílohy ohledně projednání. No a teď se jednomu z analyzátorů stalo, že omylem do toho projednání vložil špatnou přílohu a nejde s tím nic dělat (zrušit, smazat atd.)
Bude toto nějak možné ošetřit Petře ?

**Comment by Sundin18** [comment]
Můžeme tedy udělat tlačítko na smazání odpovědi, že by pak zadal tu odpověď znovu.

**Comment by Sentinel65** [comment]
Pokud to správně chápu smažeš tím tak celou odpověd včetně přílohy ano ?
A pak by prostě napsal další "příspěvek" s vloženou přílohou. Ok pokud to takto půjde, je to řešení.

**Comment by Sundin18** [comment]
Jj, asi mi to přijde nejjednodušší.

**Comment by Sentinel65** [comment]
Dobře tak to dej na 38 a pak otestuju

**Comment by Sundin18** [comment]
hotovo, verze 20.02.06

**Comment by Sentinel65** [comment]
OK, jen doufám, že na ostrém nebudou problémy s tím, jaké jsem měl já, že jsem musel přepnout z role na jinou roli a pak se vrátit, aby se mi to tlačítko **Smazat** zobrazilo. U těch analyzátoů, pokud by se toto projevilo, by se pak musela smazat cache.

Takže v pondělí zkusíme nasadit.

**Comment by Sundin18** [comment]
Nebude protože oni mají jen jednu roli, navíc se vždycky musí znovu přihlásit do pc, když přijdou do práce. Takže se jim role vždycky znovu načte. Ty jsi roli měl pořád načtenou.

**Comment by Sentinel65** [comment]
Ještě jeden dotaz ohledně toho tlačítka Ukončit příkaz / Zrušit ukončení příkazu, toto by měl asi vidět jen Analyzátor, který by ml mít právo Ukončit příkaz resp. Zrušit ukončení příkazu, ale vidí ho a mohou ho používat jak VD, PD, tak iKontrolér analýzy i Kontrolér CDP. To asi není dobré.
Můžeš to nastavit, aby tedy bylo viditelné jen pro Analyzátora /potažmo administrátora/ ?

**Comment by Sundin18** [comment]
Je to nastavené

**Comment by Sentinel65** [comment]
Super, vyzkoušeno  Ok

**Comment by Sentinel65** [comment]
Tak dneska jsem narazil na další věc, co by asi bylo třeba nějak ošetřit. V Přerově analýza zrušila ukončený příkaz ST 390, takže je zeleně podbarvený a text přeškrtnutý viz. obrázek.
Netuším, jak se jim to podařilo, protože u ukončeného příkazu je tlačítko zrušení disabled. Stav mají Příkaz je ukončen a zároveň je zrušený.

![image](https://user-images.githubusercontent.com/54531291/75852737-ee4e5f00-5dec-11ea-91e6-0d1e932a9221.png)

**Comment by Sundin18** [comment]
No chvíli mi trvalo přijít na to jak se jim to podařilo, ale bylo to tak, že ten kdo zrušil příkaz (dispečer) měl otevřenou stránku s příkazy. Někdo druhý (analyzátor) u sebe si otevřel detail příkazu a dal "Ukončit příkaz" a následně poté dispečer (neměl aktualizovanou stránku s příkazy, tudíž neměl znepřístupněno tlačítko "Zrušit příkaz") zrušil příkaz. 
Na 38 verze 20.03.01 je tedy uděláno, aby k tomuto nemohlo dojít. Pokud v této situaci dispečer klikne na "Zrušit příkaz" objeví se mu červená notifikace s textem "Příkaz nelze zrušit, protože je ukončen."

**Comment by Sentinel65** [comment]
Koukám na to, asi bych do té chybové hlášky ještě dopsal, aby si obnovil obrazovku prohlížeče.
Ona se mu sice objeví chybová hláška, ale on vidí, že příkaz ukonřčený není.
**"Příkaz nelze zrušit, protože je ukončen. Obnov stránku prohlížeče klávesou F5."**

**Comment by Sundin18** [comment]
Obnovím tabulku i po té chybové hlášce, tím se řádek zazelená.

**Comment by Sentinel65** [comment]
ok
