### ISSUE TITLE
Příkazy - PZ tisk PDF

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#112]
Ozvali se  mi kluci, že když si dají vytisknout PZ, tak se  jim to tiskne na šířku papíru.
Zkus to předělat, aby se to tisklo na výšku papíru.

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.09)...je jen na 38

**Comment by Sentinel65** [comment]
Ok, takto by to mělo být.

**Comment by Sentinel65** [comment]
OK, ověřeno na PD3 u PZ 45, tisk je v pořádku na výšku. Možno do changelogu
