### ISSUE TITLE
ZaMU prvotní přihlášení

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#113]
Čistě náhodou jsem přišel na jednu věc a nevím zdali je žádoucí, tak do diskuze.
Když se přihlásí prvotně provozní dispečer např. z Ústí nad Labem, tak mu naběhne ZaMU kompletně bez výběru oblasti se všemi záznamy. Neměl by se rovnou zaškrtnout výběrový filtr dle oblasti?

**Comment by Sundin18** [comment]
Naběhne mu ZaMU,které měl naposledy vybrané

**Comment by zachyunl** [comment]
Neměl ZaMU vybrané žádné. Je to nový PC po formátu a prvotní přihlášení.

**Comment by Sentinel65** [comment]
No myslím, že to je postavené na cookies. U čistého profilu v prohlížeči není pro tu stránku žádné, v momentě kdy se poprvé přihlásí a zaškrtne oblast a ukončí prohlížeč, tak při dalším přihlášení má tu oblast nastavenou.

**Comment by Sundin18** [comment]
Ono by ho to mělo přihlásit do jeho oblasti,pokud neměl nikdy ještě nic nastavené nebo má smazane cookies. Podívám se na to.

**Comment by Sentinel65** [comment]
Ne, nenastaví, teď jsem to zkoušel na 210 pod uživatelem, který se tam hlásil poprvé a oblast v přihlášení má Praha, ale oblasti ve filtru vpravo nejsou zaškrnuty žádná a data mu tam svítí za všechny oblasti.

**Comment by Sundin18** [comment]
Opraveno (verze 20.01.10) - teprve nahraju

**Comment by Sundin18** [comment]
je to na obou 38 i ostrý
