### ISSUE TITLE
Milan Jakubec

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#115]
Ahoj Petře,

 

dnes jsem s kolegy projednal případné omezující podmínky pro zasílání e-mailových notifikací z aplikace Šedivák na post hlavního dispečera. Vesměs se shodují s našim včerejším závěrem.

 

Přejeme si zasílat e-mailové notifikace od záznamů závad do 4. hodiny ranní následujícího dne po ukončení závady dispečerským aparátem CDP. Tzn., že pokud dojde k ukončení závady například #42737 dne 10. 01. 2020 v 11:33, budou chodit e-mailové notifikace na změny tohoto záznamu až do 11. 01. 2020 4:00 hodin. Změny provedené po tomto čase, již posílány nebudou.  

 

Dále Tě prosím o zvětšení písma obsahu e-mailových notifikací ze současných 12 na 16. Je to malé a špatně se to čte. Moc by nám to pomohlo.

**Comment by zachyunl** [comment]
Petře v těch notifikacích to předáváš v plaintextu dále, nebo to nějak formátuješ?

**Comment by Sundin18** [comment]
Je to formátované jako html. Písmo jsem jim zvětšil.

**Comment by Sentinel65** [comment]
Netluče se to zvětšení písma s požadavkem #119  ? Petře ty dokážeš nastavit jiný druh a velikost písma pro odesílání zpráv na různé emailové adresy ?

**Comment by Sundin18** [comment]
Příkazy a ZaMU je každý jiný email,ty spolu nesouvisí.

**Comment by Sentinel65** [comment]
Ok
