### ISSUE TITLE
Pravidla pro nasazování nových verzí

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#116]
1. Nasazení nové verze aplikovat pouze 1x týdně v rozmezí pondělí - středa, zbytek dní věnovat podrobnému testování na 38, v termínu nasazení na ostrou verzi mít připravený changelog se všemi popsanými změnami v nové verzi. V případě výskytu závažné chyby po nasazení nové verze (chyba typu - nezobrazování některých důležitých dat jako to bylo u Neprojetých tras nebo teď u Příkazů zobrazení Detailu, nemožnost uložení záznamu do DB, nemožnost opravy záznamu DB apod.) provést případnou opravu verze i mimo stanovený termín pondělí - středa.

2. Nasazení nové verze aplikovat po důkladném otestování na 38 a po jasném odsouhlasení (možno nasadit na produkci) jedním z Jirků, který se účastnil testování.

3. Po nasazení sem nahrát seznam jmen souborů, ve kterých se měnil kód včetně popisu řádků, u kterých ke změnám došlo. To je z důvodu, kdy dojde po nasazení nové verze a chyba popsaná  kritická chyba se projeví později, aby jsme jeden z nás dvou byl schopen se do souboru podívat a po konzultaci s Petrem udělat v souboru opravu a ten vyzkoušet na 38, za předpokladu, že Petr bude mimo dostupnost terminálu delší dobu. 

4. Nasazení změny v DB na produkční server zachovat následujicí postup:
    - změnu dělat o víkendu (pátek, sobota) kolem 21 - 22 hod
    - změnu provést až po odsouhlasení jedním z Jirků, který se testování účastnil
    - před změnou informovat mailem všechny VD
    - zastavit provoz Apache serveru
    - udělat zálohu DB, tak aby jsme měli zajištěná aktuální data a možnost se rychle vrátit ke stavu před nasazení nové DB v případě nějaké vážné kolize, která znemožní nebo značně omezí dispečery ve své práci při evidenci 
     - podhodit novou verzi DB na produčkní server, spustit Apache server, informovat VD o znovuzprovoznění
     - v případě, že v té době bude k dispozici na PC jeden z Jirků, lze po domluvě v bodě 4 zjednodušit zálohu tím, že se provede na vSphere snapshot serveru

5. V tuto chvíli  neaplikovat žádné změny, které by vycházely z toho, že by se data, která máme k dispozici v dalších námi používaných informačních systémech, musela ručně přepisovat do našeho ŚEDIVÁKU.

Víc mě kluci nenapadá, jen Jirka by mohl vypsat ty příkazy na zastavení apache, zálohu / obnovu MYSQL, případně doplňte sami, co vás napadne.

Myslím, že ten pátek a sobota by nás měl poučit.

**Comment by zachyunl** [comment]
Já bych k tomu měl pár věcí. 
* Opravdu se nyní vykašlat na "vylepšování" Šediváku, ale soustředit se na následující. 
* Všichni 3 bychom se měli naučit pořádně z Githubem (nevím jak 😁) a jít u něj do hloubky co to vlastně všechno umí. Poctivě verzovat všechny změny a hlavně je sem nahrávat i než to půjde na 38 testovací server a nedržet to jenom lokálně u Petra. Pro obě komponenty backend ale i frontend.
* Napsat technickou dokumentaci. Vím že to bude strašný opruz, ale musíme to udělat již jenom kvůli víkendu co máme za sebou. Já zkusím najít nástroj a začnu s tím. Bude tam např. záloha a obnova DB a nějaké technické poznámky. Ale dále tam musí být celková architektura systému. Další popis jak se systém buildí. Z dokumentace musí být jasné, když k tomu přijde neznalý člověk věci, že si připraví systém a z githubu stáhne poslední verzi a vše poběží... Práce nad hlavu a nezáživná vím to.

**Comment by Sentinel65** [comment]
V zásadě souhlasím

**Comment by zachyunl** [comment]
Měl jsem schůzku s vývojářem, který prošel již velkými korporacemi a dělá hlavně týmové projekty. Téměř všude používají pro svojí práci git a na něj navázané deriváty a další produkty pro analýzu, kontrolu syntaxe, buildování atd. Pro nás na začátek co jsem si odnesl. Začít používat **commit ID** a **tagovaní** (toto bude korespondovat s naším číslováním).

**Comment by Sentinel65** [comment]
Co to znamená v praxi ?

**Comment by zachyunl** [comment]
V praxi to bude znamenat, že když se toto správně nastaví a bude to Petr striktně používat, tak uvidíme:

1. Přímo číslo verze v kódu
2. Na základě toho jsme schopni porovnat jaká úprava se dělala např. mezi verzí 10.02.10 a 10.02.11. Git to přímo zobrazí, takže uvidíš že se něco změnilo na řádku 55 souboru x a na řádku 6 souboru
y.
3. Díky tomu udržíme aktuální verzi v gitu vůči testu a můžeme být zpět o několik verzí v produkčním systému a bude nad tím hlavně přehled.

**Comment by Sentinel65** [comment]
To zní dobře.

**Comment by Sundin18** [comment]
To jde i teď.
Tag není nic jiného než popisek. Obvykle se tam píše právě číslo verze. Jinak každému commitu píšu i poznámku čeho se týkala.

**Comment by zachyunl** [comment]
No super, tak to nebude žádné extra nastavování, ale jenom abychom do toho všichni pronikly. A děláš commity skutečně pro každou verzi?

**Comment by Sundin18** [comment]
Ano.
