### ISSUE TITLE
Příkazy - generování PDF v PZ

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#117]
Požadavek na doplnění řádky (položky):

Doba zpoždění:

která teď chybí ve vygenerovaném PDF

**Comment by Sundin18** [comment]
Tohle tam je, ne?
[1_DP_PD1 UNL_PO Děčín_OŘ Ústí nad Labem_Analýza UNL#oprava.pdf](https://github.com/Sundin18/backend/files/4055430/1_DP_PD1.UNL_PO.Decin_OR.Usti.nad.Labem_Analyza.UNL.oprava.pdf)

**Comment by Sentinel65** [comment]
![image](https://user-images.githubusercontent.com/54531291/72288965-71073900-364a-11ea-8326-9a1c7f37afa5.png)

v Detailu to je, ale ne v to vygenerovaném PDF u Provozní závady

![image](https://user-images.githubusercontent.com/54531291/72289192-dce9a180-364a-11ea-9171-4631e1b08229.png)

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.12

**Comment by Sentinel65** [comment]
Ahoj Petře,
v tom vygenerovaném PDF u té Provozní závad  ten řádek **Zpoždění** přesuň pod řádek **Vlak** stejně, jako je to seřazené pod sebe u Detailu.

**Comment by Sundin18** [comment]
hotovo

**Comment by Sentinel65** [comment]
Jo teď už to vypadá ok

**Comment by Sentinel65** [comment]
Tak ještě to NENÍ OK.
PZ 114, dal jsem tam schválně delší text do Popisu závady a přepisuje se to přes sebe v tom PDF.
To samé jsem udělal v DP číslo 115 a tam mi to v mailu v PDF zobrazuje OK.

[Provozní závada číslo_ 114 - DS4A,DS3A.pdf](https://github.com/Sundin18/backend/files/4082909/Provozni.zavada.cislo_.114.-.DS4A.DS3A.pdf)

[115_DP_Analýza PHA_OŘ Praha_PO Beroun_Analýza PHA.pdf](https://github.com/Sundin18/backend/files/4082911/115_DP_Analyza.PHA_OR.Praha_PO.Beroun_Analyza.PHA.pdf)


V textu v těle mailu i v tom vygenerovaném PDF u Provozní závady: text **Vyjádřeník provozní závadě** oddělit to písmeno **k**

![image](https://user-images.githubusercontent.com/54531291/72684471-f2dee280-3ae0-11ea-8c23-43ef88de6d2d.png)

**Comment by Sundin18** [comment]
Opraveno

**Comment by Sentinel65** [comment]
OK

**Comment by Sentinel65** [comment]
Tak ještě jeden problém u těch PZ. Chtělo by to, aby se v mailu připojené PDF generovalo stejně, jako to které se generuje u těch PZ ručně kliknutím na ikonku. To je teď optimalizované pro tisk. V tom mailu to přiložené má ten text po sebou viz. přílohy.

[Provozní závada číslo_ 118 - DS4A,DS3A_generovano_tlacitkem.pdf](https://github.com/Sundin18/backend/files/4088077/Provozni.zavada.cislo_.118.-.DS4A.DS3A_generovano_tlacitkem.pdf)


[118_PZ_Analýza PHA_DS4A_DS3A_prilohu_v_mailu.pdf](https://github.com/Sundin18/backend/files/4088078/118_PZ_Analyza.PHA_DS4A_DS3A_prilohu_v_mailu.pdf)

**Comment by Sundin18** [comment]
Upraveno, verze 20.01.13
