### ISSUE TITLE
ZaMU - přidělení příkazu

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#118]
V ZaMU nejde odřadit přiřazaný příkaz, ve chvíli, kdy musíme záznam s přiřazeným příkazem zrušit, nelze tento příkaz přiřadit jinému záznamu v ZaMU.

**Comment by Sundin18** [comment]
Jj, o tom vím. To nešlo nikdy. Než se k tomu dostanu,  tak jestli je teď potřeba to u nějakého udělat, tak to udělám zatím v databázi.

**Comment by Sentinel65** [comment]
Ne ne jsi na dovolené, tohle počká až se vrátíš. Pokud bylo nutné odřadit již přiřazený příkaz, tak se ti ozvem a jenom to odřadíš. Jako jsme to udělali dneska.

**Comment by Sentinel65** [comment]
Než ztratím myšlenku, napadlo mě toto, pokud to bude realizovatelné. V Příkazech v Detailu by se objevila další položka s checkboxem nazvaná třeba **Přiděleno**. Pokud by byl příkaz přidělený v ZaMU, checkbox by byl zaškrtnutý. Pokud by se odškrtnul, v DB by se smazal u daného záznamu ZaMU příznak přidělení (číslo příkazu) a příkaz by se objevil v Nepřidělených příkazech.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.14

**Comment by Sentinel65** [comment]
SUPER, funkční

**Comment by Sentinel65** [comment]
Šlo by ještě udělat v tom formuláři vlevo dole checkbox pro Nepřiřazení k ZaMU tak, aby to ale viděl pouze analyzátor a pokud vydává nějaký příkaz, kde už předem ví, že ho nechce přiřazovat, že bo to rovnou mohl zaškrtnout.

**Comment by Sundin18** [comment]
Ok, tak já to nasadím i na ostrý, aby nemuseli dispečeři kvůli tomu volat, kdyby se jim to podařilo špatně přiřadit (jak naschvál se jim to stalo, když jsem byl na dovolené, od té doby klid :-) ).

Ano s tím počítám, je to součástí #111.

**Comment by Sentinel65** [comment]
Dobře souhlas
