### ISSUE TITLE
Příkazy - formátování textu zprávy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#119]
Dnes se ozvali z Přeřova s požadavkem na formátování textu v Příkazech. Jde o to, že oni konkrétně ty ST překopírovávají do oficálního dokumentu s číslem jednacím a jde do pak přes Spisovou službu, takže by rádi, aby ten text měl parametry oficiílního dokumentu na SŽDC, tj nějakou velikost textu, druh písma atd.

> Dobrý den, pane Horký,

> Bylo by možné DP a žádosti o stanovisko, které jsou výstupem   z  Šediváku ( **zpráva co chodí do pošty Analýzy CDP**), uzpůsobit tak, aby **použité písmo bylo VERDANA**, **velikost 9**, bez tučného zvýraznění.
>Tento výstup kopírujeme do administrativního dopisu  pro dopravce, který má mít podle šablony výše uvedené nastavení.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.12

**Comment by Sentinel65** [comment]
No tady jsem si vyzkoušel zkopírovat text z toho těla příkazu a tam se mi zobrazuje font Ariel a velikost 12  ??

**Comment by Sundin18** [comment]
A do čeho to vlastně kopírují?

**Comment by Sentinel65** [comment]
Oni to zkopírují do dokumentu word, který má číslo jednací, následně pak zkonvertují do PDF a chodí to skrze Spisovou službu jako oficiální dokument.

**Comment by zachyunl** [comment]
> No tady jsem si vyzkoušel zkopírovat text z toho těla příkazu a tam se mi zobrazuje font Ariel a velikost 12 ??

Já to zkouším a Petr tam má Verdanu. Můžeš Jirko ukázat screen, kde je Ariel?

**Comment by Sentinel65** [comment]
Když si ten tewxt zkopíruju v Gmailu a vložím do prázdného Wordu kde mám před vložením Calibri 11 a po vložení textu mi to ukáže Ariel 12.
Je možné, že v Outlooku to bude jinak, nevím.
