### ISSUE TITLE
Prohození info o verzi a o přihlášeném uživateli

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#12]

**Comment by zachyunl** [comment]
Super, nechci prudit, zase je to jen kosmeticka uprava Petre, ale prohod prosim te v tom sedem pruhu strany s popisem verze a prihlaseni. Opet je to jen o designu, ale pokud mas prihlasovaci odkaz vpravo nahore a info o prihlasenem uzivateli je pak uplne vlevo, prijde mi to nelogicke. Takze info o verzi soupnout vlevo a info o prihlasenem uzivateli vpravo. Jinak je to OK!

**Comment by Sundin18** [comment]
Přehozeno, verze 19.08.1

**Comment by Sentinel65** [comment]
A máš to podhozené i z localu  ? Já to tam vidím pořád stejně, jak to bylo :-D

**Comment by Sundin18** [comment]
už je to nahrané ;-)

**Comment by Sentinel65** [comment]
ok
