### ISSUE TITLE
Příkazy - checkbox Nepřiřazovat k záznamu

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#120]
V souvislosti s #118 , kam jsem dopisoval myšlenku, jsem si všiml, že v Detailu v příkazech není ten checkbox **Nepřiřazovat k záznamu**. Našel jsem ho jen v Příkazu DP 31, ani v ST nebo PZ nevidím, tohle budeme muset doladit.
Jinak i z toho důvodu by navrhoval, aby se v seznamu příkazu označil příkaz, který nebude přiřazen v ZaMU odlišnou barvou textu, aby to bylo na první pohled zřejmé a nemuseli jsme ho hledat.

**Comment by Sundin18** [comment]
A není to tím, že jsou ty příkazy přidělené k ZaMU? Pokud jsou přidělené, tak se checkbox nezobrazuje, jak byli dohodnuto.

**Comment by Sentinel65** [comment]
OK, je to možné
