### ISSUE TITLE
ZaMU - po přihlášení prázdná obrazovka

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#121]
Včera to byly dva případy, dneska zatím jeden. Jen pro informaci, aby jste věděli, jak reagovat.
Jde o stav, kdy se uživatel přihlásí a vidí prázdnou obrazovku ZaMU. Dalším identifikátorem je pak, že když si vpravo začně přepínat checkboxy v Oblast, tak se mu buď všechny vypnou a nebo naopak všechny zapnou najednou.
Je možné, že to nějak souvisí i s tím karambolem DB, restartem služby mysql minulý pátek.
V Administraci znovu uživateli nastavím Oblast a Roli tak, jak to má mít a uložím. Uživateli řeknu, aby v prohlížeči vymazal cache a prohlížeč se všemi okny ukončil. Po znovu spuštění to již běhá, jak má.

**Comment by Sundin18** [comment]
To nemá s DB nic společného. Jednou se mi to stalo na 38, po té změně nastavení, aby se zobrazila jen oblast uživatele, odkud je pokud to předtím již neměl nastaveno nebo smazal cookies. To musím prozkoumat proč se to občas stane.

**Comment by Sentinel65** [comment]
Dneska další oznámení u PD5 na vituálu, to samé.

**Comment by Sentinel65** [comment]
Tak dneska další 3 oznámení, 2x u přípraváře v Přerově (tam to bylo během hodiny a půl 2x), 1x z O18 z Ostravy.
Znovu jsem tedy jednotlivé uživatele přeeditoval v Administraci (Oblast a Roli) a po telefonu navigoval k vymazání cache prohlížeče.
Napadá mě, jestli toto nějak nesouvisí se spuštěním toho automatického refresh stránky.
Až se vrátíš, tak to budeme muset prozkoumat.

**Comment by Sentinel65** [comment]
Takže když se mu znovu přenastaví položky Oblast a Role, tak by se to nemělo opakovat ?

**Comment by Sundin18** [comment]
To si  nejsem jist. Až přijedu tak se na to podívám.

**Comment by zachyunl** [comment]
Další poznatek, teď jsem řešil 3 pracoviště v Praze, kde byla prázdná ZaMU. Do DB se nemusí vůbec chodit. Stačí smáznout cookies, 24hod mi nepomohlo. Když jsem smáznul cookies za 7 dnů a poté refresh prohlížeče, tak se data objeví. To vypadá, že server posílá něco blbě do cookies a pak s tím má prohlížeč problém a nic nezobrazí.

**Comment by Sundin18** [comment]
Jak jsem psal, způsobuje to přihlášení do oblasti, kterou má uživatel nastavenou a má mu to automaticky vybrat jeho oblast. Zkrátka to zatím vrátím do stavu, jak to bylo než zjistím, jak to udělat jinak. Lepší bude, když se uživateli data zobrazí a bude si muset vybrat oblast, pokud ji už nebude mít vybranou z dřívějška nebo bude mít smazane cookies, než když  se mu data nezobrazí.

**Comment by zachyunl** [comment]
Docela drsný je, že to bylo na jednom pracovišti již podruhé během 2 hodin u stejného člověka.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.12 (odebral jsem tu změnu, která to nejspíše způsobovala)

**Comment by Sentinel65** [comment]
Tak vzýhledem k tomu, že toto asi těžko na testovacím serveru nějak otestujeme, tak bych se přikláněl k tomu to nasadit s dalšími opravenými věcmi.
