### ISSUE TITLE
Generování ST a emailová adresa

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#122]
V Ústí potřebují holky nastavit, aby se v generovaném textu objevila ústecká analýza.

![image](https://user-images.githubusercontent.com/47257941/72345541-5083c100-36d4-11ea-8db6-978a4f43d40c.png)

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.12

**Comment by Sentinel65** [comment]
Možno nasadit
