### ISSUE TITLE
Neprojeté trasy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#123]
- doplnit vazbu při přidělení čísla v ZaMU, aby se čísla Neprojetých tras zobrazila v ZaMU ve Vlivech
- doplnit sloupec Dopravce ?

**Comment by Sundin18** [comment]
první bod hotov (verze 20.01.12)

**Comment by Sentinel65** [comment]
No po pravdě u toho druhého nevím Petře a Jirko, na té schůzce jak jsem byl, by se tam tento sloupec hodil, protože čas od času dělají různé sestavy a toto byla jedna ze zmíněných Neprojeté trasy dle dopravce za určité časové období. Co by to obnášelo tam ten sloupec doplnit pro ty stávajicí záznamy ?

A když už jsem u toho, tak bych Petře prosil ještě doplnit do Filtrovat dle datumu položku **Kalendářní rok**

**Comment by Sundin18** [comment]
Naprogramovat to lze, odhad 1 den. Nejvíce práce by pak asi zabralo doplnění dopravce již k vytvořeným záznamům (obdobné jako když Jirka @zachyunl doplňoval "department" u uživatelů)

**Comment by Sentinel65** [comment]
Ta vazba v Neprojetých trasách na číslo ZaMU teď na 38 funguje. Takže bychom to udělali asi po částech, toto podhodit a ten sloupec Dopravce tam potom doplnit v dalším týdnu,.až by se nasazovala  nová verze (Pondělí-Středa).

**Comment by Sentinel65** [comment]
Tak jsem byl teď u provozních dispečerů a upozornili mne na jeden BUG docela podstatný, zajímávý ale že se nikdo sám od sebe neozve.

V Neprojetých trasách **vytvoří záznam** a **uloží ho** viz. obrázek. Pak dá tlačítko **Přidat záznam** a otevře se mu okno pro vyplnění záznamu a **tam je vyplněný komplet ten předchozí záznam** viz obrázek, který uložil před chvilkou.

![image](https://user-images.githubusercontent.com/54531291/72726962-fd08eb80-3b89-11ea-9a40-3d4057a5f75e.png)

**Comment by Sundin18** [comment]
To ani tak není bug sám o sobě. Jen jsem nevymazaval proměnné,  kdyby chtěli žádat stejně údaje třeba jen pro jiné číslo vlaku. Ok, udělám změnu, aby se jim to vždy vymazalo.

**Comment by Sentinel65** [comment]
Raději ať to vyplní z prázdného formuláře.

**Comment by Sundin18** [comment]
Upraveno, verze 20.01.12

**Comment by Sentinel65** [comment]
Na 38 je to v pořádku. Ten první bod je možno nasadit, ty sloupce mají nižší prioritu a počkají.

**Comment by Sundin18** [comment]
Doplněn bod 2 (dopravci). Verze 20.1.15
Dopravce je tam pro všechny trasy vyplněn jako ČD pro snadné doplnění. Na ostrý server se samozřejmě bude muset pro každý záznam dopravce zjistit.

**Comment by Sentinel65** [comment]
OK, nech to na pondělí
