### ISSUE TITLE
ZaMU - formátování textu a tisk PDF

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#124]
Na dnešní schůzce u analyzátorů - oddělení Radka Bejšáka - jsme probírali i problém formátování textu a jeho následné zobrazení při tisku do PDF. On to byl už problém celých 8 let za éry starého Šediváku. Při dlouhém textu jsem VD instruoval, aby mezi jednotlivými větami / výpisem vlaků v Popisu a ve Vlivech dělali mezeru, aby se text dokázal automaticky zalamovat.
V tomto případě - záznam #43097 se ten text v tom PDF nějak divně popasoval s tou oddělujicí čarou mezi jednotlivými záznamy. Přijde mi to, že to tam Petr má nějak natvrdo nastavené.

[MU_1579088922795.pdf](https://github.com/Sundin18/backend/files/4064740/MU_1579088922795.pdf)

V tom vygenerovaném PDF bude potřeba, aby se také tisklo číslo záznamu vpravo nahoře, které tam teď nevidím. Dále počítat s tím, aby se až se propojí Neprojeté trasy se záznamem v ZaMU a ve Vlivech se tak vypíše seznam Neprojetých tras, aby se to v tom PDF zformátovalo pod tím textem s vlivy (tj. zpožděné vlaky).

Název odstavce Neprojeté trasy by měl být tučně a text jednotlivých Neprojetých tras v řádcích po sebou. Toto, pokud si dobře pamatuji, jak jsme s Petrem zkoušeli na 38, tam bylo, že ty trasy byly pod sebou v řádcích. Ten odstavec Neprojeté trasy aby byl navíc od toho textu s vlivy "odřádkován", tzn. aby to nebylo hned nalepeno pod sebou, ale ty dva "odstavce" aby byly při tom tisku oddělené.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.12

**Comment by Sentinel65** [comment]
Tak toto jsem odzkoušel, v tom PDF to vypadá dobře, akorát ty Neprojeté trasy, které jsou přiřazené k ZaMU se zobrazí v PDF, ale v těch Vlivech je tam nevidím, jsi asi zapomněl doplnit viz 43739 na 38

**Comment by Sundin18** [comment]
Tam ještě nejsou, to je závislé i na posílání mailů ÚD, tak to chci dát pak všechno dohromady, aby to nefungovalo jen napůl. V PDF to nevadí, že už to tam je.

**Comment by Sentinel65** [comment]
Tak moment, jak je teď na té 38 nastavena pošta ?? Domluv se s Jirkou a nastavte příkazy i ty ZaMU, aby se z 38 posílaly na můj soukromý a služební mail, případně pro kontrolu i na vaše. Ale to musíme vyzkoušet i v mailech / v těle zprávy i v tom PDF, pokud se tam generuje /. Jak ZaMU, tak příkazy. Nemůžeme čekat, až to dáme na ostrý, co přijde ústřednímu. Od toho testujeme.

**Comment by Sentinel65** [comment]
A koukám v mailu mám 43739 před chvíli poslanou, naštěstí je to z ostrého, stejné číslo, ale jiný text, Už na té 38 raději dávám text TEST. Takže bude třeba na té 38, by mi to z toho ZaMU taky chodilo na mail. A koukám, tam je to čistě jen text v těle zprávy, žádné připojené soubory. Takže bychom pak otestovali, jestli se po zpárování Neprojeté trasy - ZaMU zobrazí ve Vlivech ten text s Neprojetými a zrovna tak pak v tom těle té mailové zprávy.

**Comment by Sundin18** [comment]
Tam jsem nic neměnil. Každopádně je to teď nastavené, aby že ti budou chodit maily.

**Comment by Sundin18** [comment]
Neprojeté trasy se tam zobrazují, to chodí i na ostrým

**Comment by Sentinel65** [comment]
Ze ZaMU mi z 38 asi nic nechodí Peťo. Nic jsem nedostal, pouze příkazy

**Comment by Sentinel65** [comment]
> Neprojeté trasy se tam zobrazují, to chodí i na ostrým

Na 38 ? Je tam nevidím, koukni na 38 záznam 43739 Oblast Praha Role VD

**Comment by Sundin18** [comment]
Ve vlivech v ZaMU to není. To tam doplním, až budu mít hotové to posílání emailů. Je to zatím jen v PDF a v mailu.

**Comment by Sentinel65** [comment]
Mail mi ze ZaMU z 38 nechodí, tak nemohu posoudit, v PDF ok, počkáme.

**Comment by Sundin18** [comment]
Tak je možné, že je tam vypnutý. To bude vědět Jirka. Ale tam jsem stejně nic nedělal.

**Comment by Sentinel65** [comment]
jj to je možné, však říkam, počkáme až se nastaví to posílání z 38 a pořádně to otestujeme včetně mailů

**Comment by zachyunl** [comment]
Emaily z terminálu chodí, tabulky jsou taky ok. To bude někde něco v programu.

**Comment by Sentinel65** [comment]
Testovací mail mi přišel, ale ze ZaMU mi maily nechodily.

**Comment by zachyunl** [comment]
což je samo o sobě divný, to je již úroveň tabulek v DB nebo přímo programu, když část chodí.

**Comment by Sundin18** [comment]
Tak je možné, že tam mám něco špatně nastavené. Se pak na to podívám.
