### ISSUE TITLE
Příkazy - karta Detail

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#125]
Namátkovou kontrolou jsem zjistil, že ani analýza (v Praze) nekontroluje, co tam VD z příkazu přepisuje do záznamu ZaMU.

Konkrétně mám na mysli vlivy zpoždění v záznamu ZaMU tzn. zpoždění vlaku plus případně ovlivněný vlak včetně zpoždění. V tom Detailu máme tu řádku **Zpoždění** chybně pod řádkem **Ovlivněn vlak**.

![image](https://user-images.githubusercontent.com/54531291/72520043-e183a500-3858-11ea-97aa-f2fe26d0e954.png)

Takže navrhuji řádek **Zpoždění** přesunout  pod řádek **Vlak** a do řádku **Ovlivněn vlak** doplnit text takto: **Ovlivněn vlak + zpoždění**

Stejnou úpravu pochopitelně provést v generovaných emailových zprávách včetně generovaných PDF.

**Comment by Sundin18** [comment]
Já mám dojem, že jsem nedávno už nějaký řádek přehazoval a možná zrovna tenhle.
Hotovo, verze 20.01.12

**Comment by Sentinel65** [comment]
Při větším množství textu v Popisu závady (Poznámky) to v tom Detailu dělá paseku s tím textem u popisu položek, že se zalamuje až do tří řádků. Tady kluci nevím, ale chbí nám tu nějaká dynamika toho okna Detail, jednak aby se s ním dalo pohybovat - protože při menší obrazovce třeba na NTB, nelze přečíst veškerý text toho okna Detail, nelze nijak rolovat, okno zvětšit resp rozšířit - při tom by se ten text asi i srovnal.

![image](https://user-images.githubusercontent.com/54531291/72684558-e0b17400-3ae1-11ea-8f2c-0d949689f1e2.png)

**Comment by Sundin18** [comment]
Tak mohu udělat větší okno + aby se dalo rolovat. Bude to stejné okno jako např. okno detailu ZaMU v Neprojetých trasách.

**Comment by zachyunl** [comment]
Péťo a umíš udělat, že by šlo s oknem pohybovat uchopením myši za vršek? Jestli to umožňuje technologie, kterou používáš?

**Comment by Sundin18** [comment]
To bohužel ne.

**Comment by Sundin18** [comment]
Upraveno.

**Comment by Sentinel65** [comment]
Tak to rolování na 38 funguje, ještě kdyby jsi upravil ten levý sloupec s těmi popisy, aby ten popis **Ovlivněn vlak + zpoždění byl v jedné řádce**

**Comment by Sundin18** [comment]
hotovo

**Comment by Sentinel65** [comment]
Super - toto už je lepší, při změnšení okna lze rolovat. OK

**Comment by Sentinel65** [comment]
Možno nasadit
