### ISSUE TITLE
Analýza - Přerov

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#126]
Mám tady oznámení přímo od analýzy Přerov ohledně dvou stavů, které se jeví jako BUG, je třeba to prověřit.

1. V ZaMU editoval analyzátor záznam, nastavil stav Šetření ukončeno, do položky Vlivy: napsal číslicí 0 a řekl mi, že v mailu, který došel na adresáta, kterého zaškrtl /patrně pro kontrolu i sebe/, byla položka Vlivy prázdná, ale měla by tam být ta číslice 0. Jedná se o záznam 40902.
2. Pokud jsem správně pochopil jeho povídání, tak opět v záznamu ZaMU dal Ukočit šetření, žádný soubor jako přílohu nepřipojoval a přesto du do mailu dorazila příloha se souborem, který připojoval v předchozím editovaném záznamu 40904. To teda netuším, jakým způsobem to dokázal. Jde opět o ten záznam 40902. 
3. Vyzkoušel  jsem si na 38 dát do Vlivu tu číslici 0 (záznam 43502) spolu s ukončemín šetření a zaškrtnutí na můj mail, ale mail mi nepřišel, tak nevím, co tam je.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.13

**Comment by Sentinel65** [comment]
OK
