### ISSUE TITLE
Administrace - role

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#13]
Tak jsem se konecne prihlasil pod svym uctem, v administraci si nastavil role vcetne analyzatora, pak jsem se prihlasil, zvolil oblast Praha a ukoncil tam jeden zaznam vcetne priznaku "**Setreni ukonceno"** a vsiml jsem si, ze i kdyz mam tu roli analyzatora, tak nemam jako analyzator zpristupnene to tlacitko "**Zmenit zaznam**". Je to chyba nebo umysl ??

**Comment by Sundin18** [comment]
Ano to je úmysl. Vychází to z toho, jak to používají u nás teď. Že jakmile analýza dá ukončeno šetření, tak nemůže pak už vedoucí dispečer záznam měnit. Jedině, když analýza zase "uvolní" ukončeno šetření. Tím, že máme nadefinované role jak analyzátora, tak vedoucího dispečera, tak nás to jako vedoucího dispečera už nepustí. Tohle jsem nijak nezamýšlel, protože nepředpokládám, že bude vedoucí dispečer zároveň analyzátor. Ale pokud bude potřeba si s tím nějak pohrát, tak se to dodělá.

**Comment by Sentinel65** [comment]
Ok, rozumím
