### ISSUE TITLE
ZaMU nová role pouze na prohlížení

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#130]
Petře jak bude časově náročné připravit novou roli pouze na prohlížení ZaMU?

**Comment by Sundin18** [comment]
30 - 60 minut

**Comment by zachyunl** [comment]
Až budeš v práci, tak to prosím připrav. Doma to nedělej, je to zbytečné. Ukazuje se že to budeme potřebovat a je zbytečné některým lidem pouštět další údaje.

**Comment by Sundin18** [comment]
A co přesně tato role má vidět. Pouze ZaMU bez možnosti zobrazit opravy a příkazy?

**Comment by zachyunl** [comment]
Opravy nevadí když uvidí, příkazy myslíš asi to co je propojené? Petře ty to máš modulárně?

**Comment by Sundin18** [comment]
Ano, jestli si může rozklepnout detail prikazu. Je to na základě rolí, co mohu vidět nebo dělat.

**Comment by zachyunl** [comment]
Nevím jestli se Jirkovi ještě neozval někdo s požadovanou rolí? Já si myslím že pro případy, které zatím potřebujeme, tak může být vidět i DP a změny, které jsou vázané na ZaMU. Není to nic proti ničemu.

**Comment by Sentinel65** [comment]
Spíše bych se přikláněl k tomu, co psal Petr. Udělat roli, která bude pouze na koukání a očesat to co nejvíce tzn. bez možnosti prohlížet Detail příkazů a bez oprav. Pouze ZaMU.

**Comment by zachyunl** [comment]
Oki tak to očesáme a bude to stejné jako původní šedivák pouze s prohlížením.

**Comment by Sundin18** [comment]
A jak tu roli nazvat? Anglicky mě napadá Reader, ale počeštěně to zní divně :)

**Comment by Sentinel65** [comment]
Čtenář

**Comment by Sundin18** [comment]
No, to zní trochu divně, ale možná se mi to jen zdá :)

**Comment by zachyunl** [comment]
Spíše bych to dal "Mimořádnosti čtenář" nebo něco takového. Nikdy nevíme zda nebude v budoucnu potřeba ještě třeba jenom pro čtení - příkazy, neprojeté trasy apod.

**Comment by Sentinel65** [comment]
to je hrozně dlouhé

**Comment by Sentinel65** [comment]
Když už něco krátkého výstižného i když to není česky co takhle role Basic :-)

**Comment by zachyunl** [comment]
Jirko to ne, lidi by z toho byli tumpachový. Co třeba jednoduše ZaMU? Nebo Mimořádnosti? Bez ničeho dalšího. Je to krátké a výstižné.

**Comment by Sentinel65** [comment]
samotné Mimořádnosti bude ok

**Comment by Sentinel65** [comment]
Jinak se mi dneska ozvali z Budějovic, že by chtěli přidat Dozorčí provozu. Svým způsobem je chápu, oni mají k tomu provozu nejblíže a komunikují dost s VD. Takže jsem jim řekl, ať si dají oficiální žádost.
Tady by se ta role jen pro ZaMU hodila.

**Comment by zachyunl** [comment]
No a už to tady máme, stejně jednou někdo povolí provozní funkce, podle mě to je jenom otázka času. Nebude žádoucí udělat do té role i zobrazení změn, když už to máme hotové? Přeci jenom si dokážu představit, že to hodně lidem usnadní život. DP bych tam necpal, ty skutečně nepotřebují.

**Comment by Sentinel65** [comment]
Asi jo, ty změny se můžouu hodit.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.14

**Comment by Sentinel65** [comment]
Petře přejmenuj tu roli "Běžný uživatel" na "**Uživatel ZaMU**"

**Comment by Sundin18** [comment]
přejmenováno
