### ISSUE TITLE
Příkazy - DP + ST

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#131]
V souvislosti se změnou názvu organizace je třeba změnit u DP a ST:

text v těle mailu + text generovaný do přílohy PDF takto - 

**z** Stanovisko k narušení GVD zašlete na **SŽDC**, státní organizace,
**na** Stanovisko k narušení GVD zašlete na **Správu železnic**, státní organizace,

**Comment by Sundin18** [comment]
Hotovo, verze 21.01.14

**Comment by Sentinel65** [comment]
OK, nech to na pondělí.

**Comment by Sentinel65** [comment]
Petře, upozornil nás Honza Frajer na chybu, která je v těle mailů (včetně přílohy PDF). Teď se do stanic posílá text, aby odpověděli na analýzu do Prahy i do Ustí, Ale je třeba to nastavit tak, aby se v tom textu zobrazila analýza za tu poblast, která to posílá.
Tzn. pokud je příkaz poslán z Ústí, musí v tom textu být analýza Ústí, pokud je poslán z Prahy, musí tam být v textu odkaz na analýzu Praha. Tak jak to je dole, je to chyba.

Dispečerský příkaz číslo: 138 pro OŘ Praha, PO Kolín, Analýza PHA, vydán dne: 22.01.2020
Vlak číslo: 944 byl zpožděn dne 22.01.2020
Místo zpoždění: Český Brod - Úvaly
Doba zpoždění: 5 min
Čas události: 16:28 hod.
Důvod zpoždění: Chybný sled vlaků R 944 a R 866.
Ovlivněn vlak: R 886 + 3 min
Stanovisko k narušení GVD zašlete na SŽDC, státní organizace, Centrální dispečerské pracoviště Praha, AJŘ (CDPPHAanalyza@szdc.cz
**a CDPUNLanalyza@szdc.cz)** a pracoviště Analýza GŘ (O11analyza@szdc.cz).
Dispečerský příkaz sepsal vedoucí (provozní) dispečer: Martin Ubrý (PD3 PHA)
Odesláno z pracoviště: cdp0000phant023.red.szdc.cz v 17:51:32

**Comment by Sundin18** [comment]
hotovo

**Comment by Sentinel65** [comment]
Petře, to je úplně špatně. Přepnul jsem se na na 38 na PD Ústí, napsal DP a přišlo mi - odešlete na analýza Přerov

![image](https://user-images.githubusercontent.com/54531291/73132252-ed215980-4018-11ea-8bda-e85ed3c3776b.png)

U pracoviště Praha je to OK

![image](https://user-images.githubusercontent.com/54531291/73132329-0545a880-401a-11ea-8502-d9b2d13de455.png)

 Pracoviště Přerov je taky špatně, tam je zase odkaz na analýza Praha

![image](https://user-images.githubusercontent.com/54531291/73132404-dda31000-401a-11ea-91ca-a7049bdd0320.png)

**Comment by Sundin18** [comment]
Tak už by to mělo být v pořádku

**Comment by Sentinel65** [comment]
Není, v Ústí oprava DP121 a je tam stále Přerov 

![image](https://user-images.githubusercontent.com/54531291/73139475-9ba3b980-406e-11ea-9b3b-bb7970d81017.png)

V Přerově oprava DP124 a je tam Praha

![image](https://user-images.githubusercontent.com/54531291/73139516-12d94d80-406f-11ea-9c06-120f2c041647.png)

**Comment by Sundin18** [comment]
Tak teď, já měl zaměněnou oblast Ústí s Přerovem. Jinak tedy nasadím novou verzi na ostrý.

**Comment by Sentinel65** [comment]
Ne ne nic nenasazuj, napsali jsme si, že nasazovat nové verze budeme pondělí až středa

**Comment by Sundin18** [comment]
Však jo, to už bude prakticky pondělí. Budu muset projít všechny záznamy neprojetých tras a nastavit tam dopravce.

**Comment by Sentinel65** [comment]
ZATÍM NIC NENASAZUJ

Je to pořád blbě tady Ústí (je tam Praha, má tam být Ústí) 

![image](https://user-images.githubusercontent.com/54531291/73140769-e0365180-407c-11ea-8b59-e0442a7b7674.png)

**Comment by Sundin18** [comment]
To je přeci dobře ne? CDPUNLanalyza@szdc.cz

**Comment by Sentinel65** [comment]
Jo tak se omlouvám, už je tam správně adresa analyzy Usti, ano

**Comment by Sentinel65** [comment]
Napiš mi prosím, co všechno za opravy chceš nasazovat, abych to mohl sepsat do mailu

**Comment by Sundin18** [comment]
jsou to issue #131 , #130 , #123

**Comment by Sentinel65** [comment]
doplněno do changelogu
