### ISSUE TITLE
Vyjádření k provozní závadě - úprava v generovaném pdf

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#132]
Ahoj jeden požadavek od vedení CDP.

Text "Vyjádření k provozní závadě" přesunout na další stranu nebo list.

Přeuspořádat spodní řádky na první straně následovně a posunout to více nahoru:
Za DŘP (OŘP) *dvojtečku vyhodit*
Sepsal:
Funkce:
Výsledek šetření:

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.16) jen na testovacím serveru

**Comment by zachyunl** [comment]
Takto je to ok.

Raději nechtějte vědět co dalšího vymýšlí, to jsem řekl, že se nad tím musíme zamyslet. Prý jestli by nešlo jak je tam ta položka výsledek šetření, že by to bylo rovnou přístupné v šediváku a psali to do této položky. Přemek sám řekl, že už si začínají vymýšlet krávoviny (Baško, Frajer), takže to necháme zatím být. Třeba někdy časem.
