### ISSUE TITLE
Okno zápisu - úprava při rozdělané práci

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#133]
Požadavek od dispečerů, zda nelze udělat to, aby zůstalo rozepsané okno, které je editované i při kliknutí mimo něj? Dnes pokud si kliknu při rozepsaném zápise mimo toto okno, tak veškerá rozdělaná práce zmizí.

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.16) - jen na testovacím serveru

**Comment by Sentinel65** [comment]
Petře na 38 mám pořád verzi 20.01.15 a to jsem zkoušel refresh, shodit a nahodit prohlížeč a pořád je tam 15.
A když kliknu v ZaMU na Změnit záznam, něco naoíšu do Popis nebo Vlivů tak mi stejně nejde nikam kliknout, to okno je tam v popředí natvrdo. Nedostanu se na okno se záznamy v ZaMU

**Comment by Sundin18** [comment]
Já nepřepsal to číslo. Tak to když tak nahraju znovu. 
To je právě to co chtějí, aspoň jsem to tak pochopil. Že, když mají otevřené a rozepsané okno se záznamem (nový nebo změnu), tak nechtějí, aby když kliknou mimo to okno, se to okno zavřelo, tak jak to bylo doposud. V podstatě to fungovalo stejně jako tlačítko "Storno".

**Comment by zachyunl** [comment]
Petře za mě to je ok.

**Comment by Sentinel65** [comment]
ok
