### ISSUE TITLE
Přepínaní pohledů

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#134]
Ahoj Petře, mrkni se prosím tě na ostrém na přepínání pohledů mezi ZaMU a Neprojeté trasy. Naběhnutí dat v pohledu Neprojeté trasy trvá cca 4 vteřiny, což se mi zdá celkem dost vzhledem k tomu, že tam těch dat není tolik.
Při zpětném pořadí je náběh (Neprojeté trasy - ZaMU) cca 2 vteřiny.

Stejné odezvy jsou i na 38.

**Comment by Sundin18** [comment]
No ono jich tam právě až nečekaně dost, hlavně tedy po Prahou. Takže to budu muset vyřešit jako u ZaMU strankovanim.

**Comment by Sentinel65** [comment]
Aha, chápu, tam se to načítám komplet vše najednou. OK vymysli nějaké vhodné stránkování. Je fakt, že při nějakých závažných MU se tam těch záznamů napíše dost.

**Comment by Sundin18** [comment]
Tak na 38 je to nahrané (verze 20.01.17)

**Comment by Sentinel65** [comment]
Ok, možno nasadit v pondělí
