### ISSUE TITLE
Operativní příkaz

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#135]
Máme tu nový požadavek přímo od ředitele - zpřístupnit pro roli "**Ústřední dispečer**" funkcionalitu "**Přidat záznam**" a možnost editace / opravy záznamů v pohledu "**Operativní příkaz**"

**Comment by Sundin18** [comment]
Hotovo na 38, verze 20.01.18

**Comment by Sentinel65** [comment]
Hm, Petře je tam jeden problémek. Teď jsem si to vyzkoušel a u toho ústředního dispečera to vždy vypíše oblast Praha. lze to ješt nějak upravit ?

**Comment by Sundin18** [comment]
Udělejte ctrl+shift+R v prohlížeči

**Comment by Sentinel65** [comment]
Až doděláš tu 111, tak to zkus tady upravit na větší rozsah, ten mail s operatovním příkazem od ÚD, co jsem ti poslal.
Ale netuším, jak to teda udělat s těmi položkami PO a Úsek (ŽST), které jsou povinné a které sem moc nepasují.

**Comment by Sundin18** [comment]
Ok, tu 111 tedy nahraju. U toho operativního příkazu se tady má nahrát těch 50 nebo kolik příjemců?

**Comment by Sentinel65** [comment]
Žádní příjemci Petře. Jde jen o ten zápis do DB, tzn. rozšířit to pole na zápis (aspoň tolik, aby se tam vešel ten zápis z toho mailu). Oni si to bokem stejně rozešlou mailem. Já to ještě zítra proberu s Milanem Jakubcem.

**Comment by Sentinel65** [comment]
Petře nové zadání pro operativní příkazy - promysli co bude z tvého hlediska možné a jednodušší:

1. buď je možnost spojit formulář pro VD i ÚD
2. nebo pak udělat samostatný formulář pro ÚD
3. 1) combo PO přejmenovat na **PO (Oblast)** a doplnit tam položky "Celá síť", "CDP Praha", "CDP Přerov", u **doplněných položek by se NIKAM žádný MAIL NEODESÍLAL**, výběr bych upravil tak, jak je u příkazů, tzn. že by **byla možnost vybrat více PO (oblastí) najednou**.
4. 1) combo **ŽST (úsek)** by v tom případě bylo **nepovinné**
5. Položku **Důvod** rozšířit na maximálně možnou hodnotu znaků

**Comment by Sundin18** [comment]
A když ÚD vybere jen PO, tak se to má chovat stejně jako v případě, když to píše VD? To znamená, že se odešle také email na příslušné PO?

**Comment by Sentinel65** [comment]
Ano, to není nic proti ničemu.

**Comment by Sundin18** [comment]
jj, to jsou stejný emaily jako u příkazů

**Comment by Sentinel65** [comment]
ano

**Comment by Sundin18** [comment]
Hotovo, verze 20.02.04, k vyzkoušení na 38.

**Comment by Sentinel65** [comment]
No je to první nástřel. Mám k tomu pár bodů:

1. Bylo by možné, aby když přepnu /zvolím/ danou roli (nebo když se rovnou daný uživatel pod touto rolí přihlásí), aby se rovnou načetla daná konkrétní stránka - pro VD "operative-command" a pro ÚD "ud-operative-command" ? To tlačítko Operativní příkazy VD nebo Operativní příkazy ÚD je tam dost matoucí. Takto by se načetla hned příslušná stránka a bylo by tam jen tlačítko **Přidat záznam**
2. U operativního příkazu pro ÚD jde záznam uložit, chybí tam tlačítko pro opravu /editaci/, ve sloupci **Vytvořeno** doplnit i čas pořízení záznamu, chybí sloupec se jménem, kdo pořídil.
3. U toho operatovního příkazu pro VD teď ten záznam ani nejde uložit, háže to chybu Záznam se nepodařilo uložit chyba 500

**Comment by Sundin18** [comment]
1. To by šlo jen v případě, že by stránku operativních příkazů ústředních dispečerů mohl vidět jen ústřední dispečer. Zároveň by nešlo udělat, jak by se mohl ústřední dispečer dostat na stránku operativních příkazů vedoucího dispečera.
2. ok, dodělám
3. opraveno

**Comment by Sentinel65** [comment]
U toho prvního bodů jsem myslel to úplně rozdělit a asi i v menu prostě udělat OP ÚD a OP VD, když to jinak nepůjde.

**Comment by zachyunl** [comment]
Na menu bych se vykašlal, používá se to jednou za uherský rok a bude to zbytečně zabírat místo. Možná bude Detalko a třeba další věci a za chvíli budeme řešit místo v menu.

**Comment by Sundin18** [comment]
1. tlačítko na přepínaní OP VD a OP ÚD jsem tedy ponechal, aby se ÚD a VD mohli přepínat. Souhlasím, že by to ubíralo místo. Odkaz "Kniha OP" je akorát rozdělena pro ÚD a zbytek, tzn. že když na tento odkaz klikne role ÚD, tak se mu zobrazí nejprve OP ÚD, u ostatních se zobrazí OP VD.
2. hotovo

**Comment by Sentinel65** [comment]
OK

**Comment by Sentinel65** [comment]
Tak netuším, jestli se to nějak tluče, ale jak jsi opravil ty příkazy, tak teď pro změnu zase nevidím u Knihy OP u ústředního dispečera tlačítko **Přidat záznam**, u vedoucího to tlačítko je.
Na 38 to tlačítko u Knihy OP u role ústřední dispečer je.

![image](https://user-images.githubusercontent.com/54531291/75221147-64c1e000-57a1-11ea-9b56-d8885c7e7f07.png)


![image](https://user-images.githubusercontent.com/54531291/75221182-7dca9100-57a1-11ea-9606-6736cc448fbe.png)

**Comment by Sundin18** [comment]
Na té 37 jsem nenastavil ÚD, že může pridat záznam. Kolem oběda to doplním.

**Comment by Sundin18** [comment]
opraveno

**Comment by Sentinel65** [comment]
OK
