### ISSUE TITLE
Vytvoření duplicitního záznamu ZaMU v jeden okamžik

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#136]
Petře dnes se v Ústí stalo Rosťovi, že když vytvářel ZaMU 47457, tak v době psaní tohoto záznamu provozní dispečer (Honza) vytvořil Stanovisko k narušení. V ten okamžik to Rosťovi vyskočil do červených upozornění a on to stanovisko přiřadil k danému ZaMU. Poté když to odeslal, tak se vytvořili 2 duplicitní záznamy ZaMU 47457 a 47458. Teď je jeden skryt, ale v DB to uvidíš.

**Comment by Sundin18** [comment]
to pravděpodobně kliknul 2x rychle po sobě. To znamená, že ještě než se stihl vymazat formulář, tak poslal ty samá data znovu. Zkusím se podívat, jestli se tomu dá zabránit.

**Comment by Sentinel65** [comment]
Tak jsem to zkoušel nasimulovat na 38 a povedlo se to teda až při opravě, ale s tím DP to myslím vůbec nesouvisí. Opravdu jsem rychle 2x za sebou klikl na **Uložit změnu záznamu** a vytvořil se ten samý duplicitní záznam 45456 viz obrázek, ale po refresh stránky tam je pak už zase jenom jednou

![image](https://user-images.githubusercontent.com/54531291/74831667-fbac1980-5315-11ea-8751-5ca84f479670.png)

**Comment by Sentinel65** [comment]
Teď se mi teda povedlo i to, co Rosťovi.


![image](https://user-images.githubusercontent.com/54531291/74831932-85f47d80-5316-11ea-816e-2cc26d2e1d8f.png)

**Comment by Sundin18** [comment]
dám schovat to okno okamžitě, ještě než se data uloží do DB. Teď jsem si to zkoušel na lokále a klikal jsem rychle jako mistr světa a nikdy se mi to nepodařilo poslat 2x. To tam pak tedy nahraju s novou verzí.

**Comment by Sentinel65** [comment]
Máš špatnou koordinaci ukazováčku :-)
Mně se to teď zase povedlo 47491, 47492 duplicita, mám pocit že to není o uložení dat, ale opravdu o tom rychlém dvojitém kliku na to tlačítko

**Comment by Sundin18** [comment]
Já to ještě nikam nenahrál. Testuju to na svém pc.

**Comment by Sentinel65** [comment]
jj já to zkoušel zase na té 38

**Comment by Sundin18** [comment]
tak na 38 udělána změna. Snad nebude někdo tak rychlý, aby se mu to povedlo zadat 2x :-)
verze 20.02.03

**Comment by Sentinel65** [comment]
Tak bohužel pořád duplicita - 47494 a 47495 - TEST3

**Comment by Sundin18** [comment]
A udělal jsi refresh prohlížeče? Pokud ano, tak bohužel tomu není jak zabránit.

**Comment by Sundin18** [comment]
teď jsem to zkusil ještě v práci a duplicitu se mi nepodařilo udělat

**Comment by Sentinel65** [comment]
No taky netuším, prostě při tom opravdu rychlem dojkliku se tam ta duplicita udělá

**Comment by zachyunl** [comment]
Kluci Rosťa dnes určitě záměrně rychle neklikal, buď to byla náhoda, nebo to souviselo s tou výtkou, kterou udělal Honza.
Petr ať nasadí úpravu a pojďme od toho pryč.

**Comment by Sentinel65** [comment]
Nasazovat teď něco nemá smysl, protože to ten problém prostě zatím Jirko neřeší. Petr tam sice něco poupravil, ale mně se na té 38 opět rychlým dvojklikem povedla duplicita.
Nikdo neříká, že to udělal schválně, ale kolikrát klikneš na myš a uděláš pohyb, že si to ani neuvědomíš.
S tím DP to vůbec nesouvisí, to byla jen shoda okolností. Já tu duplicitu prostě vytvořím pouhým velice rychlým dvojklikem na tlačítko. A vpravo dole se mi okamžitě zobrazí 2x zelená notifikace, že záznam byl uložen.
Tak buď Petr vymyslí nějaké ošetření toho dojkliku nebo to prostě necháme být. Tohle je proprvé, co se to někomu stalo. Od toho je tam to tlačítko "Zrušit".

**Comment by Sundin18** [comment]
Tak to zkuste ještě teď, jestli ani tohle nezabrání, tak už pak nevím. Raději si nejprve udělejte refresh prohlížeče

**Comment by Sentinel65** [comment]
Hm tak to vypadá už lépe, zatím se mi to nepovedlo. Tak to nasaď

**Comment by Sundin18** [comment]
ok
