### ISSUE TITLE
Přeposílání dat ze Šediváku do systému drážní HZS

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#137]
> Dobrý den pane Horký.
> Děkuji za dnešní věcné jednání.
> Na základě naší dohody prosím nasměrovat mailovou komunikaci na adresu **hzsizs@szdc.cz**
> Předpokládám, že nám **pro ověření dalšího postupu bude stačit dvoudenní vzorek**.
> Prosím dejte mi vědět, až to bude běžet.
> 
> Hezký den přeje 
> Jiří Zoubele
> Podpora operačního řízení HZS
> 731 428 390

Petře, doplň tedy tu jejich mailovou adresu do DB, aby se jim přeposílaly zprávy při každé vytvořené události a její opravě v ZaMU tak, jak to chodí teď mně.

Za dva dny tzn. ve středu 26.2.2020 někdy po obědě to zase smaž, oni si z toho vzorku těch zpráv udělají nějaké své vyhodnocení s programátorem, jestli ta data tak jak jim je teď budeme posílat dokáží nějak rozumně zpracovat.

Jen pro informaci - v tom svém systému mají vytvořeného svého poštovního klienta, který příjímá klasické textové zprávy a dokáže ten text nějak zpracovat, vyfiltrovat a potřebná data (primárně tedy lokalitu) uložit do DB a podhodit v systému konkrétnímu operačnímu pracovišti v dané lokalitě.
Jestli se jim to povede i od nás se uvidí po tom jejich vyhodnocení.

Pokud by s tím měli problémy, říkal jsem, že bychom jim eventuélně mohli vypomoci tím, že určitá data "zpřesníme" a budeme vkládat do příslušných kolonek - dopravní bod (potažmo dopravní úsek) bychom dali zvlášt do inputu, stejně tak např. v případě nutnosti by se zadávalo P číslo přejezdu a km poloha (tady už bychom mohli i použít číselník).

**Comment by Sundin18** [comment]
Ok, přidáno. Bylo by pak dobré, aby si řekli, co chtějí zasílat atd.

**Comment by Sentinel65** [comment]
Zatím chtějí nějaký vzporek, aby věděli, co jim tam chodí a jak to budpu moci zpracovat. Až teprve potom řeknou, co a jak dál.

**Comment by Sentinel65** [comment]
Petře vypni to přeposílání těm hasičům a dej mi vědět až to bude.

**Comment by Sundin18** [comment]
vypnuto

**Comment by zachyunl** [comment]
Přeposílání otestováno.
