### ISSUE TITLE
Nová role vedení

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#14]
Vzhledem k prohlížení archivních dat vedením CDP, případně jinými jednotkami či GŘ prosím o dodělání nové role. Nazvěme ji např. vedení pokud nemáte někdo vhodnější pojmenování? Tato role nebude mít žádná speciální práva vyjma prohlížení všech dat v příslušných formulářích.

**Comment by Sentinel65** [comment]
To bych nedělal Jirko. Už teď se tam na čumendu dívá tolik lidí, že o tom ani nevíme (OŘ, lidí z bývalé SDC, GŘ). Jak chceš všechny ty účty hlídat. Nechal bych to, jak je to teď s tím, že tam nebudou žádná tlačítka, opravy záznamů.

**Comment by zachyunl** [comment]
V současné době jdou anonymně prohlížet pouze data u mimořádných událostí, cílem je prohlížení všech formulářů bez editace.

**Comment by Sentinel65** [comment]
Ná základě tvojí odpovědi: https://github.com/Sundin18/backend/issues/26#issuecomment-527037794
bych teda rád, aby ty smazané záznamy byly pro definované role (**v rámci CDP - ne pro běžné uživatele**) jednoduše k dispozici přes nějaký filtr nazvaný třeba "Smazané záznamy".

**Comment by Sundin18** [comment]
Tam šlo o to, že jsem mazal i záznamy přímo v DB, když jsem zkoušel tu migraci. Nemazal jsem je přes aplikaci.
Každopádně mi bylo jasné že k tomuhle jednou dojde a budete to chtít zobrazit. Ale asi bych to udělal až v rámci nějakého rozšíření nad rámec původního návrhu. Aby aplikace nejprve byla funkční podle požadavků uživatelů. Jestli souhlasíte. Kdyby bylo akutní se na smazaný záznam podívat už teď, tak by třeba Jirka @zachyunl se podíval přímo do DB.

**Comment by Sentinel65** [comment]
Petře, proto jsem tomu dal prioritu 5, nechci, aby jsi to dělal hned, ale taky aby se na to nezapomnělo, protože tohle je dost průserové, když má někdo možnost v DB smazat záznam. Pokud už to oprávnění z jakéhokoli důvodu má, tak ať je o tom někde záznam (třeba oznámení mailem na administrátora) a potom možnost si ty smazané záznamy vyfiltrovat.

**Comment by Sundin18** [comment]
V DB se to nevymaže, ten záznam tam zůstane. Ale jasný, pak se může udělat notifikace a i výpis smazaných záznamů.

**Comment by Sentinel65** [comment]
OK, necháváme to otevřený, až se vyřeší důležitější věci, vrátíš se k tomu ...

**Comment by Sentinel65** [comment]
> V současné době jdou anonymně prohlížet pouze data u mimořádných událostí, cílem je prohlížení všech formulářů bez editace.

Nevím, jestli někdo z vedení chce, aby si všude prohlíželi např. DP, ST nebo PZ které ani pro ty OJ nejsou určeny

**Comment by Sentinel65** [comment]
Jinak bych tedy rád zase "popojel" tzn. je potřeba vytvořit obdoubné role jako je va@szdc.cz pro vedoucí analýzu (oddělení Radka Bejšáka), ale byly by to role zvlášť pro CDP Praha a pro CDP Přerov.
Jak už to tady někde Petr nazval a já to i popsal v průvodním dopise pro OJ, byla by to role Kontrolor CDP PHA a Kontrolor CDP PRE. Tyto role by měly defacto stejná oprávnění jako ta va@szdc.cz, ale každá jen pro svoji vlastní oblast.  Kontrolor CDP PHA oblast Ústí a Prahy pouze na prohlížení, Kontrolor CDP PRE oblast Přerov pouze na prohlížení. Někteří se už zběžně dívali přes tu roli va@szdc.cz, takže teď to chce dokončit, aby tam viděli jen ta svá data.

**Comment by Sundin18** [comment]
Hotovo, přihlašovací údaje pro kontroléry CDP jsou ccdppha@szdc.cz a ccdppre@szdc.cz, hesla jako ostatní. (Verze 19.09.29)

**Comment by Sentinel65** [comment]
OK, ještě kosmetika - v názvu po přihlášení **KontrolérCDP PHA** můžeš to přejmenovat na **Kontrola CDP PHA (Kontrola CDP)** jednak aby ta slova byla odděleně a místo Kontrolér - Kontrola.
Při tom přihlášení, lze u těchto rolí, pokud jen prohlížejí a nevytváří a nemají možnost editace, nastavit i pro ZMU, aby měly automaticky nastavenou oblast PHA a Ústí a po zadání uživatelského jméne a hesla nemuseli vybírat oblast ?

**Comment by Sundin18** [comment]
hotovo verze 19.09.33
