### ISSUE TITLE
DP - přílohy docx

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#143]
Ahoj Petře, dnes mě upozornil Honza Frajer z analýzy, že v DP **nejdou otevírat v odpovědích přílohy typu *.docx.**

Vyzkoušel jsem u něj i u sebe a po stažení to při otevření dokumentu dává tuto hlášku:

![image](https://user-images.githubusercontent.com/54531291/81528705-a0f6ec80-935d-11ea-887b-1d919a6ca866.png)

U přílohy v levém sloupci při vložení VPZ (#483) ve formátu *.jpg, dojde sice ke stažení, ale po otevření souboru to háže tuto hlášku:

![image](https://user-images.githubusercontent.com/54531291/81529058-4c07a600-935e-11ea-94fd-71e2b32f63b0.png)

Dokumenty ve formátu *.pdf jdou otevírat bez problému.

**Na TESTU na 38** v levém sloupci formát *.png v pořádku, v odpovědích v pravém sloupci **nejde formát *.docx ani *.pdf** (de facto žádná příloha) vůbec stáhnout** DP #311, ST #211

TEST vyzkoušen v Chrome i v novém Microsoft Edge.

**Comment by Sentinel65** [comment]
Tak dneska jsem to zkoušel na ostrém a je to to samé, u DP 637 odpověď ze včerejška 11.5.2020 v *.docx a taky to blbne.

**Comment by Sundin18** [comment]
Zatím vůbec netuším, proč tomu tak je. Proto navrhuji, ať se ukládají soubory jako pdf. Neměl by to být problém navíc, protože převod z docx do pdf jde jedním kliknutím ve wordu.

**Comment by zachyunl** [comment]
Mám k tomuto pár dotazů. Víme určitě, že to na ostrém chodilo? Máme nějaký časový snímek, kdy to případně přestalo chodit? 
Petře neupravuješ na ostrém serveru v kódu hlavičku odpovědi? Když si pošlu data na 38 a na ostrém, tak jsou úplně rozdílné hlavičky a další části. Není zde něco ohnutého kvůli NTLM autentizaci, či uploadu typů příloh?
![image](https://user-images.githubusercontent.com/47257941/82115813-6ded9800-9765-11ea-960c-560442855e7f.png)
![image](https://user-images.githubusercontent.com/47257941/82115844-99708280-9765-11ea-91d2-c68fa7922b3a.png)

**Comment by Sundin18** [comment]
Na ostrém to chodilo. Kdy to přesně přestalo nevím, ale nějak před víkendem to ještě šlo. Kód na 38 a ostrém je stejný. Proč to v jednom případě stáhne normálně a ve druhém jinak netuším.

**Comment by Sentinel65** [comment]
Ano víme určitě, že to fungovalo. Honza Frajer měl ten čtvrtek před tím stažený soubor *.docx na disku a šel otevřít normálně.
Oni jdou otevřít i teď, ale musíš to 3x odklepnout.

**Comment by Sundin18** [comment]
@zachyunl na to přišel, funguje :)
