### ISSUE TITLE
Tlačítko - Registrovat

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#15]
Petře, u tohoto tlačítka to funguje jak ? Tam se bude moci zaregistrovat kdokoli ? Předpokládám, že tu registraci, by měl verifikovat administrátor a novému uživateli na základě nějakých informací přidělit roli, aby se neprováděla automaticky a pak jsme ani netušili, kdo všechno tam má účet. 

Možná by bylo dobré to tlačítko přejmenovat na "**Žádost o registraci**"

**Comment by Sundin18** [comment]
On se sice někdo zaregistrovat může, ale nemá žádná oprávnění a ani není pro něho vybrána oblast. Ty mu pak musí přidělit administrátor. Do té doby funguje stejně jako anonymní uživatel.

Ok, přejmenuji.

**Comment by zachyunl** [comment]
Petře nezavírat dokud to nebude vydáno ven v nové verzi.
