### ISSUE TITLE
Filtry - položka od - do

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#16]
Mám tady námět od vedení CDP s kterým se ztotožňuji i když to asi nebude jednoduché z programátorského hlediska. Předělat filtr dat od - do, tak jako to je na současném oorp. Jsou lidé, kteří potřebují filtrovat data pouze od - do např. z jedné stanice a dále s tím pracují. Není to náhodný případ, ale používá se to. Nové pojetí filtrování toto neumožňuje.

**Comment by Sundin18** [comment]
Doplněno, verze 19.08.1

**Comment by zachyunl** [comment]
Petře filtr doplněn, ale nechápu jak funguje. Když si dám, že chci např. položky od 13. 9. 2019, tak se mi zobrazí pouze 2 položky. Jak je to možné? Až budeš dělat opravu, čísluj novou verzí ať se v tom vyznáme. Verze 19.08.01 už byla jednou vydána a není možné do ní dělat opravy, musí to mít nové číslo z důvodu přehledu.

**Comment by Sundin18** [comment]
Já to teď zkoušel a zobrazilo se mi to správně.

**Comment by zachyunl** [comment]
zadán např. filtr od 27.8 a zobrazí se záznam 1.8? Jinak jsem objevil ještě drobnost, že po najetí myši na pole filtru "do" se zobrazí text záznamy od vybraného dne, ale má být do.
![image](https://user-images.githubusercontent.com/47257941/63910797-70b62a80-ca28-11e9-8a8d-857aa6eceb44.png)

![image](https://user-images.githubusercontent.com/47257941/63910853-9c391500-ca28-11e9-895b-23e265be5a6b.png)

**Comment by Sundin18** [comment]
Ten filtr funguje tak, že pokud zadám jen "datum od", tak zespoda není nijak omezen. Tzn.,že funguje stejně jako fungoval předtím. Zobrazí se všechny záznamy zahájené od vybraného data. Naopak pokud zadám jen "datum do", tak se zase zobrazí záznamy od aktuálního (dnešního) dne do vybraného data. Pokud zadám oboje, tak se zobrazí záznamy v určeném rozsahu.

Nápovědu opravím.

**Comment by Sundin18** [comment]
Teď na to ještě koukám. Ten filtr fungoval dříve i podle požadavku, ale asi se neshodujeme v pochopení slov "od" a "do". Já zamýšlím, že datum "od" je jako např. dnešní den a od toho dne, ke starším datum se hledá (tedy je to horní hranice). Vy asi to asi chápete opačně, že je to od vybraného dne směrem k novějším datum, tedy jako spodní hranici.

**Comment by zachyunl** [comment]
Petře tu Tvojí logiku nemůže běžný uživatel na první  dobrou pochopit. Jseš schopen to udělat dle intervalové logiky? Čili od je od data vyplněného až po xxx.

**Comment by Sundin18** [comment]
No mně se zdá logičtější, když řadím data od novějšího ke staršímu. Ale ok, prohodím to tedy ;-)

**Comment by Sundin18** [comment]
Hotovo verze 19.08.3

**Comment by Sentinel65** [comment]
V tom vyhledávání - navrhuji udělat ty "input" s datumy krapet delší, nelíbí se mi tam pak to zmenšení fontu a dva řádky, ten font bych nechal stejně velký a tak, aby to bylo v jedné řádce takto:
 Od: 28.08.2019    x      Do: 29.08.2019     x
V "input" **hledat** prosím tě doplnit také křížek na zrušení filtru hledat, protože pak to musí ručně mazat.
Vyhledávání je funkční, ale bude to třeba někde polopaticky popsat - třeba i jako tool tip, aby všichni pochopili tu logiku vyhledávání podle toho komba "Zahájeno", "Ukončeno", "Aktualizováno"

**Comment by zachyunl** [comment]
Ahoj na fonty jsem chtěl také upozornit, testuji to nyní na ntb a např. vůbec není vidět poslední číslo z roku. Dále co je potřeba doladit, tak nějaký test blbuvzdornosti. Je nesmysl zadávat filtr např. od 30.8 do 1.8, samozřejmě to záznam nenajde. Ale uživatele by tento nesmysl neměl vůbec pustit.
![image](https://user-images.githubusercontent.com/47257941/64047660-b4677c00-cb6f-11e9-8d66-e6fd5cfcb7a1.png)

**Comment by zachyunl** [comment]
Petře a jestli budeš u tohoto řešit i font, tak se mrkni co tam vlastně máš? Správně jsou povoleny pouze Styrene a Verdana. Já vím že jsem s tím otravnej, ale když už to budeš upravovat s fontem, tak ať se to poté nepředělává, protože každý font má jinou šířku.

**Comment by Sundin18** [comment]
Udělal jsem tedy ten filtr do jednoho pole. Je tím ošetřena validace "od"-"do" a zároveň ušetřeno místo na roztažení komponenty, takže by se tam měl zobrazit interval celý i na monitorech s menším rozlišením. (verze 19.08.4). Co se týče toho písma. Není to jen písmo doporučované? Ten font Styrene je komerční a Verdana je teda na pohled docela ošklivá.

**Comment by Sentinel65** [comment]
Klucí, proč tu máme dva požadavky na to hledání (#16 a #17) ?? Zkuste to sloučit ...
To hledání asi už bude ok, chce to větší vzorek dat s větším rozptylem času. Ale jak to ted Petr pojal, tak to vypadá moc dobře a zjednodušilo se to ...
Akorát v položce "**hledat**"  stále chybí ten křížek na zrušení / vymazání textu hledání, nebo jak se toho textu zbavím, musím ho ručně vymazat nebo to jde i jinak ?

**Comment by Sundin18** [comment]
Nn, jakmile do toho políčka začneš psát, tak se ten křížek zobrazí

**Comment by Sentinel65** [comment]
Ano, ted jsem to zjistil, v prohlížeči Chrome, Chromium to funguje, ale ve Firefoxu ten křížek nevidím.

**Comment by zachyunl** [comment]
https://github.com/Sundin18/backend/issues/16#issuecomment-526900409
Ahoj Petře, tak jsem opět studoval vizuální identitu. Takže co se týče písem tak jsou povoleny 2 typy fontů. Písmo Styrene je skutečně komerční a je určeno "v logu, na tiskovinách zpracovávaných 2
grafickými studii nebo k označování vozidel. ". 
Pro text dokumentů vytvářených v kancelářských programech jako je např. Microsoft Office, pro **webové stránky** a aplikace, e-mailové zprávy, formuláře a razítka se používá systémové písmo Verdana. 
Mně osobně ta Verdana nijak hnusná nepřijde, je to pouze o subjektivním pocitu. Koukal jsem, že stránky www.szdc.cz mají komplet vše děláno ve Verdaně. Láďa Čermák na Kazasu má mix 3 písem, ale Verdanu tam má jako hlavní písmo.

**Comment by zachyunl** [comment]
https://github.com/Sundin18/backend/issues/16#issuecomment-526909681
Mně to také na Firefoxu nechodí s křížkem. Ještě to musíme testnout s Edgem, protože ho začínáme instalovat z MDT. Já ho teď nemám po ruce na otestování.
