### ISSUE TITLE
Položka hledat jiné pojetí

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#17]
Současné pojetí hledat je pro uživatele matoucí. Navrhuji buď udělat, že po zapsání nějakého textu, se bude automaticky rovnou rolovat vyhledaný text, tak jako např. zde https://help.github.com/en?query=l bez dalšího klikání. Nebo pokud to nepůjde, tak přidělat tlačítko hledat na které uživatel klikne jako na současném www.oorp a poté dojde k vyhledávání.

**Comment by Sundin18** [comment]
Hotovo. (Verze 19.08.4)

**Comment by zachyunl** [comment]
Mám k tomuto dotaz jak je to na starém webu? Když si zadám zde u nového řešení necelé slovo, tak zde to nic nenajde. Např. "osob", tak nic nenajde, protože je v textu osoby. Neříkám že to je dobře nebo špatně. Spíše nevím jak to je u původního webu, protože tu nemám adresu, kterou jsem měl nacachovanou a smáznul jsem si ji.

**Comment by Sentinel65** [comment]
Tak jiné pojetí hledání se ujalo, jak vidno, ale to pole "**hledat**" nefunguje korektně.

Zkouším to teď konkrétně přihlášen pod svým účtem, kombo má nastaveno "Zahájeno", filtrování dle datumu nic:

Do vstupního pole "**hledat**" píšu **Beroun**, na nic nemačkám a vyhledají se mi 4 záznamy  #26, 19, 17 a 8. 
Když tam ale napíšu jen "**Berou**" bez "n" na konci, tak se nenajde nic.
Když napíšu "strojvedoucí", zobrazí se záznam #22.
Když napíšu jen "stroj", nezobrazí se nic.
Když napíšu "usmrcen", zobrazí se pouze záznam #22, přestože v záznamu #26 je slovo "usmrcení".
Rozdíl je v tom, že u záznamu #22 je Šetření ukončeno, u záznamu #26 Šetření trvá.
Tohle je třeba dopilovat. Navíc, pokud by to bylo možné, tak bych rád v těch vyhledaných záznamech viděl zvýrazněn hledaný řetězec. Takto to teď funguje na ostrém webu:
http://www.oorp.szdc.cz/web/mu/view_search.php?search=porucha&or_check=%283%29

Nevím, jestli správně chápu funkčnost filtru u komba "Zahájeno", "Ukončeno", "Aktualizováno", ale "Zahájeno" by mělo defacto obsahovat naprosto všechny záznamy, protože u každého vzniklého záznamu musí být vyplněno pole Zahájeno. 
"Ukončeno" pak všechny záznamy, kde je vyplněno pole "Ukončeno". 
"Aktualizováno" pak jen ty, kde je aspoň jedna oprava záznamu.  Chápu to správně ?

**Comment by Sentinel65** [comment]
Tak to bude sranda teda, teď to testuji na Microsoft Edge a tam příkladně dám vyhledat "**usmrcen**" a zobrazí se pouze záznam #26.
K tomu slovu připojím dlouhé "í" čímž vzniká "**usmrcení**" a zoubrazí se pouze záznam #22.
Takže to oproti Chromu funguje taky jinak.
Jinak v Microsoft Edge, v IE, v Chromu/Chromium se ten křížek v poli "**hledat**" zobrazuje.
Teď jsem vyzkoušel na portable Firefox Quantum v68.0.2 a křížek se tam taky objevuje.

**Comment by Sundin18** [comment]
Vyhledávání funguje jako fulltext. Tedy vyhledá konkrétní slovo. Nejsem si jist, jestli umí innodb tabulky vyhledávat jako myIsam pomocí příkazu LIKE. Výhoda toho fulltextu je v rychlosti vyhledávání.

To první kombo není filtr. Je to kvůli řazení záznamů. Řadí záznamy podle vybrané položky.

**Comment by Sentinel65** [comment]
Na kolik znaků to vyhledávání teda funguje ?? Jak to že při zadání "usmrcen" nenajde i řetezec "usmrcení" ?

**Comment by Sundin18** [comment]
Hledá to celá slova, ne jen části. Např. Berou nenajde, protože takové slovo tam není, ale Beroun ano. K tomu kombu pro řazení jsem raději přidal text, aby to bylo lépe rozpoznat, co to dělá.

**Comment by Sentinel65** [comment]
No popravdě s tímto se setkávám poprvé, aby vyhledávání fungovalo JEN NA CELÁ SLOVA a nikoliv hledaný textový řetězec. Potřebujeme vyhledávat textový řetězec.

**Comment by Sundin18** [comment]
Vyhledává tedy i jen části slov. Verze 19.09.2

**Comment by Sentinel65** [comment]
Petře, výborně, teď se to vyhledává přesně, jak jsem chtěl ! V souvislosti s uzavřeným požadavkem #10 je třeba do toho komba s filtrama "Zahájeno", "Ukončeno", Aktualizováno" doplnit další dvě položky "Zahájeno (ZP)" a "Ukončeno (ZP"), seřaď je hned pod to "Ukončeno". Děkuji

**Comment by zachyunl** [comment]
Jirko tak si issues znovu otevři. Jako vlastník bys měl mít oprávnění, jestli to mají rozumně uděláno. Nezkoušel jsem.

**Comment by Sentinel65** [comment]
OK tak ten požadavek #10 znovu otevři a ještě doplním, jak by mělo to kombo vypadat a přepiš tam tento text.

"ID"
"Zahájeno" 
"Ukončeno" 
"Zahájeno (ZP)"
"Ukončeno (ZP")
"Aktualizováno"
