### ISSUE TITLE
Tisk záznamů a export

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#18]
Na současném webu www.oorp je po vyhledání určité skupiny položek možnost zaškrtnutí jenom části z nich a poté si je mohu vytisknout. Tuto funkcionalitu by uživatelé chtěli i do nového pojetí a případně k tisku dodělat ještě export např. do pdf či jiného vhodného formátu.

**Comment by Sentinel65** [comment]
Měním tady Prioritu na 2  z následujicího důvodu:

V pohledu **Závady a mimořádné události** toto platí pro UNL a PRE ! Praha to nedělala a nedělá. Nevím jistě, jestli to ještě dělá UNL, ale PRE určitě ANO.

Ve chvíli, kdy analyzátor dořešil závadu a ve formuláři vybral volbu **Šetření ukončeno**, tak se mu zpřístupnil seznam **e-mailových adres** (viz obrázek), na které se uložením záznamu ta závada odeslala.
Takže nechám na Petrovi, aby se vyjádřil, ale je tu varianta, že bychom to mohli udělat v tom opravném formuláři pod tlačítkem **Změnit záznam** nebo potom při tom **tisku**, kdyby se pro vybraný záznam vygeneroval soubor PDF, který by se mohl poslat mailem (přímo, či nepřímo).


![MU_setreni_ukonceno](https://user-images.githubusercontent.com/54531291/65036662-374c4d00-d94c-11e9-8d08-c5c137fdb69e.png)

**Comment by Sundin18** [comment]
V Ústí holky skoro ani nevěděly, že to mají. Asi bych se přikláněl spíše k variantě, když se pro tisk vytvoří pdf soubor. Nemusel by se pak udržovat někde v DB seznam emailových adres, i když se asi moc nemění (nevím), ale také z důvodu, že by pak to okno bylo už docela velké (i když asi bych to schoval do "roletky" ty sloupce adres, takže by to o moc okno nezvětšilo).

**Comment by Sentinel65** [comment]
OK souhlas, tak to udělej, že pro tisk se vytvoří pdf soubor.

**Comment by Sentinel65** [comment]
> OK souhlas, tak to udělej, že pro tisk se vytvoří pdf soubor.

No a tady by se tedy udělalo **tlačítko na tisk označených záznamů** do PDF a zároveň další **tlačítko na vygenerování označených záznamů** do PDF s tím, že by se **automaticky přidaly do implicitní aplikace pro odeslání pošty jako příloha**. Uživatel by si pak doplnil jen adresáty.

**Comment by Sundin18** [comment]
Tisk hotov. Verze 19.09.26
Když uživatel zaškrtne poličko v levém horním rohu u MU, tak se zobrazí tlačítko "Vytvořit PDF" vedle tlačítka "Přidat záznam" a po kliknutí na toto tlačítko se vytvoří pdf soubor se zaškrtnutými MU, který lze pak vytisknout, či poslat emailem.

**Comment by Sentinel65** [comment]
Ahoj Petře, když kliknu na Vytvořit PDF, tak mi to nabízí uložit soubor. Měl jsem na mysli 2 ikonky, jedna by provedla tutu operaci, tzn. převod do PDF a uložení na lokál, druhá ikonka by provedla to samé, ale otevřela implicitní poštovní aplikaci a to pdf tam šoupla jako přílohu hned. Půjde to ?

**Comment by Sundin18** [comment]
Poslání záznamu MU po kliknutí na "šetření ukončeno" na vybrané emailové adresy lze v okně po stisknutí tlačítka "Změnit záznam". Zatím jsou tam na testování jen naše adresy. Verze 19.09.27

**Comment by Sentinel65** [comment]
Výborně, zasílání mailu funguje okamžitě, 
V tom mailu tam oprav zkratku hned té první položky - Záznam MU: na **Záznam ZMU:**

**Comment by Sundin18** [comment]
Opraveno, verze 19.09.28

**Comment by Sentinel65** [comment]
> Poslání záznamu MU po kliknutí na "šetření ukončeno" na vybrané emailové adresy lze v okně po stisknutí tlačítka "Změnit záznam". Zatím jsou tam na testování jen naše adresy. Verze 19.09.27

Petře můžeš to pro účely testování rozšířit ještě na adresy analýzy Přerov (nebo jestli už to budou mít přířazené ty adresy v závislosti na jejich oblasti):

cdppreanalyza@szdc.cz
krcmarova@szdc.cz
petrikova@szdc.cz
sterbaf@szdc.cz

**Comment by Sentinel65** [comment]
Plovoucí tlačítko **Vytvořit PDF** je OK, ještě bych vedle něj vytvořil další plovoucí tlačítko nebo klávesovou zkratku (ta by byla i lepší) na označení / odznačení všech záznamů dle nastaveného filtru.

**Comment by Sundin18** [comment]
Tady přesně nerozumím, dle jakého filtru?

**Comment by Sentinel65** [comment]
Jednak tam máš překlep a **všehny** a asi bych to tam Petře ještě přejmenoval na **Vybrat vše** a po najetí myši zobrazil Tool tip **Označit / odznačit všechny záznamy na stránce** aby tam nebyl tam dlouhý popis.

**Comment by Sundin18** [comment]
Hotovo verze 19.09.33

**Comment by Sentinel65** [comment]
Ještě tam dopln toto a můžu to uzavřít:

> 
Petře můžeš to pro účely testování rozšířit ještě na adresy analýzy Přerov (nebo jestli už to budou mít přiřazené ty adresy v závislosti na jejich oblasti):

cdppreanalyza@szdc.cz
krcmarova@szdc.cz
petrikova@szdc.cz
sterbaf@szdc.cz

V tom mailu prosím tě ještě pozměň jak je začátek a konec zastavení provozu, tak zatím je Vydal:, tady to prosím tě uprav na Pokyn vydal:

**Comment by Sundin18** [comment]
hotovo, verze 19.10.0

**Comment by Sentinel65** [comment]
Petře tady ještě doplň do textu toho mailu u toho zastavení a obnovení provozu slovo **Pokyn vydal**:, teď je tam jen Vydal:

**Comment by Sundin18** [comment]
Opraveno, verze 19.10.01
