### ISSUE TITLE
Import dat ze současné databáze do nového prostředí

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#19]
Petře docela by se hodilo, kdybys udělal přednostně něco čím bychom dostali data ze současného webu do nové databáze. Bavili jsme se o tom, že to bude stejně potřeba ve fázi přechodu ze starého webu na nový. Ale nyní na detailnější testy hlavně z pohledu uživatelů, by to bylo potřeba již teď. Jde primárně o mimořádnosti.

**Comment by Sentinel65** [comment]
Tohle je tak trochu vázané na konečnou strukturu dat v novém a stávajícím systému. Dokud nebudeme mít všechny položky struktury ve finálním stavu, tak asi nemá smysl dělat importní script.

**Comment by Sundin18** [comment]
Ok, udělám teď #10

**Comment by Sundin18** [comment]
Mám připravený dotaz pro migraci dat. Vzhledem k tomu, že v nové DB je pojato uložení změněných údajů a ve staré je jen pouze informace kdo a kdy měnil zápis, nechal bych staré údaje bez této informace, jestli souhlasíte. Akorát na těch starých zkušebních datech se asi při migraci uložil text v nějaké znakové sadě, která z českých znaků udělala "rozsypaný čaj", proto se chci zeptat, zda v aktuální DB na ostrém serveru, jsou texty čitelné.

**Comment by zachyunl** [comment]
Petře takže by to bylo i bez údajů kdo kdy změnil zápis? 
Co se týče rozsypaného čaje, tak jsem to trochu studoval přes víkend, protože jsem si s tím lehce hrál přes csv a hedisql. Bohužel ten "rozsypaný" čaj je u staré databáze použitou charset verzí, která kdysi byla použita (Swedish v defaultu). Našel jsem k tomu hack, který bys mohl zkusit implementovat.
Zde je popis https://nicj.net/mysql-converting-an-incorrect-latin1-column-to-utf8/
A zde skript https://github.com/nicjansma/mysql-convert-latin1-to-utf8. Jenom si nejsem jistej tím utf8. Přeci jenom my jedeme tabulky utf8mb4_czech_ci. 
V readme je zmínka o tom jak přepnout konverzi do utf8mb4, tak se to musí zkusit, když půjdeme touto cestou.

**Comment by Sundin18** [comment]
Tak se mi podařilo tomu dát češtinu. Pár dat jsem nahrál do naší DB.

**Comment by zachyunl** [comment]
Péťo pomohl ten hack co jsem psal nebo jsi to dělal jinak? Můžeš popsat postup, že bychom tam s Jirkou hodili nějaký testovací data, až to uvolníme pro další testery? Koukal jsem, že bych udělal někde slave pro současný ostrý server a z toho slave by se dali nalévat přímo "aktuální" data.

**Comment by Sundin18** [comment]
Jen mě usvědčil, že hledám správným směrem, ale řešení jsem pak našel někde jinde. 
Vytvořil jsem jen obyčejný INSERT dotaz. Samozřejmě, tím jak je v nové aplikaci pojato přihlašování, jsou stará data importována, že je vytvořil fiktivní vybraný uživatel, ale to nevadí, na testování to stačí a prohlížení taky.

**Comment by Sundin18** [comment]
Dotaz jsem nahrál na ten náš google word soubor. Je omezenen na určitý počet položek, aby se nenahrálo úplně všechno. Stará data už nejsou kompatibilní ve smyslu, že neexistují obvody Plzeň a Ostrava.

**Comment by zachyunl** [comment]
A bude to pak řešení pro finální stav, kdy potřebujeme dostat otevřené položky do živé databáze a ostatní data někam staticky vystavit?

**Comment by Sundin18** [comment]
V podstatě ano, jen každá z těchto položek bude mít, že ji vytvořil nějaký fiktivní dispečer. Podepsaná, ale bude jako to je teď, tedy jménem dispečera, který ji ve skutečnosti vytvořil. Pokud ji pak bude někdo aktualizovat, tak už to bude pod jeho účtem.

O té archivaci by se chtělo asi pak domluvit jak to pojmout.

**Comment by Sundin18** [comment]
Tak letošní rok je celý nahraný do naší DB

**Comment by Sentinel65** [comment]
Koukám se na to, čeština OK, ale jak se tím probírám, tak ne u všech záznamů se ty údaje načetly korektně, vidím u položek **Ukončeno** a **Doba trvání** Invalid date a NaN min

záznam 25, 24, 22, 21, 20

**Comment by Sundin18** [comment]
aha, v té původní DB je údaj 0000-00-00 00:00:00, což samo není žádný čas, proto to Invalid date. To nevím, co tam dát za čas. Jestli to znamená, že závada trvá?

**Comment by Sentinel65** [comment]
Ano trvá

**Comment by zachyunl** [comment]
Petře ten archív bude dneska také řešit, nebo to ještě nemáš rozmyšleno a připraveno?

**Comment by zachyunl** [comment]
Chyba v importu, našel jsem další problém a to ten znak html br.
![image](https://user-images.githubusercontent.com/47257941/64556084-057d2a00-d33f-11e9-9cbd-6c93fdf38e32.png)

**Comment by Sundin18** [comment]
archív zatím nemám rozmyšlený, mám rozpracovaný tisk MU. 
Ten čas ukončení tam byl dopsán nejspíš až potom, co Jirka @zachyunl exportoval DB.

**Comment by Sentinel65** [comment]
Koukám, ty už jsi to tam nastavil jako neukončené, ale je to možné, protože to asi bylo v posledním týdnu, ale každopádně bych ten import ještě někde bokem znovu zkusil a prohlédl ty záznamy, jestli to tam někde není.

**Comment by zachyunl** [comment]
Znak <br> lze odstranit hromadně pomocí phpmyadmin. 
Tabulka records, menu vyhledávní, podmenu Vyhledat a nahradit.
Nejdříve spustit regulární výraz <br>\s--+<br>, tím se odstraní všechny znaky <br> ----<br>. Počet pomlček může být libovolné množství.
Dále pustíme jednoduše ve vyhledání <br> a nahradíme prázdnou položkou. 
Těmito 2 kroky dojde k úplnému vyčištění balastu, který tam zůstal po formátování u html značek <br>.
