### ISSUE TITLE
Záznam PMD - Error: Request failed with status code 500

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#2]
Teď jsem se přihlásil pod VDPHA a zkusil pořídit záznam PMD, vyplnil jsem všechna pole, ale nejde mi ten záznam uložit. Píše to chybu "Záznam se nepodařilo uložit! Error: Request failed with status code 500". Nejde to ani pod jiným uživatelem.

**Comment by Sundin18** [comment]
Opraveno

**Comment by Sundin18** [comment]
Opraveno (Verze 19.08.1)

**Comment by Sentinel65** [comment]
OK!
