### ISSUE TITLE
Návrh na změnu číslování verzí

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#22]
Nemám s tím žádné zkušenosti, ale dle dneška už vidím, že jednotlivé požadavky se mohou vyřizovat i několik dní, respektive přes několik verzí, pokud to nebude odladěné tak, jak je potřeba.
Chtěl bych tedy navrhnout, co kdyby se číslování změnilo na formát YY.MM.DD, tzn. že číslo verze by byl den, kdy tam Petr podhodí nějakou domluvenou a odsouhlasenou změnu požadavků.
Toto mě teď mate, protože tam je a možná ještě bude :-D několik dní stejná verze a trochu se v tom pak ztrácím resp. protože tam je dva tři dny stejná verze netuším a nepoznám podle toho, jestli už tam ty změny jsou podhozené nebo ne. Nevím nakolik je to "otravujicí pro Petra, aby to takto měnil. Nebylo by to "každý den", pouze den, kdy tam podhodí změnu. Vyjádřete se ...

**Comment by zachyunl** [comment]
Myslím že to je zbytečné, každá změna po již vydané verzi má mít nové číslo. Bohužel toto Petr nedodržel, takže to je spíše na nás abychom to vyžadovali, protože to dělá tyto problémy. Co dělal Petr večer za úpravy, tak to již měla být verze 19.08.02. Proto chci aby se začal poctivě udržovat Changelog. Chápu že to je vše pro Petra nové a práce navíc, ale musíme v tom udržet nějaký pořádek. Já budu klidně ten changelog udržovat, ale musí být jasně dáno, že jakmile zde bude napsána nějaká verze, tak již jakákoliv oprava je prostě nová verze.

**Comment by Sentinel65** [comment]
No proto navrhuji to číslování podle dne, ani z toho co píšeš nepoznám, jestli verze 02 či 03 byla podhozená včera nebo kdy vlastně, takto podle verze poznám den, kdy tam byla nasazena.

**Comment by zachyunl** [comment]
Poznáš to podle Changelogu, kde to musí být vše poctivě dokumentováno. Můžeš se podívat do kódu.

**Comment by Sundin18** [comment]
Já měl za to, že všechny tyhle změny, co tu jsou se týkají jedné verze. Takže pokaždé, když nahraju nějakou změnu, tak mám i změnit číslo verze? Tak je to myšleno?

**Comment by Sentinel65** [comment]
Domluvte se s Jirkou, mně je to celkem jedno, ale jde mi o to, že bych rád nějak poznal a podle stávajícího číslování to nepoznám, jestli tam ty změny jsou nebo nejsou podhozené.

**Comment by zachyunl** [comment]
Ano je to tak myšleno, samozřejmě můžeš udělat v jedné verzi třeba 10 oprav a vydat 2 nové funkcionality. Ale jakmile je ven vydána již nějaká verze a poté se zjistí, že tam je chyba, tak se musí nově očíslovat. Právě kvůli přehledu.

**Comment by Sundin18** [comment]
Ok, tak jakmile něco nahraji, tak zároveň změním verzi.

**Comment by zachyunl** [comment]
Petře přesně tak, uvidíme jak se to osvědčí, ale jinak v tom neudržíme nějaký rozumný pořádek.
