### ISSUE TITLE
Sladění webu s korporátní identitou

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#23]
Přiblížit se pokud možno co nejvíce šabloně. Jsou doporučené 3 základní barvy, které mají přesně dané hodnoty. Dále jsou 2 typy písem atd.

**Comment by Sundin18** [comment]
Písmo Verdana (verze 19.08.5)

**Comment by zachyunl** [comment]
Péťo můžeš změnit verzi na 19.09.00? Děkuji ať sedí měsíc.

**Comment by zachyunl** [comment]
Barvy nejsou úplně dle korporátní šablony, ale v základu jsou zde pouze 3.
