### ISSUE TITLE
Závady a mimořádné události - zobrazení editačního okna

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#24]
Tady jedná celkem o zásadní věc aspon po dobu, co testujeme. Většinou to děláme na NTB bez připojeného velkého externího monitoru. Pokud ted zakládám nový záznam v MU nebo opravuji stávajicí, tak v editačním okně u položek **Provoz zastaven od** a **Provoz zastaven do** se nedostanu žádným způsobem na výběr datumu a času ve spodní části toho dialogového okna (nejde ani rolovat) a nedostanu se ani na prvky formuláře, abych datum a čas odeslal / potvrdil a data se zapsala do položky. U velkých monitorů toto asi nebude dělat problém.
Zkus se na to Petře podívat. Označil jsem to jako bug z hlediska zobrazení na menších monitorech speciálně NTB.

**Comment by Sundin18** [comment]
ok. Tím, že se okno zvětšilo, tak to zmizelo. Můžu buď udělat roletku do toho okna, tím půjde vše zobrazit, ale u těch malých rozlišení bude potřeba tedy rolovat, aby šel vybrat datum. Nebo bych musel celý formulář udělat jako novou web stránku.

**Comment by Sundin18** [comment]
Posunul jsem okno trochu výše. Mrkněte, jestli to takhle stačilo nebo budu muset přidat to scrollování. Díky

**Comment by zachyunl** [comment]
Péťo prosím o změnu na verzi 19.09.00, máme nový měsíc.

**Comment by Sundin18** [comment]
Ju, už jsem si to u sebe přepsal, nechtěl jsem to zase kompilovat a nahrávat kvůli jednomu číslu. Teď už to mám připravený s novým.

**Comment by Sentinel65** [comment]
Vypadá to, že to nestačí Petře, tady máš sejmutou obrazovku z NTB. 
Udělal bych ten dialog jako nové okno.


![MU_formular](https://user-images.githubusercontent.com/54531291/64079090-6ffced00-cce3-11e9-9d00-9076e117b94a.png)

**Comment by Sundin18** [comment]
Tak už by se mělo dát posouvat stránkou, aby se zobrazily i tlačítka. Verze 19.09.1

**Comment by Sentinel65** [comment]
Fajn, toto je už ok. Požadavek možno uzavřít.
