### ISSUE TITLE
Internet Explorer - nezobrazení stránek

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#25]
Ahoj nejsem schopen vůbec stránky spustit přes Internet explorer. Zkouším to na 3 PC, všude je pouze IE 11 verze. Je vidět, že my 3 používáme jiné prohlížeče, ale musíme to odladit pro IE a Edge.
Testuji to ještě na Opeře, Firefoxu a Chromu. Jirka používá ještě nějaké minoritní browsery, ale tam nás to asi až tak netrápí i když se to na nich může také testovat.

**Comment by Sundin18** [comment]
V IE to fungovat nebude. Ten neumí nový  javascript. Myslím, ze vyvíjet pro explorer uz nemá význam. Poslední OS, které používalo explorer je XP? A to uz snad neni ani od MS aktualizovano. Edge už by měl být v pohodě.

**Comment by Sentinel65** [comment]
Testuji na:

Microsoft Edge v44.18362.267.0
Internet Explorer v 11.295.18362.0
Portable Mozilla Firefox Quantum v68.0.2
Portable Google Chrome v76.0.3809.100
Portable SRWare Iron v75.0.3900.0 open source na bázi Chrome
Portable PaleMoon v28.6.1 odnož Firefox

**Comment by Sentinel65** [comment]
Myslím že ne, Windows 10 mají Microsoft Edge, teď jdou zvěsti, že i ten chtějí opustit a vyvíjejí nový Microsoft Edge na základě Chromia
https://www.cnews.cz/microsoft-edge-chromium-integrace-internet-explorer-build-2019/

**Comment by zachyunl** [comment]
On IE umí Javascript, ale ve starší verzi než píšeš stránky. Něco jsem si k tomu pročetl a skutečně ho uvádějí jako nepodporovaný prohlížeč pro tento jazyk. Edge na tom chodí, už jsem si ho, alespoň rozeběhnul na compu.

Jirko piš problematiku pole hledat do správného threadu.
