### ISSUE TITLE
Filtry 2

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#26]
Ještě se vracím k těm filtrům, konkrétně ten prostřední "input" Filtrovat dle datumu.

Zkus tam Petře ještě doplnit na začátek filtr na 3 dny (00:00 hodin den první až do 06:00 hodin dne čtvrtého). Toto máme teď na ostrém šediváku a vychází to ze zavedené praxe, kdy se každé pondělí v 08:00 hodin koná konference operativního řízení provozu a probírají se závady a MU za uplynulý víkend s tím, že tento filtr by se měl projevit ve správném zobrazení čísel v sekci "**Druh mimořádné události**"

Mimochodem, když se na to teď dívám, tak ta čísla mi tam pořád nesouhlasí. Podle ID je záznamů 26, takže když vyberu všechny 3 oblasti, tak by součet těch hodnot v té sekci  "**Druh mimořádné události**" měl dát 26 a to mi nedává, je tam součet 23.

**Comment by Sundin18** [comment]
To číslo není pořadové číslo, ale ID číslo záznamu z DB. Např. mám záznam s číslem ID 5, když pak někdo napíše další záznam, tak se mu automaticky přiřadí číslo 6 atd. Když pak, ale třeba ten záznam č.5 vymažu, tak nebude ve výpisu, ale když přidám další záznam, tak bude mít stejně další číslo, které je na řadě, třeba 10. Takže uvidíš záznam, který bude mít číslo 10, ale záznamů bude 9, protože záznam č.5 byl vymazán.

**Comment by Sundin18** [comment]
Ten filtr umí filtrovat pouze po celých dnech. Od 0:00 hodin dne "od" do 23:59 dne "do". Takže buď jim v pondělí na konferenci nebude vadit, že se ve filtru objeví i záznamy mezi 6:00 až 8:00 toho pondělního dne nebo udělám třeba tlačítko (checkbox), které vyfiltruje přesně v tom časovém intervalu. Nebo by pak musely být zase dva inputy "od" a "do" a byly by i s výběrem času, jako je třeba při zakládání nové MU.

**Comment by Sundin18** [comment]
Trochu bojuju s tím názvem filtru "na 3 dny", protože se to liší od ostatní logiky, která filtruje vždy na celé dny od 00:00 do 23:59. Proto bych ten filtr nazval třeba "konference"?

**Comment by Sentinel65** [comment]
Petře na názvu až tak nezáleží, klidně to můžeš pojmenovat jako "Konference", důležité je aby to tam bylo od té půlnoci pátek až 6 hodina pondělí ráno.

**Comment by Sundin18** [comment]
Asi by bylo lepší defultně posledních 7 dní? Protože třeba tento týden by tam byl pouze dnešní den.

**Comment by zachyunl** [comment]
Máš pravdu Petře, posledních 7 dní je lepší.

**Comment by Sundin18** [comment]
Hotovo (Verze 19.09.4)

**Comment by Sentinel65** [comment]
OK
