### ISSUE TITLE
Dispečerské příkazy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#27]
Už jsem to někde psal, ale asi to zapadlo v tom množství.
Prosím doplnit, aby v **detailu DP** bylo dole vedle "jméno" - "datum a čas" - "**computer name**", odkud byl záznam pořízen.
Toto chce hlavně náměstek, aby bylo prokazatelné, kdo jmenovitě, v kolik hodin a z jakého pc pořídil DP.

**Comment by Sundin18** [comment]
Hotovo, verze (19.09.6)

**Comment by Sentinel65** [comment]
Mrkni na to ještě, teď nelze ukládat záznam "**Dispečerský příkaz se nepodařilo uložit**" ani při opravě ani při pořízení nového.

**Comment by Sundin18** [comment]
Opraveno, já nezměnil DB na serveru. Už by to mělo ukládat. (verze 19.08.7)

**Comment by Sentinel65** [comment]
OK opraveno zavírám, podobně se udělá ten formulář "**Vyjádření k provozní závadě**"
