### ISSUE TITLE
Závady a mimořádné události - formát stránky

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#28]
Tady jen na ukázku, co se může stát. Já mám ty položky Popis a Vlivy právě pod sebou, protože jím můžeš 100 x opakovat, aby mezi čárkami dělali mezery, ale když to pak namastí vše za sebe, dopadne to takto.

![A000](https://user-images.githubusercontent.com/54531291/64145330-abe59e80-ce18-11e9-9815-8296bdd5fcac.png)

**Comment by zachyunl** [comment]
Moc hezký 😄 . To musíme ošetřit systémově kódem. Kázeň uživatelů jinak nedocílíš než jasně danými pravidly v programu. Organizační opatření jsou pouze na papíře a vždy se najde někdo, kdo ulétne.

**Comment by Sundin18** [comment]
Opraveno (Verze 19.09.8)

**Comment by Sentinel65** [comment]
OK
