### ISSUE TITLE
Vyhledávání

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#29]
Ve vstupním poli **hledat**, když tam najedeš myší, tak se zobrazí implicitní tolltip nápověda. 
Tak prosím tě **smaž** ten text "**_Napiš hledané slovo._**" a napiš tam:

**Vyhledá textový řetězec v položkách: "Zapsal", "Dopravce", "Číslo DP", "Popis", Vlivy".**

**Comment by Sundin18** [comment]
Změněno, verze 19.09.9

**Comment by Sentinel65** [comment]
ok
