### ISSUE TITLE
Rozložení stránky úprava

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#3]
K těm DP ještě jedna připomínka. Když kliknu vpravo u záznamu DP na "Původní", tak se mi obsah zobrazí nikoliv ve frame vlevo a seznam záznamů DP zůstane vpravo jako je to u volby "Opravit", ale skočí tam nová stránka s těmi daty původního DP. Uživatel je pak nucen kliknout v prohlížeči na stránku zpět. Mrkni se na to a oprav to. Při té příležitosti mám ještě další připomínku ohledně rozložení - nahoře jak je Logo, menu (odkazy) a vpravo login, pod tím pak ten šedý pruh s označením vybrané volby menu, nešlo by aby tenhle vršek by statický frame a při rolování stránky kolečkem myši zůstal na místě a neroloval se s celou stránkou ?

**Comment by Sundin18** [comment]
Po domluvě přidáno tlačítko, které vrátí uživatele zpět na výpis DP. Logo s pruhem zafixováno při rolování. (Verze 19.08.1)

**Comment by Sentinel65** [comment]
Super, nechci prudit, zase je to jen kosmeticka uprava Petre, ale prohod prosim te v tom sedem pruhu strany s popisem verze a prihlaseni. Opet je to jen o designu, ale pokud mas prihlasovaci odkaz vpravo nahore a info o prihlasenem uzivateli je pak uplne vlevo, prijde mi to nelogicke. Takze inmfo o verzi soupnout vlevo a info o prihlasenem uzivateli vpravo. Jinak je to OK!
