### ISSUE TITLE
Registrace

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#30]
Petře ještě k té administraci:

1. to že to píše po registraci, že nemám oprávnění, to je samozřejmě OK, práva pak přidělí admin
2. ale při té registraci vyplníš formulář a klikneš na tlačítko **Registrovat** a tam se nic neděje, žádná reakce typu oznámení, že "Udaje o registraci se zpracovávají". Navíc ten formulář zůstane s těmi vyplněnými údaji, takže ten kdo se registruje netuší, jestli to má provést znovu :-) Také by se přidělením oprávnění o tomto nějak měl uživatel dozvědět, opět zasláním této informace na email zadaný v registraci. 
3. navíc bych tam přidal dvě věci, jednak aby si uživatel mohl heslo změnit, přes administraci, kde uvidí pochopitelně jen údaje o svém účtu, nic víc a pak aby si mohl nechat poslat vygenerované heslo na svůj mail zadaný v registraci.

**Comment by Sundin18** [comment]
Má to vypsat informaci o tom, že byl o registraci informován administrátor atd. Mrknu se proč ti to nevyskocilo.

**Comment by Sentinel65** [comment]
Tak máme možnost vyzkoušet to, co jsi napsal, ale mně se to po tom vynulování DB neukázalo.

Jak už jsem psal, potřebujeme ted vytvořit role pro kontrolu ze strany vedení. Bude to role POUZE na prohlížení. Tady je návrh.

To co bude následovat platí POUZE pro DP, ST a PZ !

Centrální analýza - tady by uživatel, který bude mít přidělenou tuto roli, měl mít po ověření uživatelského jména a hesla AUTOMATICKY přiděleny všechny 3 oblasti (Praha, Ustí, Přerov), aniž by je vybíral.
Kontrola CDP - podobné, u Prahy bude nastavena jen oblast Praha a Ustí, u Přerova jen Přerov.

Po kliknutí na odkaz **Příkazy a vyjádření** zobrazí se POUZE tabulka s výpisem dat, tzn. NIKOLIV formulář a přepínače radio buttony.
Nad tabulkou by byly filtry:
**číslo**
**typ** kombo s předvolbou Vše (implicitně), DP, ST, PZ
**filtrovat dle datumu** stejné jako ted
**vydal** stejné jako ted
**Všechny** (kombo rozšířené na všechna pracoviště PHA, UNL, PRE dle přidělené role)

Závady a mimořádnosti

Vzhledem k tomu, že uživatelé mají účet a přidělenou roli, tak jim v tomto pohledu **ODSTRANIT** tlačítka:

**Přidat záznam
Změnit záznam
Odstranit**

Ještě k té registraci, pokud by se ti povedlo za jméno a závorku s vypsanými rolemi (po přihlášení) přidat odkaz na editaci účtu, kde si dotyčný bude moci změnit heslo. U přihlašovacího dialogu pak dát odkaz na zaslání zapomenutého hesla, kde se objeví dialog s nutností napsání registrovaného emailu, na který přijde nově vygenerované heslo. Po registraci by se tam měla objevit ta hláška , co jsi psal a ideální by pak bylo na registrovanou adresu odeslat mail s informací ohledně přidělených rolí a odkazem na stránky webu .

Pak bychom oslovili pár dotčených, kteří tyto role budou mít, aby se zaregistrovali a vyzkoušeli, jak to funguje.

**Comment by zachyunl** [comment]
Jirko s tím resetem hesla neblázni, je to pro Petra zbytečná práce. Berte že toto přihlašování je provizórium. Finále by mělo být přihlášení přes doménové jméno. Tam přes formulář reset hesla je velká neznámá a to teď určitě řešit nebudeme. Ani nevím zda to jde přes tu metodu ověřování, kterou máme navrženou.

**Comment by Sentinel65** [comment]
Tak pokud to ověření přes doménu bude v dohledné době funkční, tak je pravda, že tohle je zbytečný.

**Comment by Sentinel65** [comment]
> Po kliknutí na odkaz **Příkazy a vyjádření** zobrazí se POUZE tabulka s výpisem dat, tzn. NIKOLIV formulář a přepínače radio buttony.

Nad tabulkou by byly filtry:
**číslo**
**typ** kombo s předvolbou Vše (implicitně), DP, ST, PZ
**filtrovat dle datumu** stejné jako ted
**vydal** stejné jako ted
**Všechny** (kombo rozšířené na všechna pracoviště PHA, UNL, PRE dle přidělené role)

Závady a mimořádnosti

Vzhledem k tomu, že uživatelé mají účet a přidělenou roli, tak jim v tomto pohledu ODSTRANIT tlačítka:

**Přidat záznam
Změnit záznam
Odstranit**

**Comment by Sundin18** [comment]
Když se přihlásíte jako vedoucí analýzy (va@szdc.cz, heslo stejné jako u ostatních), tak pod odkazem "příkazy a vyjádření" uvidíte tabulku všech příkazů. Verze 19.09.22

**Comment by Sentinel65** [comment]
Petře, super, takhle jsem si to představoval ...
Podívej se, prosím tě, ještě v té tabulce na záznamy  **#40, 24, 23, 22, 13, 12 (všechny jsou Analýza PRE)**, ta když u nich kliknu na tlačítko **Původní, tak tam nic není**, ale tlačítko tam je ... divné
A před chvilenkou jsem vytvořil 2x 43_ST_Analýza PRE_Analýza PRE#oprava a když kliknu na tlačítko **Původní, tak tam nic není,** to je nějaká chybka ...

**Comment by Sentinel65** [comment]
Jinak jsem si teď ještě všiml, že v tom **pohledu Detail** i **Původní** v tom výpisu **úplně chybí položka Příjemce**. To tam doplň do obou prosím tě.

**Comment by Sentinel65** [comment]
44_DP_PD1 UNL_PO Karlovy Vary#oprava  pod účtem va@szdc.cz opět nic nevidí, účet dunl@szdc.cz vidí

**Comment by Sentinel65** [comment]
45_ST_PD6 PHA_Analýza PHA#oprava   tak za PHA to v tom účtu va@szdc.cz je vidět.

**Comment by Sundin18** [comment]
Opraveno, do detailu DP přidán řádek "Přijemce". Verze 19.09.23

**Comment by Sundin18** [comment]
U DP původních před touto změnou je v poli "příjemce" null. To je tím, že se příjemce u opravených DP dosud neukládal. Od této změny, už tam příjemce vidět je.

**Comment by Sentinel65** [comment]
Ještě prosím tě přidej ten sloupec **Příjemce** do výpisu záznamů a dodělej tam filtr s kombem zatím jen u té tabulky, která se zobrazuje pro účet va@szdc.cz

**Comment by Sundin18** [comment]
hotovo, verze 19.09.24
