### ISSUE TITLE
Nový formulář Evidence aktivací SZO

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#31]
Ahoj, tak dneska po školení, poté co o tom hovořil pan ředitel,  jsem si uvědomil, že tam asi budeme muset udělat ještě jeden nový formulář a to na **evidenci aktivací SZO** (stupně zimní ochrany). 

Do tohoto formuláře zapisuje **pouze vedoucí dispečer** z každé oblasti a výpis tabulky je pak k dispizici na OŘ. Tady se nikam nic mailem neposílá, z formuláře se data ukládají do tabulky DB. Takže to je případně sekce na vstupní formulář a tabulku na prohlížení pouze pro uživatele **vedoucí dispečer**.

Tady je odkaz právě na tu část prohlížení:
http://www.oorp.szdc.cz/web/zov/view.php?volba=oblast&vyber=0&mesic=12&rok=2014

Ředitel mluvil o tom, že se tam chystají nějaké změny, ale podrobnosti ještě nevěděl, takže až zjistím, napíšu to sem.

 Tady je obrázek vstupního formuláře:

![SZO](https://user-images.githubusercontent.com/54531291/64589222-e618e800-d3a4-11e9-9dff-ecc5350bbbd9.png)

**Comment by Sentinel65** [comment]
Petře, tady se vracím k tomu **prvnímu příspěvku,** v pátek byla porada a včera jsem dostal informace, že se tady nic měnit zatím nebude. Takže je možné ten formulář na **evidenci aktivací SZO** (stupně zimní ochrany) začít tvořit.


Tady jsou ještě jednou odkazy (nejsem si jist, jestli se tam dostaneš): 

**Editace**
http://www.oorp.szdc.cz/web/zo/index.php?oblast=2

![zo_orp praha](https://user-images.githubusercontent.com/54531291/65596169-9f2b1500-df96-11e9-89ef-6411b24e0efe.png)

![zo_orp praha 2](https://user-images.githubusercontent.com/54531291/65596180-a520f600-df96-11e9-8661-98e344f6bdb0.png)

**Prohlížení:**
http://www.oorp.szdc.cz/web/zov/view.php?volba=oblast&vyber=0&mesic=12&rok=2014

![SZO](https://user-images.githubusercontent.com/54531291/64589222-e618e800-d3a4-11e9-9dff-ecc5350bbbd9.png)

A tady je export z databáze, po stažení přejmenuj na zo.sql

[zo.sql.txt](https://github.com/Sundin18/backend/files/3652104/zo.sql.txt)

**Comment by Sentinel65** [comment]
No a aby toho nebylo málo, tak když jsem jela včera s Přemkem autem domů, tak jsme o tom mluvili a přitom jsem přišel na to, že jsem zapomněl na ještě jeden formulář, který se používá a který tam musíme doplnit. 

Je to formulář  **Neprojeté trasy OŘ Praha**

Tady je odkaz 

http://www.oorp.szdc.cz/web/neprojete/pha/index.php

![NT_OR_PHA](https://user-images.githubusercontent.com/54531291/65596944-48bed600-df98-11e9-8c5a-8a1a622c5ad3.png)

Tady je export z databáze, po stažení přejmenuj na neprojete_pha.sql

[neprojete_pha.sql.txt](https://github.com/Sundin18/backend/files/3652148/neprojete_pha.sql.txt)

Tohle jsme používali v Plzni, Ústí a Praze. 
Plzeň zrušili, v Ustí se to jak jsem se díval a nevím proč už nepoužívá (ale Přemek to chce sjednotit, aby to dělali i v Ústí), no a v Praze se to používá každý den viz obrázek.

**Comment by Sentinel65** [comment]
Petře, můžeš zatím začít dělat na tomto formuláři, ty ten formulář Neprojeté trasy swe bude projednávat během příštího týdne, očekávám nějaký výstup nejdříve v úterý či ve středu.

**Comment by Sundin18** [comment]
Pole "Žádal" je jméno vedoucího dispečera?

**Comment by Sentinel65** [comment]
No to je otázka do pranice :D po těch letech 
Takhle teď jsem to probíral s Petrem Novotným a s kolegou v Přerově a ta pole **"Žádal"**, **"Vyhlásil"** a **"Zrušil"** jsou pole, kam se píší jména. 
**"Žádal"** - jméno výpravčího (nebo vedoucího, případně dozorčího směny v uzlové ŽST)
**"Vyhlásil"** a **"Zrušil"** - jméno pracovníka OŘ (většinou nehodová dozor či pohotovost)

Takže jestli ti jde o nějaký seznam jmen lidí, tak tam se nic dávat nebude. Jde o klasické input pole pro zapsání jména. Teď jen odhadnout délku - zkusil bych třeba 30 znaků.

**Comment by Sentinel65** [comment]
Tady si to můžeš vyzkoušet

http://www.oorp.szdc.cz/web/zo/index.php?oblast=4

**Comment by Sentinel65** [comment]
**Oprávnění pro čtení a zápis u role** vdpha@szdc.cz a vdpre@szdc.cz, **pouze pro čtení u role** dpha@szdc.cz, dunl@szdc.cz, dpre@szdc.cz, ccdppha@szdc.cz a ccdppre@szdc.cz

**Comment by Sundin18** [comment]
Takže hotovo zobrazování, ukládání. Jirko @Sentinel65  mrkni na to a řekni, co bys ještě chtěl doupravit. (Verze 19.10.17)
Dodělat ještě musím zobrazení pouze pro čtení pro vypsané role dispečerů a kontrolérů.

**Comment by Sentinel65** [comment]
Petře, zkoušel jsem to teď v rychlosti na tabletu, vyhlásit, zrušit a koukám, že to nespočetlo ty hodiny.  Mrkni na to, podívám se na to podrobněji tak za necelé 2 hodiny, až budu u pc.

**Comment by Sundin18** [comment]
To ještě nic nepočítá, tam nevím, co to má počítat.

**Comment by Sentinel65** [comment]
Počítat to má počet aktivací a počet hodin, které ty aktivace trvaly viz.  obrázek
Dodělej tam to počítání a ty role, aby to fungovalo podle toho, jak jsem psal ta oprávnění.

![_SZO_01](https://user-images.githubusercontent.com/54531291/66653182-bd9c3c00-ec37-11e9-99f3-1b95a585d10c.png)

**Comment by Sentinel65** [comment]
Tak další připomínka v tom formuláři při editaci a v tom přehledu:

- jako první řádek název Vyhlášení aktivace
- to okno klidně udělej o něco málo širší tak, aby na druhém řádku byly položky  OŘ ... PO ... ŽST-PO-úsek
- ve třetím řádku pak položky Datum žádosti, Žádal, Vyhlásil
- pak řádek mezera
- další řádek název Zrušení aktivace
- další řádek opět položky  OŘ, PO, ŽST-PO-úsek
- další řádek  pak položky Datum žádosti, Žádal, Zrušil

V přehledu **Sumář aktuálně evidovaných aktivací OŘ** pak doplnit a přejmenovat sloupce, aby tam bylo **Datum [V] - Žádal - Vyhlásil, Datum [Z] - Žádal - Zrušil**. Je to z toho důvodu, že může býtk lidně i delší prodleva, než dojde po žádosti k vyhlášení a může to mít vliv na plnění GVD

V přehledu **Sumář nepotvrzených (zamítnutých) žádostí o aktivaci OŘ** přejmenovat sloupce, aby tam bylo **Datum [V] - Žádal**

V přehledu **Sumář zrušených aktivací OŘ** přejmenovat sloupce, aby tam bylo  **Datum [V] - Žádal - Vyhlásil, Datum [Z] - Žádal - Zrušil**

![_SZO_03](https://user-images.githubusercontent.com/54531291/66656044-7fa21680-ec3d-11e9-8fe1-57d00019b4f1.png)

**Comment by Sundin18** [comment]
hotovo, verze 19.10.19. 
Ale nejsem si jist, jestli jsem dobře pochopil jaké datumy, v které tabulce mají být.

**Comment by zachyunl** [comment]
Při přidání záznamu, když si vyberu OŘ, tak by se měli nabídnout pouze příslušné PO. Je to tak Sentinel65? Všiml jsem si, že to nemáme ani u DP, ale tam to myslím v minulosti bylo?

**Comment by Sundin18** [comment]
U DP to bylo závislé na výběru pracoviště, ale pak se to na přání změnilo, aby se zobrazovaly  všechny PO a OŘ. 
U SZO je to nastavené podle oblastí. Praha, Přerov, Ústí

**Comment by Sentinel65** [comment]
Měla by tam být PO a OŘ dohromady v rámci daného CDP, u SZO je to dle oblastí

**Comment by Sentinel65** [comment]
Petře, formulář a přehled už je asi nyní, jak má být. Klucí se na to podívají, ale myslím, že to bude OK.

Ještě prosím tě dodělej ta oprávnění takto:

**Oprávnění pro čtení a zápis u role** vdpha@szdc.cz a vdpre@szdc.cz, **pouze pro čtení u role** dpha@szdc.cz, dunl@szdc.cz, dpre@szdc.cz, ccdppha@szdc.cz, ccdppre@szdc.cz a va@szdc.cz .

A pak už to bude ok.

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.20

**Comment by Sentinel65** [comment]
Petře OK, zavírám a můžeš přejít na tu 49 Tisk Příkazů

**Comment by Sentinel65** [comment]
Petře, jedna kosmetická ...

Šlo by ty sloupce [**OŘ**] - [**PO**] - [**ŽST, PO, úsek**] - [**Datum žádosti**] atd. ve **všech třech tabulkách srovnat pod sebe** ?
Bylo by to pak daleko přehlednější ...

**Comment by Sundin18** [comment]
hotovo, verze 19.10.26

**Comment by Sentinel65** [comment]
ok, super.

**Comment by Sentinel65** [comment]
Koukám, ty hodiny se tam počítají nějak divně ...


![_SZO_BUG](https://user-images.githubusercontent.com/54531291/67182442-7fdda700-f3df-11e9-846c-08898ab1f56d.png)

**Comment by Sentinel65** [comment]
Opraveno, ok
