### ISSUE TITLE
Dispečerské příkazy, Stanovisko k narušení GVD, Vyjádření k provozní závadě - mail

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#32]
Petře, prosím tě pro účely testování, zadej tam e-maily nás třech, abychom viděli a měli přehled o tom, jak chodí ty dispečeráky a provozní závady mailem a jaká je struktura zprávy v mailu.

**Comment by Sundin18** [comment]
Jj, teď ho skládám podle vzoru, co jsi tady dával jako obrázek. Napište mi ještě prosím vaše adresy, na které to mám posílat potom. Díky

**Comment by Sentinel65** [comment]
jirizachar@seznam.cz
sentinel.h@gmail.com
ZacharJ@szdc.cz
HorkyJ@szdc.cz

**Comment by Sentinel65** [comment]
Při tom testování jsem si te´d všiml, že u těch DP, ST PZ to do tabulky do sloupce Pracoviště zapisuje např. **UNL PD1 UNL** nebo **PRE PD2 PRE** atd. To je schválně ? Nestačilo by tam jen to co je v seznamu toho komba Pracoviště **PD1 PRE** ?

**Comment by Sundin18** [comment]
Ju to opravím.

**Comment by Sentinel65** [comment]
Petře, před chvílí jsem mluvil s Jirkou a vypadá to, že jsme se nepochopili a že jsem ti nedal úplně přesné zadání.

Ty tři výstupní sestavy:

**Dispečerské příkazy
Stanovisko k narušení GVD
Vyjádření k provozní závadě**

Obsah zůstane tak jak je, **ale rovnou by se to odesílalo jako příloha mailu ve formátu pdf**. K tomu pak případně jako druhá příloha ten doplnujicí obrázek nebo dokument, tak jak je ted.

**Comment by zachyunl** [comment]
Nechal bych text v těle zprávy, tak jako to je nyní a doplněk by bylo pdf vygenerované z těla zprávy jako příloha. Název pdf udělej Petře stejný, jako předmět v emailu, pokud to nebude nějaký problém.

**Comment by Sundin18** [comment]
:-)) ten právě není. Na locale mi to jde, ale jak to nahraju na server, tak nejde. Tak jsem zkusil poslat mail, jestli se nerozhodilo ještě něco jiného.

**Comment by Sundin18** [comment]
Tak už to chodí i s přílohou pdf (Verze 19.09.19)

**Comment by Sentinel65** [comment]
Ahoj, tak DP 30 už je korektní příloha PDF.

**Comment by Sentinel65** [comment]
Tak ještě to není úplně OK.
Stanovisko k narušení GVD 31, to vygenerovalo soubor, ale v názvu před PDF chybí tečka, takže se nedá otevřít. To samé u PZ ...
Petře, ještě když dám přílohu jinou, tak se odešle a dá se prohlédnout, ale generuje to samo nějaké názvy jako hatmatilku, nešlo by tam natvrdo dát nějaký název ??
A ted ještě pro Jirku k zamyšlení:
kouikal jsem se na tu zástupnou schránku s DP za CDP Praha a loni tam bylo necelých 400 dohromady, letos doposud cca 450 plus navíc asi 3200 stanovisek k narušení GVD ! A to nepočítám vůbec Přerov ! Tak mě jen napadlo, že to je docela velké množství těch PDF a co to udělá za rok, dva tři ... a opět v to nepočítám možné vkládání příloh do DP, i když to je zřídka kdy ...

**Comment by Sundin18** [comment]
Ju, já tu příponu .pdf zapomněl přidat, když se posílá DP s přílohou. Jinak to vytvořené PDF jako DP nikam neukládám, to je jen v příloze emailu.

**Comment by Sentinel65** [comment]
Aha, tak netušil jsem, jak to máš udělané, myslel jsem, že se to vygenerované PDF také ukládá jako ta příloha z formuláře.

Ten DP s číslem 30 byl v pořádku, tam byla příloha s příponou *.pdf a v mailu šla otevřít.
Ale pak jsi tam asi něco změnil a ted to do mailu ukládá přílohu s názvem, ve kterém je na konci názvu připojeno pdf, ale je to bez tečky, takže z toho je název souboru bez přípony a je to u všech DP, ST i PZ. Tak to pak oprav.

Pokud by šla ta příloha ve formuláři, kterou ukládáš a v DB je pak na ni odkaz, pojmenovat dle typu záznamu tj. například takto:

**P31ST_201909140854.png
P32PZ_201909140904.png
P33DP_201909141203.png**

Ted se tam generuje název té přílohy takto: **wmvumKJty3XJbqw81HWW6RA34JOAIcYAj9RTiwjg.png**, což může být podezřelé a nikomu to nic neřekne.

**Comment by Sundin18** [comment]
Opraveno, jména příloh pozměněna. Verze 19.09.19

**Comment by Sentinel65** [comment]
Vypadá to už ok, ještě otestuji

**Comment by Sentinel65** [comment]
Petře, 

tak jsem to ještě otestoval a jsou tam třeba už jen drobné opravy:

- v detailu uloženého záznamu **opravit název přílohy na stejný. který se ukládá do mailu**, ted tam je název **image_png**, což je špatně, tam asi měla být tečka místo podtržítka, tím pádem nesouhlasí ani typ souboru
- pokud si pamatuji, psal jsi, že tyto přílohy jsou ukládáné na server a jsou prolinkované v DB
- pak jsem si všiml, že když dáš opravu záznamu, v té opravě např. změníš přílohu, než byla v tom původním záznamu, tak když kliknu na tlačítko "**Původní**", tak **tam odkaz na přílohu v původním uloženém záznamu vůbec není**.
- obecně by mělo platit, jak jsi už nastavil, že název přílohy bude odvozen od čísla DP, ST nebo PZ s tím, že na začátku je P jako Příloha a za podtržítkem je datum a čas uložení záznamu /opravy/

-

**Comment by zachyunl** [comment]
> A ted ještě pro Jirku k zamyšlení:
> koukal jsem se na tu zástupnou schránku s DP za CDP Praha a loni tam bylo necelých 400 dohromady, letos doposud cca 450 plus navíc asi 3200 stanovisek k narušení GVD ! A to nepočítám vůbec Přerov ! Tak mě jen napadlo, že to je docela velké množství těch PDF a co to udělá za rok, dva tři ... a opět v to nepočítám možné vkládání příloh do DP, i když to je zřídka kdy ...

Ahoj určitě to bude na podrobnější zamyšlení. Moje první otázka je, potřebujeme to vůbec uchovávat po novu v zástupné schránce, když bude možné vše vytahat z databáze? Na to navazuje otázka případně jak dlouho to chceme v zástupné schránce uchovávat? Kdo všechno dnes pracuje se zmiňovanou zástupnou schránkou (funkce, pozice a jak často)? Jak hluboko do historie se využívají data? Koukal jsem, že nově má to pdf cirka půl mega, čili 5000 zpráv s přílohou po novu v zástupné schránce.
Ještě se můžeme zamyslet nad generováním zpráv s pdf jenom pro určité uživatele a zbytek uživatelů by měl pouze zprávu v těle emailu. Na to navazuje otázka, zda to má cenu vůbec takto selektovat?

**Comment by Sentinel65** [comment]
No pokud vymyslíme jiný typ distribuce, tak ne. V tuto chvíli slouží zástupné schránky pro distribuci DP na OJ, dle pravidel jsou automaticky přeposílány jednak na sekretariáty, pak ale i na vyjmenované jednotlivce OJ.
Moje původní myšlenka byla taková, že na OJ přijde DP v tom formátu jako doposud v mailu s případnou přílohou, kde by byl link na záznam v DB, kam by OJ mohla napsat odpověď. Ale praxe je taková, že odpověď z OJ jde cestou oficiálního dokumentu s číslem jednacím na mail analýzy CDP, která si pak odpověď páruje s příslušným DP. Zatím mě jiný způsob nenapadá.

**Comment by zachyunl** [comment]
Tady si možná nerozumíme. Já se spíše ptám, potřebujeme vůbec uchovávat v historii zástupné schránky nějaké dokumenty, když to je jenom takový "průtokový" distributor zpráv a vše bude v databázi? Pokud jde odpověď oficiální cestou, tak bych nerad nahrazoval ERMS, které je k tomu určeno. Neříkám že se mi nápad s odkazem na odpověď nelíbí dělat přes aplikaci, je to určitě zajímavá myšlenka, ale to by se muselo zase probrat s vedením a vydalo by se to jako oficiální status.

**Comment by Sentinel65** [comment]
Ty zástupné schránky byly zřízeny právě pro komunikaci OJ s analýzou na CDP. Ty odpovědi z OJ jim tam stejně budou chodit. 
Myšlenka využít tu DB i na komunikaci s OJ je sice hezká, ale to už ten systém začínáme rozšiřovat více a dále, než bylo původně zamýšleno a bojím se, abychom se nezasekli na dalším vymýšlení řešení a rozšiřování přístupů napříč celou SŽDC, a to nepočítám dopravce. To je věc nového projektu Jirko. To, že tam teď navíc generujeme i soubor PDF, je spíše malý bonus.
Do DB, jak Petr uvedl, se ukládá soubor příloh, ale vygenerovaný soubor PDF je jen přílohou mailu.
Nemám ambice, aby tato upravená verze nahrazovala velký projekt.

Dostali jsme se teď do fáze, kdy by bylo třeba vytvořit nové role pro kontrolu (CDP PHA, CDP PŘE, centrální AJŘ) a přizpůsobit jim souhrnný výpis DB s různými možnostmi filtrování dat a vyhledávání. Mluvím pořád o DP, ST a PZ. Tohle je teď dle mého priorita, abychom jim mohli něco odprezentovat. Na základě toho by pak oni mohli začít dělat úpravy na dokumentaci, kterou bude třeba mít hotovou do začátku grafikonu, předpis D7 apod.

**Comment by zachyunl** [comment]
> _Ty zástupné schránky byly zřízeny právě pro komunikaci OJ s analýzou na CDP. Ty odpovědi z OJ jim tam stejně budou chodit._
A dneska to tam chodí vše? Takže obava je, že to bude bobnat díky pdf přílohám? Nechodí to oficiálně přes ERMS?

> _Myšlenka využít tu DB i na komunikaci s OJ je sice hezká, ale to už ten systém začínáme rozšiřovat více a dále, než bylo původně zamýšleno a bojím se, abychom se nezasekli na dalším vymýšlení řešení a rozšiřování přístupů napříč celou SŽDC, a to nepočítám dopravce. To je věc nového projektu Jirko. To, že tam teď navíc generujeme i soubor PDF, je spíše malý bonus._
Právě si začínám čím dál více pohrávat s myšlenkou udělat to naše jako základ pro velký projekt. Mám obavy, že až to jednou někdo vypíše a vyhraje nějaká firma, která o železnici ví jenom, že vlaky jezdí po kolejích a nic více, tak z toho bude nicneříkající SW a všichni budou jenom nadávat. Máme něco nového k velkému projektu, nebo to je zatím jenom ten myšlenkový draft od Pavla a od Petra Řádka mix myšlenek všeho možného dohromady? Docela mi chybí podrobná analýza prostředí v současném stavu a v budoucím stavu po dokončení velkého projektu a hlavně detailní cíl.

> _Do DB, jak Petr uvedl, se ukládá soubor příloh, ale vygenerovaný soubor PDF je jen přílohou mailu.
> Nemám ambice, aby tato upravená verze nahrazovala velký projekt._
Velký projekt má řešit i dispečerské příkazy, stanovisko ke GVD a vyjádření k provozní závadě?
> 
> _Dostali jsme se teď do fáze, kdy by bylo třeba vytvořit nové role pro kontrolu (CDP PHA, CDP PŘE, centrální AJŘ) a přizpůsobit jim souhrnný výpis DB s různými možnostmi filtrování dat a vyhledávání. Mluvím pořád o DP, ST a PZ. Tohle je teď dle mého priorita, abychom jim mohli něco odprezentovat. Na základě toho by pak oni mohli začít dělat úpravy na dokumentaci, kterou bude třeba mít hotovou do začátku grafikonu, předpis D7 apod._
Proti tomu nic nemám, určitě dobrý nápad.

**Comment by Sentinel65** [comment]
Máme termín do prosince, víš jak to chodí s analýzami všeho typu na dráze, jak všechno hrozně dlouho trvá a kolik lidí se k tomu bude mít potřebu vyjádřit.
Proto se držím při zemi a rád bych toto dodělal do grafikonu.
Jak to dál rozšiřovat se můžeme klidně pobavit po novém roce, až tohle poběží.
Ty PDF přílohy sis prosadil ty na základě požadavku Přemka, myslím že v dnešní době si to umí do požadovaného formátu uložit každý sám. Takže ne není obava z bobtnání, ale že se poženeme za nějakou vizí, kterou jsme ani neměli původně v plánu a zaseknem se jednak na technickém řešení a jednak na tom, že poradně není zmapován žádný požadavek, jak by to mělo do budoucna vypadat a s čím vším by to nakonec mělo umět komunikovat a spolupracovat. Velký projekt měl krom jiného řešit i “šedivák”, ale už teď je vidět přesah a určitá provázanost s dispečerskými  příkazy. A když už se předělává, tak myšlenka byla dát ty DP, ST a PZ k tmu, aby to bylo v jednom. Udělat to co nejrychleji, přejít  ze starého na nový a pomoci tak lidem. 

Vymyslet něco úplně nového je určitě dobré, al chce to podstatně více času a mít zmapované a vydiskutované požadavky se všemi stranami. Uvědom si,  že to Petr dělá ve svém volném čase, to co ty navrhuješ obnáší práci týmu na plný úvazek .

**Comment by zachyunl** [comment]
Termín do prosince není striktně dán, to je jenom zatím pracovní návrh. Původně jsme měli datum ke grafikonu, ale nakonec po diskuzi s Přemkem jsme se od toho odklonili. Nyní máme kvůli změně číslování DP a dalších věcí termín 1 v nějakém měsíci. Prosinec se jeví jako nejvhodnější, pokud to bude 1.1., tak se taky svět nezboří. Když to uděláme a překlopíme dříve, tak je to také jedna z variant.
Ve volným čase to děláme všichni a taky se podařilo dostat za to alespoň nějaké prémie. Budu se snažit, aby to nebyla poslední částka. Je to také jeden z důvodů proč jsem začal poctivě evidovat Changelog, ať je něco k předložení. Petr bude psát odhad hodin kolik na tom stráví a my od toho odvodíme i náš čas.
Na jednu stranu vidíš ten přesah šediváka do DP a dále, nevěřím tomu, že by toto postihla nějaká analýza, kterou bude někdo matlat neznalý detailní problematiky práce dispečerů a analýzi. Proto se zaobírám myšlenkou tak jak jsem to popsal výše v příspěvcích. Jinak ten nápad s odkazem z DP a zápisem odpovědi rovnou do DB jsi navrhl Ty :smiley:, mně se to líbilo jako fajn řešení. Ale toto se může udělat později. Petr tam má celkově ještě také pár myšlenek, které se mi líbili. Můžeme stanovit nějaký detailnější plán co dotáhneme do konce a zbytek se nechá na řešení až někdy po spuštění.

**Comment by Sundin18** [comment]
Přílohy se tedy ukládají na server jako např. 38DP_20190915193631.png. Je tam tedy i vteřinový údaj, aby se nestalo, že by došlo k přepsání jednoho souboru, v případě, že by dotyčný dělal opravu a stihl by ji udělat ve stejné minutě.
V původních DP už je odkaz na přílohu, pokud ji DP má.
Verze 19.09.20

**Comment by Sundin18** [comment]
V této sekci už chybí jen jediný bod a to je ošetření přílohy (velikost, typ), jinak si myslím, že by DP měly být hotové. Samozřejmě ještě pak testovat a testovat.

**Comment by Sentinel65** [comment]
Jirka se k tomu, co jsem psal zatím nevyjádřil, tzn. soubory typu png, jpg a pdf a velikost max 5MB.

Jinak jsem to zkusil Petře a v tom původním záznamu tam tu  přílohu rtesp. odkaz na ni nevidím viz obrázky:

DP38_opravený s odkazem na přílohu
![DP38_opraveny s prilohou](https://user-images.githubusercontent.com/54531291/64925600-80d55480-d7f3-11e9-8d38-1ac0a945f7e7.png)

DP38_původní, kde by měl být odkaz na přílohu, ale nevidím ho
![DP38_puvodni_prilohu_nevidim](https://user-images.githubusercontent.com/54531291/64925607-9b0f3280-d7f3-11e9-865e-47d377f2a13b.png)

No a tady o čem jsem psal před tím, ale nebyl jsem asi pochopen :-) když kliknu v detailu na odkaz ke stažení přílohy, tak se mi tam objeví image_png ke stažení, místo aby se mi stáhnul soubor PDP38_2019....png
![DP38_ulozeni_z_odkazu](https://user-images.githubusercontent.com/54531291/64925617-b4b07a00-d7f3-11e9-88da-e00da9c81ce8.png)

**Comment by zachyunl** [comment]
Sorry to mi uteklo, souhlas 5Mb a typy příloh jpg, png a pdf.

**Comment by Sentinel65** [comment]
A koukám, že už se ti povedlo opravit i ten návrat z pohledu Původního záznamu, že to zůstane na vybraném radio buttonu, které jsou ted pro lepší přehled podbarveny žlutě /aktuálně vybraný/. Super
Jirka se vyjádřil, tak to nastav a já to zavírám ...

**Comment by Sundin18** [comment]
Tak je tam nastavena i validace na tu přílohu. Nelze nahrát jiné soubory než s příponou jpg, jpeg, png, pdf a velikostí menší než 5 MB. (Verze 19.09.21)
