### ISSUE TITLE
Test přílohy v DP, ST, PZ

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#33]
Ted jsem zkoušel otestovat typ přílohy v DP, ST a PZ a prošel mi soubor **P41ST_20190916094730** s **příponou log**

To samé u 23ST, příloha **P23ST_20190916095446** s **příponou ppt**
To samé u 24DP, příloha **P24DP_20190916100150** s **příponou exe**

Co zafungovalo, tak to **hodilo chybovou hlášku u souboru s příponou mp3 o velikosti 32 MB**
**Obrázek s příponou jpg větší než 5 MB** to sice na oko vzalo, formulář nahlásil, že záznam uložil, ale **soubor s přílohou typu jpg** se neobjevil ani v detailu, ani v mailu.
**Soubor pdf o velikosti 7 MB** to sice na oko vzalo, formulář nahlásil, že záznam uložil, ale **soubor s přílohou typu pdf** se neobjevil ani v detailu, ani v mailu.
Takže to vypadá, že test na velikost souboru funguje tak nějak na půl, ale u přípony ne.

**Comment by Sundin18** [comment]
Jirko @Sentinel65 , testuješ nejnovější verzi? Dej raději obnovit prohlížeč. Já to teď vyzkoušel a funguje mi to. Že testuješ starší verzi by odpovídalo i to s tou velikostí, protože ta je nastavená i na straně php. To je pak i na druhého Jirku @zachyunl, protože v php.ini bývá implicitně nastavená velikost 2MB, tak by to tam asi chtělo změnit na těch 5MB. Teď mě napadlo kouknout na info.php a tam je pak ta proměnná napsaná. Tuším jako max_file_size.

**Comment by Sentinel65** [comment]
Koukám, že ted tam mám  21, ale předtím ?? :-) ještě znovu vyzkouším

**Comment by Sentinel65** [comment]
Aha, tak pravda asi jsem tam měl před tím verzi 20, po refresh stránky je verze 21 a už to tam okamžitě hlásí, že se neshoduje přípona nebo je překročena velikost. Chjo tak se omlouvám

**Comment by Sundin18** [comment]
Tak je tam opravdu upload_max_filesize ty 2MB. V php.ini se to dá přepsat na těch našich 5MB.

**Comment by Sentinel65** [comment]
jj dej to na těch 5MB, ono záleží jakým způsobem kdo udělá screenshot obrazovky a v čem ...

**Comment by Sentinel65** [comment]
Zachy tak se mrkni na ten **php.ini** soubor a **uprav tu položku upload_max_filesize na 5 MB**

**Comment by zachyunl** [comment]
Jirko zkus uložit soubro větší než 2MB. Změnil jsem hodnotu na max 5 MB.

**Comment by Sentinel65** [comment]
Tak 7 MB to nevezme, 3MB jo...

**Comment by zachyunl** [comment]
Petře ty přílohy co se týče přípustnosti na ukládání máš dělané na straně apache, nebo to je kódem v php?

**Comment by Sundin18** [comment]
Je to ošetřené na straně klienta. Ale chci i v php.
