### ISSUE TITLE
Kosmetické úpravy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#34]
Sem budeme psát kosmetické úpravy, které mají Prioritu 5, ale aby se na ně nezapomnělo:

- ve všech filtrech (Závady a mimořádné události, Příkazy a vyjádření) pokud to půjde nějak **barevně nastavit** / podbarvit kombo, input /, že je **filtr aktivní**
- ve všech filtrech (Závady a mimořádné události, Příkazy a vyjádření) sesouladit text (první písmeno velké - někde je, někde není)
- Závady a mimořádné události v sekci **Stav** přejmenovat radio button z _Neukoncčené_ na **Závada trvá** (HOTOVO)

**Comment by Sentinel65** [comment]
Dám to sem, uvidíme kdy se k tomu dostaneš ....
Jak tam narůstá počet záznamů, tak čím dál tím víc cítím potřebu ještě jedné změny v ZMU.
Zkus tam ještě upravit ty **FRAMY** tak, aby se docílilo **POUZE rolování těch samotných záznamů**, ale tlačítko Přidat záznam, komba a inputy na filtrování a ty sekce vpravo Stav, Oblast a Druh mimořádní události **zůstalo statické na pevno** , jestli mi rozumíš.

Když např. budu označovat záznamy k tisku, tak mi zmizí ta horní tlačítka (v tomto případě Vytvořit PDF) a musím se vracet zase zpět nahoru.

**Comment by Sundin18** [comment]
Vytvořen odkaz na DP v záznamu MU. Verze 19.09.34

**Comment by Sentinel65** [comment]
Odkaz na DP super.

Ještě jedna kosmetika ... u některých záznamů jsou ráměčky kolem dokola, u některých jen po straně. 
**Navrhuji ty rámečky zrušit uplně**. A ještě kdyby jsi tam u toho ID čisla v pravém horním rohu záznamu mohl udělat 1 - 2 pixely mezeru od pravého okraje, jako je u toho checkboxu pro tisk v levém horním rohu.

![_Ramecky](https://user-images.githubusercontent.com/54531291/65936137-d9276b80-e41b-11e9-9b38-6210a937443a.png)

**Comment by Sundin18** [comment]
ok. Jsou to někdy záhady, protože já u sebe vidím rámečky v pořádku. Ale zruším je.

**Comment by Sundin18** [comment]
hotovo, verze 19.10.0
