### ISSUE TITLE
Závady a mimořádné události - prohlížeč

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#35]
Uplnou náhodou jsem narazil na následujicí problém, zkuste to vyzkoušet dle popisu u vás pod různými prohlížeči. Je možné, že na počítaci s připojeným velkým monitorem se to neprojeví (nebude vidět vpravo rolovátko), zkuste na samotném NTB bez monitoru.

Jednak se mi nedaří načíst tyto stránky (http://10.99.164.36/web/oorp/oorp-production/) vůbec v IE 11 viz. obrázek

![IE_11](https://user-images.githubusercontent.com/54531291/65319953-1b8db480-dba1-11e9-8922-c54ea824a0b4.png)

Dále při určitém úkonu dochází k zacyklování stránky:

- spustím http://10.99.164.36/web/oorp/oorp-production/
- zruším filtr datumu
- v sekci **Stav** vyberu raido button **Zastavený provoz**
- protože tam je ted jeden záznam, ale u menšího monitoru na NTB mám stále vpravo rolovátko, tak bud s ním popojedu dolů nebo kliknu myší mimo ty radio buttony a stisknu tlačítko se šipkou dolů a zacyklí se mi stránka viz obrázek. Nelze nic jiného než dát refresh stránky. Zkoušel jsem to v Microsoft Edge, Firefoxu, Chrome, všude stejné.

![WEB_error](https://user-images.githubusercontent.com/54531291/65320562-6eb43700-dba2-11e9-879c-f47adbf3e98f.png)

**Zkouším to i s jinými nastaveními - zrušen filtr datum, nastaven filtr Ustí nad Labem, Neukončené (těch je 7), sjedu dolů a opět se to cyklí.
Přijde mi, že to nějak souvisi s tím, jak tam Petr má nějakou funkcionalitu, že se po dorolování na konec stránky načítají další záznamy. Ale pokud mám filtr, který mi ukazuje nějaký omezený konkrétní počet záznamů, který ani nezabere celou stránku, tak by tam k žádným pokusům o načtení dalších záznamů na stránku nemělo docházet.**

**Comment by Sundin18** [comment]
Opraveno, verze 19.09.25

**Comment by zachyunl** [comment]
Petře mohl bys tam udělat na úvodní stránce test na prohlížeč a pokud tam bude nepodporovaný jako např. IE, tak vyhodit hlášku na uživatele, že "Tento prohlížeč není podporován, použijte prosím Chrome, Firefox, Edge, Operu, Safari či jiný alternativní prohlížeč, který podporuje nejnovější technologie Javascriptu"? Případně ten poupravte.

**Comment by Sentinel65** [comment]
Ten bug byl odstraněn, udělej tam prosím tě ten test na IE, tohle issue zavírám
