### ISSUE TITLE
Závady a mimořádné události - doplnění

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#36]
Máme tady první ohlasy  na  "Šedivák".

- dostal jsem žádost na _předvyplnění položky_ **Dopravce** nejčastěji používanými dopravci (klasicky kombo se seznamem) s tím, že **pokud by bylo potřeba vyplnit jiného dopravce, který v seznamu není**, bylo by to možné prostou editací do vstupního pole - **půjde toto Petře nějak udělat** ??

Seznam dopravců (předpokládám, pokud bychom to zrealizovali, že Přerov nám dodá ješty ty své na Moravě, které často používá a v seznamu je nemáme):

ARRIVA vlaky
AWT
BF Logitics
Cargo Motion
CZ Logistics
ČD Cargo
ČD a.s.
EŽ Praha
GJW Praha
GWTR
IDS Cargo
JHMD
KŽC Doprava
Leo Express
LTE cz
Metrans rail
Regio Jet
Unipetrol

**Comment by Sundin18** [comment]
Kdysi jsem něco podobného dělal, je to složitější. Snad to někde najdu.

**Comment by Sundin18** [comment]
Hotovo, verze 19.09.30

**Comment by zachyunl** [comment]
K tomuto mám dotaz, z čeho je brán ten seznam dopravců? To je něco oficiálního? Našel jsem na stránkách SŽDC oficiální seznam obchodních názvů dopravců, ale samozřejmě že existují třeba nějaké provozní názvy. Např. JHMD neexistuje a oficiálně to jsou Jindřichohradecké místní dráhy, a.s. Ještě se chci podívat jak jsou tyto názvy např. v ISOŘi a jiných provozních systémech. Přesně to je ten důvod proč nechci pouštět běžným uživatelům doplňování dopravců, protože to nebude odpovídat správné konvenci a v budoucnu to bude dělat problémy pro statistiky, hledání apod.

**Comment by Sundin18** [comment]
To jsem jen zkopíroval z toho, co jsi tu napsal.

**Comment by zachyunl** [comment]
On je to primárně dotaz na Jirku.

**Comment by Sentinel65** [comment]
Je to brané ze seznamu na portálu provozování dráhy, ty názvy jsou přesně z toho seznamu, takže by to mělo být dobře .

**Comment by zachyunl** [comment]
Jirko nechci být detailista, ale už toto přesně ukazuje, že musíme brát jako základ jednotný číselník pro, který bude šiřší shoda. ARRIVA vlaky je co, to tady nevidím? Je tu buď ARRIVA jako zkratka nebo 
ARRIVA  vlaky s.r.o. Přesně takto to zobrazuje i CDS, primárně bere jako základ zkratku dopravce a v závorce je uveden celý jeho obchodní název.
No a do toho hned dáš zkratku AWT? Tam si vůbec nejsem jist jak to má být, protože CDS nám zobrazuje odchylku od číselníku a je tam nějaké AWT_CD. To je někam na konzultaci.
Pak napíšeš ČD a.s.? To je složenina zkratky a obchodního názvu dohromady?
Metrans Rail je co? To je useknutý obchodní název? Ale zkratku má METR Rail. Ale do toho ještě máš jiného dopravce, který má zkratku METRANS a obchodní název METRANS, a.s.
A teď mi řekni pro představu, když to takto necháme, tak co tam asi dispečeři namastějí, když bude MÚ u jednoho z těchto Metransů? Buď budou mastit oba dopravce pod jedno pole, což je blbě. Nebo si tam budou chtít udělat nově dopravce a to nechci vidět jakou tomu dají zkratku nebo obchodní název. 
A takto bych mohl rozebrat všechny dopravce. Vezmi si, že v budoucnu bude určitě někdo filtrovat i data dle položky dopravce a pokud to bude nejednoznačné, jako to máme nyní uděláno, tak je to další potencionální problém.
--

**Comment by Sentinel65** [comment]
Tady je originál seznam dopravců přímo ze zdroje tj. z Portálu provozování dráhy v excelu a csv.
Zkus tam Petře naimportovat ten sloupec se zkratkou, ten celý název si myslím bude v některých případech hodně dlouhý.

[Seznam_dopravcu_SZDC_02092019.csv.txt](https://github.com/Sundin18/backend/files/3668842/Seznam_dopravcu_SZDC_02092019.csv.txt)

[Seznam dopravců.xls.txt](https://github.com/Sundin18/backend/files/3668843/Seznam.dopravcu.xls.txt)

**Comment by Sundin18** [comment]
A má  to tedy být i s tím, že pořád bude možné dopsat dopravce do toho pole nebo jen kombo s těmito předvyplněnými dopravci?

**Comment by zachyunl** [comment]
Petře umíš udělat, že v základu by se nabídlo jenom pár dopravců těch původních co posílal Jirka a na základě nějaké interakce od uživatele by se nabídli všichni? Poté by nebyla potřeba něco vypisovat ručně. Jenom se ještě musí vymyslet ruční doplnění seznamu pro admina.

**Comment by Sentinel65** [comment]
V aplikaci ISOŘ ŘV má Oltis udělané, že v kombu je seznam stanic a přes klávesovou zkratku se nabízí ten seznam buď plný nebo nějak upravený (v našem případě třeba nejčastěji používaný dopravce). Pokud by to šlo udělt takto, tak by pak nebylo třeba nic doplňovat ...

**Comment by Sundin18** [comment]
Já tam zatím nechám všechny dopravce. Dokud není dotvořena admin sekce, tak se to dá zatím aktualizovat v DB v tabulce.

**Comment by Sentinel65** [comment]
OK a ještě se zeptám na jednu důležitou věc, lze aby tam nějak fungovalo v tom kombu a rolovacím seznamu vyhledávání podle řetězce ? Rozkliknu kombo a zadám první dva tři znaky a v seznamu mi to najde prvního dopravce, který toto splňuje.

**Comment by Sundin18** [comment]
hotovo verze 19.09.31

**Comment by Sentinel65** [comment]
Ve verzi 19.09.31 už je to OK
