### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#37]
Bylo by možné na na číslo verze vlevo v pruhu zavěsit jako odkaz changelog, kde by bylo ve zkratce popsáno jaké nové funkce jsou zprovozněny, případně co bylo opraveno  ?

**Comment by Sundin18** [comment]
hotovo, verze 19.10.0

**Comment by Sentinel65** [comment]
Prosím tě Petře, obrať tam to řazení, poslední verze aby byla nahoře. Díky

**Comment by zachyunl** [comment]
To musím přehodit já ve zdrojáku. Dneska při aktualizaci.

**Comment by Sentinel65** [comment]
OK, rozumím

**Comment by Sundin18** [comment]
hotovo, verze 19.10.01
