### ISSUE TITLE
Připomínky od uživatelů

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#38]
- v ZMU ve změně přejmenovat položku Pokyn k PP vydal na Pokyn k OP vydal (OP = obnovení provozu - zažitý termín u provozních a VD)
- v ZMU tlačítko Odstranit přejmenovat na Skrýt (jako Skrýt záznam nikoliv ho smazat, odstranit, záznam zůstává v DB, ale PD, VD ho pořídí omylem)
- v ZMU v položce Číslo DP k datům ze sloupce Číslo připojit i sloupec Typ tak, aby se pro lepší orientaci vedle čísla zobrazil i jakého typu se to týká. V kombu by se tedy např. objevilo 39 PZ.
- v Příkazy a vyjádření do přehledové tabulky doplnit tlačítko Zrušit, které by opětovně použilo stejné číslo (v podstatě stejná data jako při uložení) a na uvedené adresy v záznamu automaticky odeslalo předdefinovaný text příklad "Ruším DP_5_PD1 PHA_PO Kolín z důvodu zaslání omylem" a záznam by zůstal v přehledu, ale text by zčervenal a tlačítka by se stala disabled (tady bude nutno ještě oslovit Analýzu na upřesnění toho textu)
- v Příkazy a vyjádření ve formuláři dochází při zvolení opravy záznamu k načtení dat, ale pokud v tu chvíli skočím do jiného pohledu (ST, PZ), nelze zrušit editaci opravy, tzn. vybráním jiného pohledu (DP, ST, PZ) by mělo dojít ke kompletnímu refresh formuláře, aby byl čistý. Laicky nelze zrušit opravu zvoleného záznamu, kdy se načtou data.
- analýza by se měla vyjádřit k formuláři Neprojeté trasy za CDP Praha, zda to bude nutné opisovat (přepisovat) do ZMU, nebo vzhledem k tomu, že na to budou mít práva AJŘ na CDP i centrální, to nechájí jen v tom přehledu
- v Přerově už měly námitky na velikost a barvu fontu u menu ZMU a Příkazy a vyjádření a pod., možná by nebylo od věci to udělat s podbarvením jako jsou tlačitka Přidat záznam nebo Vybrat vše - to by i barevně ladilo.

**Comment by Sundin18** [comment]
- hotovo (verze 19.10.01)
- hotovo (verze 19.10.01)
- hotovo (verze 19.10.01)
- v další verzi
- to je úmyslně, kdyby chtěli opravit např. omylem vydaní DP a poslat ho jako ST. Ke zrušení opravy, je v horní části formuláře na žlutém podkladu text "zrušit opravu" a tím dojde k vymazání dat z formuláře.
- mám tedy začít dělat tedy odřeknuté trasy?
- v další verzi

**Comment by Sentinel65** [comment]
Jo jo začni dělat na těch  Neprojetých trasách. Oprávnění ti ještě upřesním, v Praze to dělají PD, v Ústí to původně asi dělali VD, musím domluvit s Přemkem, jak to chce. Přerov to neuvidí vůbec, nedělají to.

**Comment by Sentinel65** [comment]
> v Příkazy a vyjádření ve formuláři dochází při zvolení opravy záznamu k načtení dat, ale pokud v tu chvíli skočím do jiného pohledu (ST, PZ), nelze zrušit editaci opravy, tzn. vybráním jiného pohledu (DP, ST, PZ) by mělo dojít ke kompletnímu refresh formuláře, aby byl čistý. Laicky nelze zrušit opravu zvoleného záznamu, kdy se načtou data
> to je úmyslně, kdyby chtěli opravit např. omylem vydaní DP a poslat ho jako ST. Ke zrušení opravy, je v horní části formuláře na žlutém podkladu text "zrušit opravu" a tím dojde k vymazání dat z formuláře

OK, ale nevím jestli už jedu moc mechanicky, ale toho jsem si opravdu nevšiml a to jsme u toho seděli dva :-) Z toho důvodu to chce jakékoli odkazy na kliknutí prostě dělat tak, aby byly dobře viditelné a uživatel je bez problémů zaregistroval. Můžeš tedy ten **odkaz (zrušit opravu)** upravit, aby tam byl **tmavě šedý podklad a bílé písmo**, jako je to u ZMU tlačítka **Vybrat vše** ?

**Comment by zachyunl** [comment]
> * v ZMU v položce Číslo DP k datům ze sloupce Číslo připojit i sloupec Typ tak, aby se pro lepší orientaci vedle čísla zobrazil i jakého typu se to týká. V kombu by se tedy např. objevilo 39 PZ.

Nebylo by zde vhodnější přejmenování popisu z "Disp. příkaz" na "Příkazy a vyjádření", ať je to stejné jako v menu?

**Comment by Sentinel65** [comment]
No vhodné by to bylo, ale bojím se, že to už je dost dlouhé. Spíše bych to upravil v menu i tady na prosté Příkazy

**Comment by zachyunl** [comment]
Petře prosím otestuj změnu s oběma návrhy a porovnej co bude lepší na zobrazení. Případně uprav i menu. Primární je zobrazení pro velké monitory na dispečinku.

**Comment by Sundin18** [comment]
hotovo, verze 19.10.03

**Comment by Sentinel65** [comment]
Petře, prosím tě ještě u těch zrušených jsem zapomněl, aby bylo aktivní i tlačítko Detail, tzn. u zrušeného záznamu v Příkazech bude **řádek červeně** a aktivní budou pouze tlačítka **Detail** a **Původní**

**Comment by Sentinel65** [comment]
verze 19.10.04 když dám opravit nějaký záznam a následně kliknu na tlačítko **Zrušit opravu**, tak mi přijde mail s opravou, přestože jsem dával rušení opravy a nic jsem neodesílal

**Comment by Sundin18** [comment]
opraveno, verze 19.10.05

**Comment by Sentinel65** [comment]
Ok
