### ISSUE TITLE
Pohled ZMU role va@szdc.cz

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#39]
Tady mám pocit, že jde o bug. Role VA má sice vidět všechny oblasti, ale měli by mít možnost si ty oblasti filtrovat podle sebe a nastavení v sekci Oblast vpravo.

Předpokládal jsem, že po přihlášení by měli mít nastavené checkboxy u všech oblastí jako zatržené, nyní není zatržený žádný a jsou vidět všechny oblasti.
Ale, a kvůli tomu píšu, pokud zatrhnu třeba jen oblast Praha, tak se nic nezmění a je tam pořád vidět vše viz. obrázek. Takže to filtrování co se týká oblastí nefunguje.

To samé se týká role ccdppha@szdc.cz. U Přerova je to jedno.

![_va](https://user-images.githubusercontent.com/54531291/65957681-c037ae00-e44d-11e9-9c9d-8372064c1b64.png)

**Comment by Sundin18** [comment]
Opraveno, verze 19.10.02

**Comment by Sentinel65** [comment]
OK
