### ISSUE TITLE
DP ukládání "undefined" - datum a čas

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#4]
Ahoj Petře, koukám u dispečerských příkazů už jsi opravil ukládání. Ještě tam je ale jeden renonc. Přihlásil jsem se tam jako provozní dispečer UNL tzn. dunl@szdc.cz a pořídil záznam, pak jej opravil s příznakem "Vyplnit jako žádost o stanovisko k narušení GVD". Obojí se korektně ukončilo, ale když si dám detail, tak tam je u položky "Vydal" text "undefined" - datum a čas. To je zatím takto schválně nebo by tam mělo aspoň to "jméno" - Dispečer UNL"

**Comment by Sentinel65** [comment]
Ahoj, tak teď to zkouším a žádná změna, pořád tam v detailu vidím v detailu v položce Vydal - undefined. Domluvme se, že ty položky budeme uzavírat, až se to pořádně vyzkouší. Stačí tam dát poznámku, že 5o je opraveno, a po vyzkoušení a potvrzení se to může uzavřít.

**Comment by Sentinel65** [comment]
Byl to DP 3002 26.08.2019 19:04  UNL PD3

**Comment by zachyunl** [comment]
> Ahoj, tak teď to zkouším a žádná změna, pořád tam v detailu vidím v detailu v položce Vydal - undefined. Domluvme se, že ty položky budeme uzavírat, až se to pořádně vyzkouší. Stačí tam dát poznámku, že 5o je opraveno, a po vyzkoušení a potvrzení se to může uzavřít.

Psal jsem Petrovi, ať u položek než je uzavře, tak dá jednoduchou poznámku o provedené změně a že  změna bude např. ve verzi 19.08.01 apod. Podle toho poznáme zda již testovat nebo ne. Po opravě se může vykotit jiná chyba a to už bych nechal jako další položku issue. Pokud to je významnější změna, tak se nechá nová položka s poznámkou k otestování a poté se uzavírá až je vše potvrzeno.

**Comment by Sundin18** [comment]
Ok, teď jsem tedy nahrál opravy a změny, které jsou tady jako uzavřené issue.

**Comment by Sundin18** [comment]
Opraveno, verze 19.08.1

**Comment by Sentinel65** [comment]
OK!
