### ISSUE TITLE
Opravy v ZMU

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#40]
- v ZaMU změnit název položky Číslo DP: na **Příkazy:**   ... OK
- v ZaMU v tmavě šedém pruhu pro ZP změnit název položky  Doba trvání: na **Doba trvání [ZP]:**   ... OK
- v ZaMU při změně záznamu přejmenovat položku Příkazy a vyjádření pouze na **Příkazy**   ... OK
- v ZaMU při změně záznamu v položce nově **Příkazy** se při rozbalení komba zobrazí seznam příkazů s typem (např. 39 DP), ale po vybrání už tam je vidět jen to číslo bez toho typu a to samé se přenáší do celkového pohledu v ZaMU

![_DP](https://user-images.githubusercontent.com/54531291/66028220-ea947480-e4fc-11e9-900b-72f65c9b9e0f.png)

**Comment by Sentinel65** [comment]
V pohledu **Příkazy**

k tomu **tlačítku **Zrušit** pro jistotu navázat potvrzovací dialog Ano - Ne**

**Comment by Sundin18** [comment]
Hotovo verze 19.10.04

**Comment by Sentinel65** [comment]
>v ZaMU při změně záznamu v položce nově Příkazy se při rozbalení komba zobrazí seznam příkazů s typem (např. 39 DP), ale po vybrání už tam je vidět jen to číslo bez toho typu a to samé se přenáší do celkového pohledu v ZaMU

Toto pořád není ... chtěl bych, aby se mi v ZaMU zobrazovalo, to co v tom kombu Příkazy tzn. 31 ST nebo 25 DP atd a ne jen číslo

**Comment by Sundin18** [comment]
Dej refresh prohlížeče, mně se to zobrazuje.

**Comment by Sentinel65** [comment]
Nevím, jestli si rozumíme, ale zkoušel jsem refresh, odhlášení a přihlášení, nakonec jsem ukončil a znovu nahodil prohlížeč a pořád stejně, takže raději posílám screenshot. A zkoušel jsem to ted i doma na svém ntb na firefox a to samé.

![image](https://user-images.githubusercontent.com/54531291/66055658-28fa5580-e536-11e9-8158-33fa7d3623e6.png)

![image](https://user-images.githubusercontent.com/54531291/66055695-39aacb80-e536-11e9-8980-32600870fa5d.png)

**Comment by Sundin18** [comment]
hotovo, verze 19.10.05

**Comment by Sentinel65** [comment]
Ok
