### ISSUE TITLE
Formulář Neprojeté trasy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#44]
Jirka říkal, že tam vymýšlíš nějaké propojení tohoto formuláře s ZaMU. Zatím s tím počkej, vedoucí analýzy na CDP Praha má tento týden dovolenou, bude příští týden, tak s ním prodiskutuji, jak to vlastně chce.

**Comment by Sundin18** [comment]
No tohle asi nevím, jestli půjde. To jsem si jen tak nadhodil jako co kdyby, ale zatím nevím jak a vzhledem k tomu, že to ani není jednotné pro všechny, tak nad tim zatím neuvažuji.

**Comment by Sentinel65** [comment]
Po dnešní poradě:

- formulář **neprojeté trasy bude samostatně** bez jakékoli vazby na ZaMU
- oprávnění na tento formulář a možnost do něj zapisovat a vidět ho budou mít role vdpha@szdc.cz, vdunl@szdc.cz, dpha@szdc.cz tzn. v Praze do něj budou zapisovat provozní dispečeři, v Ustí pak vedoucí dispečer, vedoucí dispečer v Praze to bude mít jako kontrolu s možností zapsat

**Comment by Sentinel65** [comment]
Petře, teď se koukám na ten formulář, co se používá, tak ta komba tam udělej stejně viz obrázek, oni to tam teďka mají taky přednastavené a pokud je to důvod neuvedený v seznamu, tak zvolí "jiné neuvedené" v seznamu komba. Je třeba tam taky udělat ty záznamy o opravách a zrušení záznamu = to bude stejné jako u těch Příkazů, červeně označený řádek s disabled tlačítky, jako je to na obrázku.

Oprávní bude mít pro zápis také role apha@szdc.cz

![_NT_01](https://user-images.githubusercontent.com/54531291/66707216-4781fd00-ed3d-11e9-8c3a-f0bcc1306043.png)

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.22

**Comment by zachyunl** [comment]
Petře já ten formulář nevidím?

**Comment by Sentinel65** [comment]
Petře, 

oprávněni je pouze pro **CDP Praha**, z **Přerova tu nabídku Neprojeté trasy odeber**. Tlačítko **Smazat** bude mít **pouze role apha@szdc.cz**. Jinak ok

**Comment by Sundin18** [comment]
Měl bys ho vidět. Kliknout na tlačítko "Přidat záznam"

**Comment by zachyunl** [comment]
Už to vidím, neměl jsem to vůbec v hlavním menu.

**Comment by Sundin18** [comment]
Tak to bylo nejspíš způsobeno tím, že jsi byl přihlášený ještě "zastara", kdy jsi neměl oprávnění zobrazit tlačítko"

**Comment by Sundin18** [comment]
hotovo, verze 19.10.23

**Comment by Sentinel65** [comment]
Ve formuláři oprav v položce **Důvod** řádek "Závada dopr. zam-ce" na "**Závada dopr. zaměstnance**"
U té role **apha@szdc.cz** tam nevidím to tlačítko **Smazat**.  Tady v tom případě bych potřeboval, aby účet **apha@szdc.cz** viděl i **data za Ustí nad Labem**

**Comment by Sundin18** [comment]
Změněno.
My vidíme data za všechny jako vedoucí analýzy. A asi tu bude chyba v návrhu programu. Já mám rozdělenou analýzu na 3 (Praha, Přerov, Ústí), takže záznamy za Ústí vidí ústecká analýza.

**Comment by Sentinel65** [comment]
Ne není chyba v návrhu programu :)
Analýzu máš rozdělenou dobře, Ale tento formulář speciálně dělá jen CDP Praha, Přerov toto nedělá.
A tady potřebuji pro roli Analýza PHA speciálně pro tento formulář, aby viděla data za obě podoblasti Usti i Prahu, jakožto vrcholovou analýzu CDP Praha. v ZaMU si uživatel pod rolí Analýza PHA může zaškrtnout obě oblasti Ustí i Prahu, tady žádnou možnost nastavení nemá, proto potřebuji, aby se to dalo nějak nastavit. Snad jsem to napsal tak, aby jsi to pochopil :-)

**Comment by Sundin18** [comment]
Analýza PHA tedy vidí záznamy odřeknutých tras za oblasti Praha i Ústí.

**Comment by Sentinel65** [comment]
OK, ještě další požadavky:

- sloupec OŘ úplně zrušit
- pro role **dpha@szdc.cz, dunl@szdc.cz, vdpha@szdc.cz a vdunl@szdc.cz** doplnit za tlačítko Opravit nové **tlačítko Zrušit** (stejné jako u Příkazů) tzn. **řádek zůstane vidět, ale celý bude červenou barvou**, tlačítka **Opravit a Zrušit budou disabled**.
- role aunl@szdc.cz a apha@szdc.cz si pak rozhodnou, zda řádek záznamu **Smazat** nebo ne.
- doplnit do **Filtrovat dle datumu** novou položku 24 hodin (myšleno 00:00 - 23:59 aktuální den)
- je možné (pravděpodobné) že tento pohled (možná i ZaMU) bude zpřístupněn ústřednímu dispečerovi (takže patrně budeme tvořit novou roli)

**Comment by Sundin18** [comment]
Hotovo (verze 19.10.24)
Jinak výběr jednoho dne lze i dvojklikem na den, který chci zobrazit, ale přidal jsem tam i tlačítko "dnes"

**Comment by Sentinel65** [comment]
U toho tlačítka Zrušit to háže chybu:

Záznam se nepodařilo smazat:
Error: Request failed status code 500

**Comment by Sundin18** [comment]
Hm,to ještě musím změnit v databázi. Na to jsem zapomněl.

**Comment by Sundin18** [comment]
Tak doplněno

**Comment by Sentinel65** [comment]
Petře, ta chyba se ještě objevuje při vytváření nového záznamu

Záznam se nepodařilo vytvořit:
Error: Request failed status code 500

**Comment by Sundin18** [comment]
Opraveno (verze 19.10.24)

**Comment by Sentinel65** [comment]
Petře, udělej tam prosím tě ještě filtry na **Trasa**, **Důvod** a **Trať**, pak už by to snad mělo být vše.

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.27

**Comment by Sundin18** [comment]
Hotovo

**Comment by Sentinel65** [comment]
OK, díky

**Comment by Sentinel65** [comment]
Tak s tímhle pohledem jsme ještě neskončili .-)

Bude potřeba dodělat následující:
- zpřístupníme pohled nově i pro role dpre@szdc.cz, vdpre@szdc.cz, apre@szdc.cz dle pravidel, jako máme teď nastavené u našich rolí
- nově se do tohoto formuláře vloží sloupec ID ZaMU (ideálně na začátek, opět jako povinná položka), kam se bude zapisovat ID uloženého záznamu v ZaMU 
- při této příležitosti  - Petře změň v **ZaMU u toho čísla vpravo nahoře u každého záznamu** #xxx ** font, aby byl stejný i co se týká velikosti, jako text, který se tam zapisuje** (z důvodu lepší čitelnosti). Pokud by to šlo (neměl by to být problém - ve formulářích na webu to vidím), tak to číslo bez toho znaku # udělej klikací, po kliknutí na ten odkaz by se číslo zkopírovalo do schránky
- v pohledu Neprojeté trasy v seznamu záznamů ve sloupci **ID ZaMU by to číslo bylo opět klikací** s tím, že po kliknutí na odkaz by se **zobrazil příslušný záznam ze ZaMU** (obdoba jako u Příkazu v ZaMU)

**Comment by Sundin18** [comment]
Hmm a jsme u toho, co jsem tušil na začátku, že se to bude chtít propojit.

**Comment by Sentinel65** [comment]
Bude s tím nějaký problém Petře ?

**Comment by Sundin18** [comment]
Přemýšlím jak to provést, protože vedoucí v Ústí napíše  MU a pak se bude muset přepnout na trasy, tak si myslím,že se jim to nebude líbit. Takže  jsem přemýšlel, že by mohl přidat tu odreknutou trasu už při zápisu MU. A ještě se zeptám jestli se nemůže stát, že nějaká odreknuta  trasa nemůže být k přidána k více zapisum MU.

**Comment by Sundin18** [comment]
Hotovo (verze 19.10.28)
Je to tedy udělané tak, že je možné přidat neprojetou trasu i přímo ze záznamu v ZaMUu (tlačítko "přidat neprojetou trasu". Dále tam je tlačítko, na kterém je číslo MU, které se po kliknutí uloží do schránky (stejně jako by uživatel dal Ctrl+C) a to je pak možné doplnit k již vytvořené neprojeté trase přes tlačítko "Opravit" kam se pak může vložit do pole "ZaMU číslo". Takže je to udělané pro obě "varianty". Jako když je nejprve napsaná MU nebo neprojetá trasa.

**Comment by Sentinel65** [comment]
V Neprojetých trasách - sloupec MU č. přejmenuj na ZaMU # a to číslo v tom záznamu jsem chtěl, aby bylo klikací a zobrazil se ten záznam ze ZaMU v novém okně stejně jako to je u Příkazů

**Comment by Sentinel65** [comment]
Na tom čísle, které je klikací a ukládá se do schránky, šlo by tam místo toho zeleného informativního okna vpravo dole dát okno typu Alert ? Takhle si toho skoro ani nevšimnou ...

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.29

**Comment by Sentinel65** [comment]
Je to dobré, ale snažím se, aby to pro živatele bylo co nejlepší. Šlo by to okno, které se otevře při kliknutí na to číslo ZaMU, aby  vypadalo stejně jako v ZaMU takto ? Udělat ho klidně širší, aby se dodržel ten formát  počet řádků.

![_Za](https://user-images.githubusercontent.com/54531291/67305572-d0dfbf00-f4f5-11e9-8f68-95a189b1f570.png)

**Comment by Sundin18** [comment]
Já jsem to tak měl, ale pak se ten text hodně zalamoval a nevypadalo to hezky. Okno můžu zvětšit, ale pak to asi nebude vypadat dobře na monitorech s malým rozlišením.

**Comment by Sentinel65** [comment]
OK, zatím to nech, uvidíme toho 13.11. na poradě při prezentaci

**Comment by Sundin18** [comment]
Ok, dal jsem to tedy do většího okna a uvidíme.
