### ISSUE TITLE
Pohled PMD

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#45]
Na žádost kluků z Přerova zvětšit šířku formuláře PMD i toho přehledu záznamů.
Když zadávají položku "**úsek**", tak v tom formuláři nevidí vše co již napsali.
Mají tam specificky dlouhé názvy stanic - příklad:
Frenštát pod Radhoštěm - Kunčice pod Ondřejníkem
Navíc tam mají naszený nějaký nový typ širokoúhlých monitorů, takže si tam každý různě nastavuje velikost okna prohlížeče. ne se vším něco půjde udělat. Tady u toho pohledu je celkem dost místa.

**Comment by Sundin18** [comment]
Hotovo (verze 19.10.07)

**Comment by Sentinel65** [comment]
Za mě OK, uvidíme jestli se z Přerova ozvou.
