### ISSUE TITLE
Formuláře - ZaMU, Příkazy, PMD - modul date - time

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#46]
Petře, zkoumal jsem ted u těch formulářů ten modul date - time na vyplnění data a času a zjistil jsem následujicí:

- chybí tam test na zadání data a času, které ještě nenastalo, tzn. pokusil jsem se zadat datum 7.10.2019 11:00 hodin a záznam se uložil do datábáze (viz. obrázek), i když v přehledu záznamů se nezobrazil, takže u těch polí, kde se zadává zahájení a ukončení pomocí tohoto modulu to bude chtít ošetřit

- v Příkazech to je v pořádku, tam je přístupné pouze dnešní datum
- v ZaMU to je špatně, tam to není dopředu omezené vůbec nijak
- v PMD je to stejně jako u Příkazů, ALE tady pokud to půjde bych udělal zarážku +1 den a to z toho důvodu, že bude třeba naplánovat v systému jízdu PMD na čas po půlnoci a je třeba to číslo vědět už před půlnocí
- pak tu byla připomínka od provozních, jestli by to aktuální datum v tom kalendáři mohlo být podbarvené místo šedou barvou třeba zelenou, tu šedou mají zafixovanou jako disabled

![_modul-date-time](https://user-images.githubusercontent.com/54531291/66138952-d2f1e480-e5ff-11e9-8044-7b4c1f1819f5.png)

**Comment by Sundin18** [comment]
hotovo, verze 19.10.09

**Comment by Sentinel65** [comment]
Není hotovo :-)

Koukám v ZaMU to je jen u pole Zahájeno, ale u ostatních to je bez zarážky (Ukončeno, Zahájeno [ZP], Ukončeno [ZP]) 
V Příkazech to bylo OK, v PMD je to opraveno. Aktuální datum zelená OK

**Comment by Sundin18** [comment]
Tak u těch ostatních polích to vyplnit nelze. Nemohu zahájit zastavení provozu dříve než začala událost atd.

**Comment by Sentinel65** [comment]
Asi si nerozumíme. Na obrázku mám změnu záznamu, který je již zahájen a očekával bych tam zarážku, nemohu ten záznam ukončit v čase, který ještě nenastal, dneska je 3.10.2019 a já tam klidně ted mohu do Ukončeno zapsat 30.10.2019 19:00 rozumíš ?

![_modul-date-time2](https://user-images.githubusercontent.com/54531291/66147860-f3c23600-e60f-11e9-84f5-da7a6f09268c.png)

**Comment by Sundin18** [comment]
hotovo, verze 19.10.10

**Comment by Sentinel65** [comment]
OK
