### ISSUE TITLE
Formulář HelpDesk

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#47]
Toto zatím vůbec nespěchá. Představa je následujicí:

- odkaz na e-mailový formulář by byl vpravo vedle označení čísla verze
- formulář by obsahoval tato samostatná pole pod sebou:  jméno a funkce dle role přihlášení, pracoviště, telefonní číslo a popis závady (max. 200 znaků)
- všechna pole by byla povinná (klasicky označit červeným textem jako u ostatních formulářů)
- mail by se odesílal na přednastavenou adresu helpdeskCDPPHA@szdc.cz, s přednastaveným Předmětem "Šedivák"
- v mailu pod textem s popisem by se pak doplnil klasicky řádek s datumem a computername, odkud to bylo pořízeno

Takto docílíme toho, že nám to bude propadat do oficiální HelpDeskové aplikace CDP Praha a budeme tam mít potřebné informace

**Comment by Sundin18** [comment]
Hotovo, verze 19.12.0

**Comment by zachyunl** [comment]
Při oděslání píše tuto chybu
Upozornění:
Error: Request failed with status code 500

**Comment by Sundin18** [comment]
jsem špatně zkopíroval adresu, tak teď už je to v pořádku

**Comment by Sentinel65** [comment]
Po odeslání formuláře by se tento měl vynulovat ne ? Takhle se tam skice vpravo dole objěví na chvilku, že bylo odesláno, ale formulář zůstane stejný tj. vyplněný

**Comment by Sundin18** [comment]
Ok, udělám, aby se to vynulovalo

**Comment by Sentinel65** [comment]
Dneska jsem zmigroval stránku Helpdesku CDP Praha, zprávy odeslané z formuláře se tam objevily, takže toto funguje.
Je třeba po odeslání, aby se formulář vymazal.

**Comment by Sundin18** [comment]
Po odeslání se formulář vymaže. Verze 19.12.01

**Comment by Sentinel65** [comment]
OK, ještě je třeba opravit dvě věci:

- za položkou Telefon smazat ten text **</strong<>**
- místo ip adresy tam do kódu dej prosím tě výpis CN (computer name)

Jméno | Jiří Horký
-- | --
Funkce | Vedoucí dispečer
Pracoviště | CDP Praha
Telefon**</strong<>** | 724 260 481
Popis závady | TEST
Odesláno z pracoviště (čas) | 10.99.160.126 v 17:13:03

**Comment by Sundin18** [comment]
opraveno

**Comment by Sentinel65** [comment]
Ahoj,
pro informaci jak pro Jirku, tak pro tebe Petře - z formuláře v Šediváku už propadávají ty požadavky přímo na HelpDesk CDP Praha, dle předmětu **Popis závady z Šediváku** se tam automaticky nastavuje **Kategorie - Požadavek na informatika**.
Jediné čeho jsem si všiml a chtěl bych to změnit je tam e-mailová adresa, která je asi na tvrdo nastavena v tom formuláři a v tuto chvíli tam chodí odesílatel CDPPHAdispprik@szdc.cz.
Takže tu **adresu** Petře prosím tě **změň na CDPPHAinfo@szdc.cz**

**Comment by Sundin18** [comment]
Ta adresa je nastavena pro všechny odesílané emaily. Tak se raději ptám, jestli adresa "info" má být nastavena jen pro email na helpdesk nebo taky pro všechny?

**Comment by Sentinel65** [comment]
Aha, aha ...
No otázka teď teda zní, dokážeš to rozlišit pro vícero událostí ?

Pro HelpDesk by tam tedy byla ta adresa odesílací CDPPHAinfo@szdc.cz

Pro odesílání Příkazů (protože nic jiného si myslím se odesílat nebude) kdyby to šlo rozlišit podle oblastí, bylo by to ideální tzn.

za oblast Praha by to byla adresa CDPPHAanalyza@szdc.cz
za oblast Ústí by to byla adresa CDPUNLanalyza@szdc.cz
za oblast Přerov by to byla adresa CDPPREanalyza@szdc.cz

Půjde to takto ?

**Comment by Sundin18** [comment]
Jj, myslím, že půjde, mrknu na to.

**Comment by Sundin18** [comment]
Tak odesílací adresy nastaveny

**Comment by Sentinel65** [comment]
Super, funguje
