### ISSUE TITLE
ZaMU - položka Příkazy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#49]
Ve formuláři ZaMU při tvorbě nebo změně záznamu je požadavek, aby se **data v kombu se seznamem příkazů řadila sestupně**, tzn. aby **poslední zadaný příkaz byl nahoře**.

**Comment by Sundin18** [comment]
V tom kombu bude velmi zřídka kdy více jak jedno číslo, ale pořadí tedy změněno. Verze 19.10.11

**Comment by Sentinel65** [comment]
Jsme se asi nepochopili, jde o toto kombo na obrázku, kde VD při zápisu záznamu vybírá z Příkazů a chtějí mít ten posledně zadaný(é) nahoře, takže proto to řazení.

![_ZaMU_Prikazy](https://user-images.githubusercontent.com/54531291/66211525-92a46c00-e6bc-11e9-9838-b815c75ac389.png)

**Comment by Sundin18** [comment]
Tam právě bude max tak jeden, protože vedoucí zapisují MU vždycky když se vydá DP. V tom kombu se zobrazují jen neprirazene DP. Takže by se nemělo stát, že by tam DP pribyvaly.

**Comment by Sentinel65** [comment]
Jo rozumím té logice, ale stát se to může ve chvíli, kdy se těch DP vydá vícero za krátký čas. Teď jsi mě ale přivedl na myšlenku, že vlastně VD už nebudou chodit maily z DP a jak se dozví, aniž by se přepnul na pohled Příkazy, že tam je nějaký uložen. Šlo by tedy udělat po uložení nového Příkazu za danou oblast, aby se zobrazila nějaká notifikace (podbarvení tlačíka Příkazy či nějaká ikona, která by začala blikat ? ale pouze pro toho VD, jehož oblasti se ten Příkaz týká), aby si toho ten VD všiml ? Protože většinou mají před sebou ten pohled ZaMU.

**Comment by Sundin18** [comment]
Tak jsem to nakonec udělal trochu jinak. Na stránce ZaMU vedle tlačítek "Přidat záznam" a "Vybrat vše" je v červeném poli číslo s počtem nepřiřazených příkazů. Funguje to tak, že např. provozní dispečer napíše disp.příkaz, tak potom, pokud dojde k obnovení prohlížeče na straně vedoucího dispečera, se zobrazí (přičte) číslo. Verze 19.10.12

**Comment by Sentinel65** [comment]
Petře, to se obavam ze jsme tam kde jsme byli. VD nebude schopen pri tom mnozstvi informaci drzet v pameti, jake cislo tam bylo pred pul hodinou. To uz by bylo lepsi jak jsem navrhvoval, pri zapsani a ulozeni zaznamu nastavit barvu tlacitka Detail a v momente, kdy si ten detail precte, barvu tlacitka Detail zmenit. Tohle budeme muset probrat s lidma, at nedelame zbytecnou praci.

**Comment by Sundin18** [comment]
To odpovídá tomu jak jsi chtěl, aby se zobrazovalo číslo, když se objeví nový DP. Stále platí, že by tam nemělo být žádné  číslo nebo číslo 1 či 2. Navíc je v podstatě jedno, jaké číslo tam je, protože vždycky by měl nakonec VD přiřadit všechny DP. Když VD dispečer uvidí, že se tam objevilo číslo, může si otevřít okno "Přidat záznam", kde uvidí jaké číslo DP není přiřazeno k žádnému záznamu.
To s tím odkazem je složitější než jsem si myslel, protože to tlačítko nefunguje jako odkaz. Takže zatím ani nevím, jak to vytvořit.

**Comment by Sentinel65** [comment]
OK Peťo, je pravda že se teď pohybujeme v testovacích číslech, v reálu by to mělo být v jednotkách nepřidělených DP. A každý VD v oblasti tam má své číslo nepřidělených příkazů. Tak snad to takto bude stačit.

**Comment by Sentinel65** [comment]
Ale zase to bude na tom VD, aby si čas od času udělal refresh stránky, **automatický refresh použít nemůžeme**.

Ten text v Tool tipu prosím tě změň na "**Počet nezapsaných Příkazů v ZaMU**"

**Comment by Sentinel65** [comment]
Teď jsem byl u vedoucích dispečerů a vyzpovídal je, jak to s těmi Příkazy vlastně je.
Každopádně mi tam teď Petře pořád nesedí celkové **počty** respektive netuším, co se do toho čísla v červeném čtverečku počítá a odkud - viz. obrázky.
V ZaMU je tam při tom screenshotu vidět 20. V DP jsem napočítal 17 (červené = zrušené DP nepočítám), v ST je počet 6, takže dohromady by to mělo být 23 a ne 20.

Jinak: 
VD píše do svodky DP a ST normálně s čísly tak, jak byly vytvořeny a zapsány do DB. Takže v tom červeném čtverci je třeba, aby byl součet platných (nezrušených) čísel DP a ST.
U PZ je to úplně jinak, on potřebuje, aby mu byly nějak notifikovány i ty PZ, ale do ZaMU napíše čistě jen text a určitou předepsanou (domluvenou) formulaci, ale nikoliv číslo PZ.

![vdpha_suma_prikazy](https://user-images.githubusercontent.com/54531291/66288411-67e32f00-e8d9-11e9-893a-cb53d7a2b934.png)

![vdpha_dp_17](https://user-images.githubusercontent.com/54531291/66288422-6f0a3d00-e8d9-11e9-98df-f2f3ba4d3e23.png)

![vdpha_st_6](https://user-images.githubusercontent.com/54531291/66288426-7598b480-e8d9-11e9-9ed7-a0cea6c7b866.png)

**Comment by Sentinel65** [comment]
Teď jsem v Příkazech dal zrušit DP 2 a v tom čtverci se to číslo 20 nijak nezměnilo.

**Comment by Sentinel65** [comment]
**Jo tak už jsem na to přišel, to je opravdu ten počet nezapsaných resp. počet co se zobrazuje v tom kombu pro přidělení Přikazu v ZaMU.** Zrušil jsem teď jedno z těch čísel, co se nabízelo v kombu a to číslo v ZaMU se snížilo o jednu.

**Comment by Sentinel65** [comment]
**Ale pořád teda platí to, že jednak v tom kombu pro zapsání Příkazu by se neměly objevovat a nabízet čísla z PZ a ten součet v červeném čtverci by byl jen z nepřidělených DP a ST.**

**Comment by Sentinel65** [comment]
**Zatím ještě počkej s nějakými zásadními úpravami toho, co tam teď je nastavené. Zítra tady máme s vedením školení a po něm jim budu chtít udělat prezentaci dosavadního stavu a vývoje Šediváku a pobavit se s ními nejen o těch Příkazech. Takže zítra třeba padne nějaké rozhodnutí, že to můžeme nechat vše dohromady DP. ST i PZ a tím pádem, bychom to nechali tak, jak to je teď.**

**Comment by Sundin18** [comment]
Jen jsem tedy opravil počet nepřiřazených příkazů tedy jen na DP a ST. PZ se tam tedy nepočítají a nezobrazují ani v kombu pro přidání (úpravu) záznamu v ZaMU

**Comment by Sentinel65** [comment]
Jsem ti psal, aby jsi počkal, že zítra máme školení a poradu a že je možné, že to co platilo doposud zruší a zobrazovalo by se snad vše včetně těch PZ :-)

**Comment by Sundin18** [comment]
Dobře, ale ty by se pak tedy musely taky přiřazovat k nějaké ZaMU. Já to tedy vrátím.

**Comment by Sentinel65** [comment]
Zatím to nech :-)

**Comment by Sentinel65** [comment]
Počkáma, až co se dozvím zítra Petře.

**Comment by Sundin18** [comment]
Tak teď nevím, jestli nechat včetně těch PZ nebo bez nich :-)

**Comment by Sentinel65** [comment]
Nic s tím teď nedělej :-) nech to být tak jak to teď je, zítra napíšu
Zatím můžeš dělat na tom formuláři Evidence aktivací SZO

**Comment by Sundin18** [comment]
ok

**Comment by Sentinel65** [comment]
Takže po dnešní poradě:
 
- v ZAMU do červeného čtverečku "Počet nepřiřazených příkazů" **počítat vše tj. DP, ST i VPZ**
- v ZAMU v položce Příkazy: **přidat oprávnění na klikací odkaz příkazů** i pro role va@szdc.cz, ccdppha@szdc.cz a ccdppre@szdc.cz 
- v ZAMU u nepřihlášených v přehledu záznamů nezobrazovat vůbec položku **Příkazy**:

**Comment by Sundin18** [comment]
A budou se tedy PZ přiřazovat k záznamům ZaMU ?
Jj, s tím kombem je to zatím sci-fi opravdu. Zkusím to nějak vymyslet, aby viděl ten náhled bez přepínání na "Příkazy"

**Comment by Sentinel65** [comment]
Ano bude se tam přiřazovat vše ! Ale potřebuju, aby u nepřihlášených v tom přehledu záznamů zmizelo to pole Příkazy:

**Comment by Sundin18** [comment]
Hotovo (zatím bez "sci-fi"), verze 19.10.13

**Comment by Sentinel65** [comment]
Prosím tě, to Sci-fi má Prioritu 5. Tím se teď vůbec nezdržuj

**Comment by Sentinel65** [comment]
V ZaMU se nepřípočítávají PZ k počtu v červeném čtverci a ani nejsou nové záznamy v seznamu komba pro zapsání Příkazu v roli vedoucího dispečera. Zkoušel jsem u Prahy PZ 60

**Comment by Sundin18** [comment]
Já jsem nenahrál jeden soubor, teď už to šlape. Jinak mě napadlo, že bych místo toho čísla udělal vpravo nad filtry stejnou kartu jako jsou filtry, jen by v ní byly vypsaná čísla se zkratkou nepřiřazených příkazů. Na ty by bylo možné kliknout a poté by se zobrazilo okno s detailem příkazu.

**Comment by Sundin18** [comment]
Tak je to tam hotové (Verze 19.10.14). Možná by to teď chtělo napsat pořadí toho, co dělat dříve a co později.

**Comment by Sentinel65** [comment]
Petře to byla dobrá myšlenka, těch záznamů tam tolik nebude, jako je teď.

**V tuhle chvíli jsem tam ale našel jeden BUG v ukládání záznamů ! Máme tam uložená dvě stejná čísla 60, jedno jako DP, druhé jako PZ a jde o dva různé záznamy !**

![_DP_60](https://user-images.githubusercontent.com/54531291/66471389-82f5a080-ea8b-11e9-8b04-5197fdfe608e.png)

![_60_PZ](https://user-images.githubusercontent.com/54531291/66471408-89841800-ea8b-11e9-84ff-a4afa106fce9.png)

**Comment by Sundin18** [comment]
Jj, všiml jsem si. Jen nějak nemůžu nasimulovat tu situaci, kdy se ti tak mohlo stát, abych zjistil příčinu.

**Comment by Sentinel65** [comment]
Mrkni se do DB na čas pořízení, netuším jak se to mohlo stát, ale tohle se tam vůbec nemůže objevit, že nám tam vyskočí 2 stejná čísla a ještě k tomu v různých pohledech DP a PZ.

**Comment by Sundin18** [comment]
To je mi jasné, proto si neumím zrovna představit tu situaci, jak k tomu mohlo dojít. Proto se snažím simulovat všechny možnosti, co mě napadají, ale pořád se to ukládá dobře.

**Comment by Sentinel65** [comment]
E-mailové adresy, kam se budou Příkazy posílat (zbytek po za Moravu ještě dopíšu a seznam PO srovnám podle příslušných OŘ)

OŘ Ustí nad Labem     ORUNLsekrp@szdc.cz
OŘ Hradec Králové      ORHKRsekrp@szdc.cz
OŘ Praha                     ORPHAsekrp@szdc.cz
OŘ Plzen                      ORPLZsekrp@szdc.cz
OŘ Brno                       ORBNOsekrp@szdc.cz
OŘ Olomouc                OROLCsekrp@szdc.cz
OŘ Ostrava                   OROVAsekrp@szdc.cz

PO Beroun                    ZSTBRNsek@szdc.cz
PO Kolín                        ZSTKONsek@szdc.cz
PO Kralupy nV              ZSTKNVsek@szdc.cz
PO Nymburk                 ZSTNBKsek@szdc.cz
PO Praha                      ZSTPHAHNsek@szdc.cz
PO Česká Třebová        ZSTCSTsek@szdc.cz
PO Hradec Králové       ZSTHKRsek@szdc.cz
PO Liberec                    ZSTLBCsek@szdc.cz
PO Turnov                    ZSTTUVsek@szdc.cz
PO Děčín                      ZSTDCNsek@szdc.cz
PO Karlovy Vary           ZSTKVRsek@szdc.cz
PO Most                       ZSTMSTsek@szdc.cz
PO Ustí nad Labem      ZSTUNLsek@szdc.cz
PO Plzen                      ZSTPLZsek@szdc.cz
PO České Budějovice   ZSTCBEsek@szdc.cz
PO Tábor                      ZSTTARsek@szdc.cz
PO Brno                       ZSTBNOsek@szdc.cz

**Comment by Sentinel65** [comment]
Prosím tě, ještě j**edna podstatná připomínka** od dispečerů:

Stejně jako je to v ZaMU, je třeba udělat možnost vytisknout do PDF i jednotlivé Příkazy (**v našem případě hlavně VPZ**), takže by to asi bylo společné pro všechny Příkazy. 

**U VPZ by měl být formát PDF následujicí, zkopíroval jsem text z mailu, který ted chodí na VPZ.
Jsou tam udělané mezery, aby po vytisknutí mohl TD ručně vyplnit své vyjádření, stejně jako nadřízený výsledek šetření.**

SŽDC, státní organizace
Centrální dispečerské pracoviště Praha
Dispečerský sál /pracoviště provozního dispečera/ 

Provozní závada číslo: PHA9007/10, pro: DS4A, vydána dne : 11.10.2019
Vlak číslo: 5053 byl zpožděn dne: 25.9.2019
Místo zpoždění: Choceň 
Doba zpoždění: 0 minut
Čas události: 21:53
Traťový /provozní/ dispečer: ???
Ovlivněn vlak: 
Popis závady: Nedodržení stanovené přestupní doby mezi vlaky R 875 a Os 5053 - cestující nestihli přestoupit (vlak R 875 na 1.SK, vlak Os 5053 na 8.SK). VPZ vydáno na základě stížnosti dopravce České dráhy podané dne 11. 10.2019. Obsahem stížnosti je také tvrzení, že nebylo provedeno hlášení staničním rozhlasem. Prosím o ověření pravdivosti tohoto tvrzení a v případě pochybení o příslušné projednání.
Provozní závadu sepsal vedoucí AJŘ: Frajer Jan
Odesláno z pracoviště: cdp0000pha50009.red.szdc.cz v 14:19:22

Vyjádření k provozní závadě: 














Sepsal:
Funkce:
Výsledek šetření:



Za DŘP /OŘP/:

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.21

**Comment by Sentinel65** [comment]
Tlačítko PDF v VPZ nereaguje, zkoušeno u Chrome a Firefox a žádná akce, že by se vygenerovalo a uloožilo PDF

**Comment by Sundin18** [comment]
Já to zkoušel a zkusil i teď a funguje. Zkus raději refresh prohlížeče.

**Comment by Sentinel65** [comment]
Je to divné, mně to nešlo ani když jsem pustil firefox. Tedˇka jsem shodil úplně oba prohlížeče a nahodil a funguje to.

**Comment by Sentinel65** [comment]
Tak ještě ty adresy vyzkoušet

**Comment by zachyunl** [comment]
Navrhuji udělat možnost tisku do pdf i dispečerských příkazů a u Stanoviska k narušení GVD.

**Comment by Sentinel65** [comment]
To ano, ale jak jsem psal:

**Zatím si to připrav v databázi a udělej tam fiktivní OŘ a PO, kde do  OŘ zadej moji adresu horkyj@szdc.cz a do PO zadej adresu sentinel.h@gmail.com at to máme jak vyzkoušet a neposíláme to hned do světa.**

Tak tam vypln zatím pouze adresy pod OŘ Plzen a PO Plzen a dej tam ty adresy. co jsem psal. Komplet adresy se tam dají, až vyzkoušíme tu vazbu, o které jsem psal, že DP směrovaný na PO Plzen půjde zároven na nadřízené OŘ tj. OŘ Plzen.

Jak se toto vyzkouší, tak pak už by se tam daly ty adresy sekretariátů, co jsem psal, ale až těsně před ostrým nasazení, protože to dispečeři pořád zkouší a testují.

**Comment by Sundin18** [comment]
Tak ono už i tohle je ozkoušené, protože když se napsal DP tak to šlo na tvojí, mojí i Jirkovu adresu. Každopádně jsem tam tedy doplnil k testování tedy PO a OŘ s tvými emaily. Je to pod oblastí Praha.

**Comment by Sentinel65** [comment]
No nevím, poslal jsem DP 64 i s opravou a nic nepřišlo, směrováno na PO Praha. Mrkni na to.

**Comment by Sentinel65** [comment]
ST a VPZ nejde vůbec uložit ani nový ani u opravy.

U DP 66 jsem tedy vybral nejdříve PO sentinel.h@gamil.com a přišlo to JENOM na adresu sentinel.h@gmail.com tj. CHYBA musí na oba maily.  To je ten důvod, proč jsem to chtěl vyzkoušet.
Pak jsem pořídil DP 67 OŘ horkyj@szdc.cz a přišel mail JENOM na horkyj@szdc.cz  to je OK.

Zkus se na to podívat a pro jistotu ještě přejmenuj ten PO sentinel.h@gmail.com na PO TEST a to OŘ horkyj@szdc.cz přejmenuj na OŘ TEST

**Comment by Sentinel65** [comment]
Ted jsem zkoušel zrušit DP 66, který byl na PO sentinel ..... a mail přišel na původních 5 adres, mělo to správně přijít na PO sentinel... a na OŘ horkyj@szdc.cz
Potřebuju vyzkoušet tu vazbu, že to bude opravdiu chodit jen tam, kam má.
Takže chce to vytvořit testovací OŘ TEST a PO TEST. 
OŘ TEST bude mít adresu horkyj@szdc.cz
PO TEST bude mít adresu sentinel.h@gmail.com

Pokud napíšu DP na adresáta PO TEST, musí zpráva přijít na obě adresy.
Pokud zruším DP směrovaný původně na PO TEST, musí zpráva o zrušení přijít na obě adresy. 
Pokud napíšu dp na adresát OŘ TEST, musí zpráva přijít JEN na horkyj@szdc.cz.
Pokud zruším DP směrovný na OŘ TEST, musí zpráva o zrušení přijít JEN na horkyj@szdc.cz.

Tohle je třeba mít na 100% vyzkoušené, otestované a funkční, než se to pustí do světa.

**Comment by Sundin18** [comment]
Tak už by to mělo fungovat. Jen pokud vybereš u DP jiného příjemce než OŘ TEST nebo PO TEST, tak vyskočí hláška o chybě. DP se uloží do DB, ale neodešle se email (není adresa) a nedojde k obnovení tabulky s příkazy, takže nově přidaný DP bude vidět, až po aktualizaci stránky.

Zároveň jsem objevil, proč to předtím jednou uložilo dva příkazy pod stejným číslem, takže to už se taky nestane.

**Comment by Sentinel65** [comment]
OK, funguje, necháme nastavený současný stav, před přechodem doplníme adresy dle členění viz nahoře.

**Comment by Sundin18** [comment]
Jen jsem to ještě malinko doupravil pro testování. Všichni příjemci OŘ chodí na tvůj email na sždc, vše ostatní chodí na email na gmailu. Takže už je jedno, koho vyberou.

**Comment by Sentinel65** [comment]
OK díky

**Comment by Sentinel65** [comment]
Ještě jedna drobná úprava po konzultaci s Analýzou:

Platí pouze pro DP !
Text v generované emailové zprávě (a samozřejmě i v příloze PDF) 

Stanovisko k narušení GVD zašlete na SŽDC, státní organizace, Centrální dispečerské pracoviště Praha, ATP PHA - AJŘ (StarostovaL@szdc.cz) a pracoviště Analýza GŘ (O11analyza@szdc.cz), v kopii pak na adresu příslušného OŘ: Knopf@szdc.cz(OŘ Praha), Steffl@szdc.cz(OŘ Ústí n.L.), Krpec@szdc.cz(OŘ Hr.Králové),Krondl@szdc.cz(OŘ Plzeň), Suchy@szdc.cz(OŘ Brno)

opravit na tento text u CDP Praha:

**Stanovisko k narušení GVD zašlete na SŽDC, státní organizace, Centrální dispečerské pracoviště Praha, AJŘ (CDPPHAanalyza@szdc.cz) a pracoviště Analýza GŘ (O11analyza@szdc.cz), v kopii pak na adresu příslušného OŘ.**

opravit na tento text u CDP Přerov:

Stanovisko k narušení GVD zašlete na SŽDC, státní organizace, Centrální dispečerské pracoviště Přerov, OATP PRE (CDPPREanalyza@szdc.cz) a pracoviště Analýza GŘ (O11analyza@szdc.cz), v kopii pak na adresu příslušného OŘ.**

**Comment by Sundin18** [comment]
Změněno, verze 19.10.24

**Comment by Sentinel65** [comment]
OK

**Comment by Sentinel65** [comment]
Petře, tak jsme našli ještě jednu chybku viz obrázek.

Ve formuláři a v pohledech **Detail** a **Původní** je rozpor mezi položkami.
U DP 73 to vidíš na obrázku.

- položka **Vlak číslo** = 111
- položka **Ovlivněn vlak** = 123

Ale v pohledech **Detail** a **Původní**

- položka **Vlak číslo** úplně chybí
- položka **Ovlivněn vlak** má chybně hodnotu **111**, což je hodnota položky **Vlak číslo**


![_DP_73](https://user-images.githubusercontent.com/54531291/66900872-e0df3680-effd-11e9-8cca-3dcddacefb93.png)

**Comment by Sundin18** [comment]
Opraveno, verze 19.10.25

**Comment by Sentinel65** [comment]
OK

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.29

**Comment by Sentinel65** [comment]
OK
