### ISSUE TITLE
Závady a mimořádné události - ID záznamu

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#5]
V sekci "Závady a mimořádné události"  mi tady oproti ostré verzi chybí jedna podstatná věc a to zobrazení ID každého záznamu, podle kterého se daleko snadněji budou dohledávat nějaké chyby, než když mi někdo bude vysvětlovat, co je v záznamu napsáno.

**Comment by Sundin18** [comment]
Doplněno číslo do pravého horního rohu záznamu

**Comment by Sundin18** [comment]
Doplněno číslo záznamu do pravého horního rohu k příslušnému záznamu. (Verze 19.08.1)

**Comment by Sentinel65** [comment]
OK !
