### ISSUE TITLE
ZaMU - změna záznamu u role Analýza CDP

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#50]
Požadavek z Přerova:

v ZaMU ve **změně záznamu** (je to třeba ale přidělat i do **Přidat záznam = pouze u této role** !)  , když se zaškrtne **Ukončit šetření**, tak krom zobrazení těch emailových adres tam zobrazit **možnost nahrání přílohy ve formátech, které používáme u Příkazů, a odeslat tu přílohu na ty definované adresy**.

Analýza nůže sama vytvořit záznam v ZaMU a ukočit jeho šetření a mít možnost tam vybrat adresáty a poslat jim přílohu dokumentu, kterou mají připravenou v PC, protože je obsahově větší, než položka **Vlivy** v samotném formuláři

**Comment by Sentinel65** [comment]
Tak jsem si myslel, že toto zrušíme, ale dneska jsem opět mluvil s oběma analýzama PHA i PRE a ten jejich postup práce při té evidenci je úplně odlišný.

**Takže toto platí jen pro roli apre@szdc.cz** tedy Přerov

Jestli by jsi to tam mohl ještě upravit, když se **zaškrtne ten checkbox Šetření ukončeno** takto:

![_ZaMU_PRE_Setreni_ukonceno](https://user-images.githubusercontent.com/54531291/67364528-045f2f80-f570-11e9-8bc1-d06c1478dc43.png)

Bylo by to pro ně i přehlednější. A doplnit tam možnost odeslání přílohy v té emailové zprávě v těch formátech, jak máme nastaveno *.jpeg, *.jpg, *.png, *.pdf, *.doc, *.docx, *.xls, *.xlsx max 5 MB.

**Comment by Sentinel65** [comment]
A ještě dotaz. Na kolik znaků je v ZaMU položka **Popis** a **Vlivy** aktuálně nastavená a kolik je maximální možnost ?

**Comment by Sundin18** [comment]
Jako že to nechtějí vybrat v kombu, ale v checkboxech?
Obojí je na "bambilión" znaků (4,294,967,295 bytů ~4GB, cca ±380,000,000 slov)

**Comment by Sentinel65** [comment]
Nevím jestli to je bambilión znaků, ale když se kouknu k sobě do zdrojáku, tak je to tento kus kódu:

`<ul id="display-inline-block-example">
	<li>Vlastní:<br />
	        <?php
          $query = "select * from mail where slozka='vlastni' and oblast='".$_GET['or']."' order by email asc";
            $result=mysql_query($query, $link) or die('Query failed : ' . mysql_error($link));
            while ($row = mysql_fetch_assoc($result)) {
	    
	echo "<input type=\"checkbox\" name=\"emails[]\" value=\"".$row["email"]."\">".$row['email']."<br />";
            }
        ?> 
	</li>
	<li>SŽDC:<br />
	<?php
          $query = "select * from mail where slozka='szdc' and oblast='".$_GET['or']."' order by email asc";
            $result=mysql_query($query, $link) or die('Query failed : ' . mysql_error($link));
            while ($row = mysql_fetch_assoc($result)) {
	    
	echo "<input type=\"checkbox\" name=\"emails[]\" value=\"".$row["email"]."\">".$row['email']."<br />";
            }
        ?> 
	</li>
	<li>Ostatní:<br />
	<?php
          $query = "select * from mail where slozka='cd' and oblast='".$_GET['or']."' order by email asc";
            $result=mysql_query($query, $link) or die('Query failed : ' . mysql_error($link));
            while ($row = mysql_fetch_assoc($result)) {
	    
	echo "<input type=\"checkbox\" name=\"emails[]\" value=\"".$row["email"]."\">".$row['email']."<br />";
            }
        ?> 
	</li>
	<li><img src="clip.png" width="19" height="19" border="0"><input type="file" name="file1" size="10">
	</li>	
</ul>`

Je to ještě z plzeňské oblasti a tam jsme měli v těch checkboxech 33 emailových adres. Nedovedu si představit ten uživatelský komfort, vybírat z toho posuvného komba třeba pět adres, které jsou různě rozházené v tom seznamu.
Než označíš první tři a vyhledáš čtvrtou, už si nepamatuješ, co jsi vlastně označil.
U toho Přerova je těch adres 27.

**Comment by Sundin18** [comment]
To jsem psal, že je to tak nastavené na ty dvě pole. Zkrátka se nemusí trápit délkou textu.

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.32

**Comment by Sentinel65** [comment]
Dobre Petre, pokud k tomu budou pripominky, vyresime na porade 13.11.
