### ISSUE TITLE
Vývoj

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#52]
No a ted něco z dimenze sci-fi:
na poradě zazněl dotaz (požadavek), jestli by se VD v ZaMU při vyplnování položky Příkazy, když si rozklikne kombo se seznamem nepřiřazených příkazů, při najetí myši na konkrétní řádek s číslem nezobrazil nějakým způsobem obsah toho příkazu. V tuhle chvíli by se podle notifikace musel přepnout na pohled Příkazy a tam si v detailu prohlédnout konkrétní příkaz a následně se opět přepnout do pohledu ZaMU a zapsat záznam a vyplnit to konkrétní číslo, které si prohlížel.

**Comment by Sundin18** [comment]
Vyřešeno novým polem "Nepřiřazené příkazy".
