### ISSUE TITLE
Nový formulář Operativní příkazy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#53]
Požadavek vedoucích dispečerů PHA

Zapisují operativní příkazy do tabulky ve chvíli, kdy je z nějakého důvodu třeba buď úplně nebo částečně zrušit VDS (výluka služby dopravních zaměstnanců). Doplněním sloupce Poznámka to uděláme univerzální po obě CDP. **Oprávnění pro čtení a zápis u role** vdpha@szdc.cz a vdpre@szdc.cz, **pouze pro čtení u role** dpha@szdc.cz, dunl@szdc.cz, dpre@szdc.cz, ccdppha@szdc.cz a ccdppre@szdc.cz

Šlo by o klasický jednoduchý formulář s zápisem dat do DB.

Sloupce:

Číslo OP
Datum
ŽST (úsek) - 50 znaků
PO (předdefinovaný seznam PO v kombu)
Důvod  - 30 znaků
VDS (zrušeno nebo kráceno) - 30 znaků
Poznámka - 20 znaků

**Comment by Sundin18** [comment]
A jakpak to bude číslované? Jako je to u Příkazů?

**Comment by Sentinel65** [comment]
Číslování bude od 1, jestli k tomu pak ještě něco přifařime zatím nevím.  Každopádně se ale bude odesílat opět mail na příslušný sekretariát PO.

**Comment by Sentinel65** [comment]
Prosím tě Petře, ještě jedna připomínka k tomuto od vedoucích dispečerů.
Položku **VDS (zrušeno nebo zkráceno)** udělej jako **nepovinnou**.
Po uložení formuláře se nic neděje, až když se dá refres, tak se zobrazí záznam.

**Comment by Sundin18** [comment]
Ok. Ještě to není zcela hotové. Zatím jsem nahrál jen průběžný stav.

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.30

**Comment by Sentinel65** [comment]
Ještě se vrátím k tomu číslování. Definitivně to asi necháme na toho 13.11., ale myslím že bychom to měli udělat jako ty Příkazy, tzn. číslování lineárně od 1. Uvidíme, co na to řekne vedení.
Každopádně bych ještě teď dodělal možnost opravy a odeslání opravy na mail.
Teď jsem zkusil i já a pořád to ukládá do DB číslo OP jako 1.

**Comment by Sundin18** [comment]
Ok, udělám tedy ještě možnost opravy. Tím, že nevím jak číslovat, tak jsem tam zatím "natvrdo fiktivně" dal číslo 1, to je úmyslně.

**Comment by Sentinel65** [comment]
Dobře, dodělej tu opravu a zbytek se dozvíme na té poradě.

Až to budeš mít, tak se zkus podívat na tu #50

**Comment by Sentinel65** [comment]
Teď jsem se Petře domlouval s náměstkem a to číslování tedy vychází z D7, ÚD vydává OP všem na síti, VD vydává OP pro svoji vlastní oblast, takže to číslování bude třeba rozdělit podle oblastí a do toho mailu se bude muset objevit položka Pracoviště : VD UNL, VD PHA, VD PRE
Zatím není jasné, kdo všechno ten přehled OP bude mít ke kontrole a k nahlédnutí.
Ale do té tabulky přehledu bude třeba dát taky ten sloupec pracoviště, k tomu ještě sloupec se jménem, kdo vydal a u Datumu tam doplnit také čas pořízení záznamu.

**Comment by Sundin18** [comment]
Ten výběr pracoviště tam být nemusí, protože když je VD přihlášen, tak je jasné, pod jakou oblast patří, takže to číslo by se zjistilo přes tu oblast.

**Comment by Sentinel65** [comment]
Tak pokud to bude prohlížet někdo z oblasti asi ano, ale když zpřístupníme pohled pro va@szdc.cz pro všechny oblasti, pak tam budou stejná čísla OP a bude třeba jen rozlišit.

**Comment by Sundin18** [comment]
Tam bude oblast. Ale i proto si myslím, že by se to mohlo číslovat jako Příkazy.

**Comment by Sentinel65** [comment]
Leda by formát pořadového čísla byl jako u Příkazů: 1_PHA, 1_UNL atd.

**Comment by Sentinel65** [comment]
ok tak to  tak nastav

**Comment by Sundin18** [comment]
Hotovo, verze 19.10.31

**Comment by Sentinel65** [comment]
Zatím ok, pokud budou nějaké připomínky na té poradě, vrátíme se k tomu
