### ISSUE TITLE
Skryté záznamy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#56]
Jednak jsi tam asi zapomněl změnit verzi na 16 (pořád tam mám 15) a pak jsem zjistil, že Skryté záznamy zobrazují číslo 3 (pokud jsem to zkoušel v minulých dnech 2 byly pod CDP Praha a 1 pod CDP Přerov), ale u Prahy se zobrazuje pouze 1 místo dvou.

**Comment by Sundin18** [comment]
Pod Prahou jsou dva, nezapomeň že je defaultně nastaven filtr od-do na jeden týden, takže ten jeden už se nezobrazuje, protože neodpovídá zadanému filtru.

**Comment by Sentinel65** [comment]
nj sypu si popel na hlavu .-) je to ok
