### ISSUE TITLE
Problémy s tiskem

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#57]
Tak jsem teď byl u vedoucího dispečera a jsou tam dost značné problémy s tiskem u všech pohledů, kde se dá generovat PDF.

Zkoušeli jsme to na Chrome i na poslední verzi FireFox. Celkem to je nezávislé na tom, jestli tam podhodíš nějakou novou verzi nebo ne.
Zkusil jsem u obou prohlížečů odhlásit uživatele, vymazat cache, ukončit prohlížeč, nahodit.
A chová se to zcela náhodile, někdy to jde vygenerovat, jindy klikáš na tlačítko a nic se neděje, žádná reakce. Tak dám refresh stránky a zase to jde.

Tak mi napadlo, šlo by na to tlačítko ještě před ten příkaz, kdy se má to PDF vygenerovat, navěsit celkový refresh a pak teprve pustit to generování PDF ?

**Comment by Sundin18** [comment]
Opraveno (verze 19.10.24)

**Comment by Sentinel65** [comment]
Zatím OK
