### ISSUE TITLE
Zobrazování dat

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#59]
Pomalu se blížíme k ověřování uživatele přes doménu. Dneska jsem získal od ředitele další informace.

Celkem zásadní je tato:
kdo nebude přihlášený, neuvidí vůbec nic !

Horší zpráva je ta, že určitý okruh lidí (a nebude jich málo) z **OŘ a PO** bude mít přístup povolen. Tzn. vytvořit role pro tyto vyjmenované OJ s přístupem na pohled **ZaMU a SZO jen pro čtení**.

Další podrobnosti dodám po plánované schůzce obou CDP a O11 někdy po 12.-13. listopadu.

**Comment by zachyunl** [comment]
Já k tomu jenom doplním kluci, že bych rád abychom dotáhli do zmiňovaného data čili do 12. 11. , pokud to bude možné ověřování přes doménu. 16.11 odlétám pryč a na PC asi moc nebudu, vracím se až 2.12.

> Pomalu se blížíme k ověřování uživatele přes doménu. Dneska jsem získal od ředitele další informace.
>
