### ISSUE TITLE
Závady a mimořádné události - vyhledávání 

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#6]
Závady a mimořádné události. Funkce vyhledávání by měla fungovat v těchto polích: "Zapsal" (včetně změnových zápisů pod čarou), "Dopravce", "Číslo DP", "Popis", Vlivy".

**Comment by Sentinel65** [comment]
Petře, ještě jsme testovali vyhledávání podle polí, jak jsou vypsané zde o příspěvek výše a zjistili  jsme, že se nevyhledává v poli "**Číslo DP:**"
Zbytek je v pořádku. Mrkni na to. Díky

**Comment by Sundin18** [comment]
Ještě jsem to předtím nedělal, takže teď už by to mělo hledat i dle dispečeráku. Verze 19.09.7 

Trochu se do budoucna u tohoto pole bojím, že to bude "úzké hrdlo" až bude v DB tisíce záznamů. Uvidíme, případně by se to pak muselo rozdělit na více polí.

**Comment by Sentinel65** [comment]
Proč úzké hrdlo, nerozumím ? Těch DP zase tolik nebude a je otázka jestli to  máš jako null položku nebo prázdnou

**Comment by Sundin18** [comment]
To ne, ale, že to hledá v podstatě např. jeden znak přes pět sloupců v DB. Ten příkaz, který to dělá 'LIKE' je docela náročný na výkon, proto jsem třeba používal ten fulltext. Ale třeba se mýlím uvidíme ;-).

**Comment by zachyunl** [comment]
Uvidíme po nějakých větších testech. Než se to pustí do světa, tak chci na otestování nalít do databáze spousty záznamů (myšleno milióny) řádku, ať si pohrajeme s výkonem databáze jako takové. Jsou na optimalizaci různé nástroje, to ale bude až předfinální stav.

**Comment by zachyunl** [comment]
Připadá mi, že tam těmi opravami vznikl nějaký nový bug. Když dám slovo do vyhledávání osoby, tak to nenajde nic. Tuším že to je tím jak jsme nechali v defaultu nastavit zpětně 7 dnů? Takto nejsem de facto hledat ve všech záznamech od začátku pořízení že?

**Comment by Sentinel65** [comment]
Tak nějaká chybka tam zase je, ale v poli jméno se vyhledává, když dáš "PHA" nebo "disp" nebo "ved", tak se záznamy vyhledají a je označen řetězec v poli jméno. Pokud dám řetězec ze jména Jiří, tak se nic nechytne. Petře mrkni se na to.

**Comment by Sundin18** [comment]
Pokud je nastaven "časový" filtr a zároveň filtr na vyhledání slova, tak to logicky hledá průnik těch filtrů. Pokud tvoje jméno se vyskytuje v jiném intervalu než je vybraný čas, tak ten záznam nenajde.

**Comment by Sentinel65** [comment]
Hmmm, tak tam ten časový filtr nech, ale vypni ho, aby nebyl default, ale jenom jako další volba, zkusíme to tak.

**Comment by zachyunl** [comment]
Jirko čekal jsem až se vyjádříš, uvidíme jak se to osvědčí. Myslím že toto se dá kdykoliv změnit. Ono je otázka jak se to bude pak chovat, až to bude prohledávat databázi, kde bude několik miliónů záznamů. Tam je pak přesně jedno z doporučení optimalizace, a to zúžit výběr pro dotazy a to jsme měli tím defaultem na 7 dnů. Napadá mě ještě jedna z možností, ale nevím jak to bude náročné pro Petra. Nyní tam máme nějaké předvolené datum, dle logiky dnešní datum - 7. Pokud toto smáznu křížkem, tak to nemá na nic vliv. Bylo by možné po zrušení křížku, brát data od začátku databáze?

**Comment by Sentinel65** [comment]
No právě že ten filtr se tam nyní jeví jako pořád zapnutý, i když ho křížkem zrušíš.
Ale napadla mě ještě jedna věc, ale netuším, jestli to půjde vyřešit, jak myslím.
V tuto chvíli tam jsou vlastně 2 implicitní filtry "Zahájeno" a "7 dní nazpět". Napadlo mě, jestli to pujde, když použiju ten filtr "hledat", vlastně nejdříve ty dva především však ten časový automaticky vypnout. Pokud ne, tak jak jsem psal, nechal bych ho tam jako jednu z voleb s tím, že tam defaultně nebude žádný časový filtr a vybere se případně ručně.

**Comment by zachyunl** [comment]
Stejně mi přijde, že tam je bug. Když dám nyní v defaultu hledat "bouřce", tak to nic nenajde, přitom to je pořízeno 1.9 a je to první záznam nahoře.

**Comment by Sundin18** [comment]
Byla tam opravdu chyba. Vyhledalo to jen záznamy s dispečeráky. Už je to opravené. Filtr tam nezůstane, když se křížkem zruší. Co se týče komba "Zahájeno", není filtr, jen "řadič", to nic nefiltruje, jen řadí záznamy od nejnovějšího podle položky "Zahájeno".

**Comment by Sentinel65** [comment]
Ted to sice už vyhledává, ale píše to za jménem "Invalid date"

**Comment by Sundin18** [comment]
jj, teď s tím bojuju

**Comment by Sundin18** [comment]
Tak prosím o testování.

**Comment by Sentinel65** [comment]
Tak vypadá to, že už tro konečně funguje.

**Comment by Sentinel65** [comment]
Petře, netuším jestli to spolu souvisí a jak velké změny jsi dělal, ale testuji to vyhledávání iu na dispečeráky a ted jsem zjistil, že mi zase nejdou ty DP ukádat, tentokrát bez jakékoli hlášky, prostě klikám na "Odeslat" a nic se neděje. Zkusil jsem to vedle Chrome i ve FF.

**Comment by Sundin18** [comment]
To by nemělo mít žádnou souvislost. Mně to funguje. Zkus si prosím obnovit stránku.

**Comment by Sentinel65** [comment]
ok zavírám
