### ISSUE TITLE
Changelog - formát zobrazení

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#60]
Petře Ty ještě ten soubor ze zdrojáku nějak upravuješ? Myslel jsem, že to tam valíš přímo jak to poupravujeme s Jirkou? Koukám že tam je docela rozházené formátování.
![image](https://user-images.githubusercontent.com/47257941/67073989-84f4e900-f188-11e9-87d6-82c174b02e87.png)

Ze začátku souboru u Tvého zobrazení zmizely hvězdičky u jednotlivých odrážek a --Verze 19.09.06 2. září 2019 nemá zvýrazněný nadpis.

**Comment by Sundin18** [comment]
Jen ten text kopíruju. Tam doplním konce řádků

**Comment by zachyunl** [comment]
Aha já myslel, že děláš vždy synchronizace celého kódu local vs github a pak to valíš na server. Nebylo by to nejdnodušší, ať to nemusíš takto blbě kopírovat?
