### ISSUE TITLE
ZaMU - Přidat neprojetou trasu

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#61]
Když kliknu na tlačítko **Přidat neprojetou trasu** a místo abych vyplnil formulář dám **Storno**, tak v tom pravém rohu nahoře zmizí to číslo záznamu.

 
![_ZaMU_cislo_NT](https://user-images.githubusercontent.com/54531291/67306159-cffb5d00-f4f6-11e9-89a7-711edffbaa45.png)

**Comment by Sentinel65** [comment]
Teď jsem si všiml, že patrně i pod účty s rolí, kde je zakázána editace (konkrétně jsem teď na ccdppdha@szdc.cz), je klikací to číslo vpravo nahoře s kopírováním do schránky.

Lze to u těchto rolí zrušit, aby to nebylo klikací ?

**Comment by Sentinel65** [comment]
Účet **va@szdc.cz** (vedoucí analýzy) má dokonce v ZaMU tlačítko na **Přidat neprojetou trasu**

U všech těchto účtů je třeba, aby měli vše jen na koukání.

**Comment by Sundin18** [comment]
Opraveno verze 19.10.30

**Comment by Sentinel65** [comment]
Účet va@szdc.cz (vedoucí analýzy) má v **Neprojetých trasách** stále tlačítko **Smazat**.

**Comment by Sundin18** [comment]
hotovo

**Comment by Sentinel65** [comment]
ok
