### ISSUE TITLE
Zvýraznění rozdílových změn opraveného záznamů ZaMU

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#62]
Petře již jsme spolu o tom hovořili a včera jsem potkal Milana Jakubce, který tuto funkcionalitu poptává pro ústředního dispečera a ptal se zda se nám to podaří implementovat. Z jejich pohledu by to bylo velké usnadnění denní práce se šedivákem.

**Comment by zachyunl** [comment]
Petře ještě jsem k problematice něco dohledal, jak jsme se včera o tom bavili. Šel bych touto cestou zobrazení https://cs.wikipedia.org/w/index.php?title=Hartova_v%C3%A1lka&diff=next&oldid=7872680.

Jinak php má implementován diff a jsou ještě další podpůrné utility, koukal jsem, že to umí i Javascript a na githubu jsou různá rozšíření např. https://github.com/chrisboulton/php-diff. Najdeš tam toho spousty.

**Comment by Sundin18** [comment]
Připraveno, verze 19.11.0. Je to funkční na 39 i 36.
