### ISSUE TITLE
Importní soubor uživatelů

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#64]
Petře ve středu dostanou zaměstnanci SŽDC pokyn, aby nám předali v elektronické formě seznam zaměstnanců, kteří budou mít přístup do nového šediváku. Jsme schopni definovat přesný formát, aby se to dalo přímo importovat do systému? Co všechno potřebujeme za údaje a umíme i z tohoto nastavit rovnou role?

**Comment by Sundin18** [comment]
Ideálně v SQL příkazu :)...Ne, jasný, asi nejsnadněji v excelelové tabulce. Sloupečky v pořadí jméno, příjmení, doménové jméno (čím se přihlašují do pc), email, oblast, prac.funkce. Přikládám jako přílohu vzor tabulky.
![image](https://user-images.githubusercontent.com/20888257/68482405-d1888d00-0239-11ea-9ecc-03f6a20f78d6.png)

**Comment by zachyunl** [comment]
Otázka do diskuze a to migrace do uadfd01. Bylo by složité tam mít v jedné tabulce ještě navíc pole doména uadfd01? Myslím v DB a pak samo v požadovaném excelu. Vyhnuli bychom se určitým komplikacím po dobu přechodu, který neumíme nikdo říci jak dlouho bude trvat.

**Comment by Sundin18** [comment]
určitě jde :-)

**Comment by zachyunl** [comment]
Super tak půjdeme cestou multidomén. Můžeš si to otestovat v neděli na sobě. Heslo do uadfd01 máš díky vpn. Jde se pod tímto účtem přihlásit na PD3 i jinde do PC.

**Comment by Sundin18** [comment]
To bude vlastně trochu problém, protože mám v každé doméně jiné jméno

**Comment by zachyunl** [comment]
To nejsi sám, já např. také alespoň vidíš proč probíhá konsolidace pouze do 1 domény v rámci SŽDC. V čem máš problém? Algoritmus? Vždyť by to měla být jenom dvojitá podmínka oproti 1. Porovnej sloupec s první doménou, pokud ne, porovnej druhý sloupec s doménou uadfd01. Pokud ne, tak jdi na dalšího uživatele?
