### ISSUE TITLE
Změny/doplnění po poradě

### ISSUE THREAD

**Issue by Sundin18** [Sundin18/backend#65]
- stav skryté záznamy může vidět pouze vedoucí dispečer, analýza a kontrolér CDP **(HOTOVO)**
- zrušit všechny kategorie (filtry) fakturace **(HOTOVO)**
- zrušit konec věty v emailu u zaslání DP **(HOTOVO)**
- přidat checkbox "fakturace" + "popis fakturace" k zápisu ZaMU **(HOTOVO)**
- přidat filtr Fakturace, aby se tyto záznamy daly snadno najít (vzhledem k tomu, že jsme to ze seznamu Druh mimořádné události vyhodili, tak bych to dal do sekce Stav jako Fakturace, kde se zobrazí záznamy, které mají zaškrtnutý checkbox a příznak Ano) **(HOTOVO)**
- zrušit "trať" v odřeknutých trasách **(HOTOVO)**
- opravit bug u filtru datumu v odřeknutých trasách a SZO **(HOTOVO)**
- vytvořit novou stránku "rozvrh pohotovosti". Formulář bude obsahovat, kdo a kdy MU nahlásil, pole O18, OŘ, CDP, ED s časem kdy to bylo a komu hlášeno, popis **(HOTOVO)**
- vymyslet aktualizaci číselníku dopravců
- nová role pro pracoviště Ústředního dispečera (oprávnění vidět ZaMU, SZO a Operatovní příkaz za všechny oblasti ?? + v ZaMU mít klikatelný odkaz označujicí opravu / změnu záznamu z důvodu porovnání obsahu) **(HOTOVO)**
- nová role kontrolér OŘ (oprávnění vidět záznamy v ZaMU, SZO a Operativní příkaz za oblast spadajicí pod příslušné CDP) **(HOTOVO)**
- **chtělo by to vyřešit ten problém s ověřením ntlm, teď jsem to zkoušel z Firefox na tu 39 a objevil se mi tam dialog pro ověření účtu, což by nemělo, ale nefunguje tam ani napsat jedno písmeno, ani když dám zrušit. Funguje pouze když tam opravdu zadám účet s doménou a heslo. V tuhle chvíli je také pro účely testování špatné, že se nemohu přepínat mezi rolemi a oblastmi, nemám přístup do administrace ani se mi po přihlášení nenabídne nějaká volba.**

**Comment by Sundin18** [comment]
Ta 36 je opravená, lze se do ní opět přihlašovat pod různými rolemi.

**Comment by Sentinel65** [comment]
Tak jsem mluvil s ředitelem, co se týká SZO, tak již vyšel nějaký dokument, který by měli mít provozní dispečeři v Knize normálií k podpisu. V podstatě by snad stačilo přidat jedno textové pole s názvem Poznámka, kam by VD dopsal volnou formou, jestli se nějak domluvil na prioritě 1 a 2, nebo bylo něco slíbeno a dostali se tam s nějakým věžtším časovým zpožděním. Ono toho asi moc nebude, ale aby tam byl další sloupec. Když se na to teď dívám, tak v tom vstupním formuláři problém nebude. Dali bychom ho pod ten řádek: Datum žádosti - Žádal - Datum Vyhlášení - Vyhlásil.
Jenom  netuším, kam narvat ten sloupec s Poznámkou do tabulky Sumář zrušených aktivací. Tam už se toho moc nevejde. Leda tam udělat Sloupec P jako Poznámka a do něj ikonu I a najetím na tu ikonu by se zobrazil obsah té poznámky jako Tool Tip.

**Comment by Sundin18** [comment]
Připravena role pro ústředního dispečera, lze vyzkoušet na 36 (ud@szdc.cz)

**Comment by Sentinel65** [comment]
Na 36 jsem zkoušel změnit data pro test vůči Ústřenímu dispečerovi pod účtem VDUNL, nelze ukládat data, je tam červená chybová hláška.

**Comment by Sundin18** [comment]
opraveno, nevím proč, ale musel jsem smazat jeden sloupec v DB a pak ho znovu vložit, přitom byl nastavený úplně stejně jako na 39. Někdy to jsou záhady, že člověk nechápe.

**Comment by Sentinel65** [comment]
ok

**Comment by Sentinel65** [comment]
Na 36 v Příkazech není v prvním kombu seznam pracovišt

**Comment by Sundin18** [comment]
opraveno

**Comment by Sundin18** [comment]
přidána stránka s nehodovým rozvrhem (nehody), verze 19.11.05

**Comment by Sentinel65** [comment]
Peťo, udělej v těch Nehodách projení na ten záznam v ZaMU

**Comment by Sundin18** [comment]
Hotovo (verze 19.11.06)
