### ISSUE TITLE
Zamítnutý přístup

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#68]
Na http://10.99.164.39/oorp/oorp-production/login/ mi to hodilo hlášku, že nemám oprávnění používat tuto aplikaci.

Jsem na svém NTB (už pod doménou UADFD01, IP adresa stejná) pod svým účtem UADFD1\Horkyj

**Comment by Sundin18** [comment]
To bylo tím, že jsem neznal tvoji UADFD doménu. Doplnil jsem ji do DB, tak teď ti půjde ;-)

**Comment by Sentinel65** [comment]
Pořád to samé Peťo

**Comment by Sundin18** [comment]
jsem zkopíroval tu doménu, jak jsi napsal a ona je správně 01 asi. Tak jsem to změnil, zkus to teď.

**Comment by Sentinel65** [comment]
Jo UADFD01 :-) už to jde
