### ISSUE TITLE
Filtry 

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#7]
Filtry:   vpravo, jak máš sekci "Stav", jsou použity "checkboxy", použil bych zde pro to filtrování raději "button" coby přepínač. Vybíral bych buď to nebo ono. "Checkbox" mi dává na výběr ve smyslu, chci vidět to a ještě toto a k tomu ještě toto (jak to je v sekci Druh mimořádné události). Tady bych v tom filtru raději viděl vše pouze z toho jednoho zvoleného filtru. Doplnil bych tam ještě třetí volbu "Šetření ukončeno", druhou volbu "V šetření" bych přejmenoval na "Šetření trvá", aby to korespondovalo s textem, který používáme přímo v záznamech. Ta čísla s počty jsou pro přehled dobrá.

Pokud si někdo bude "hrát" a začne používat to řazení a filtry, tak ten kdo není přihlášen (klasicky to budou ti, kteří chtějí jen "čumět" a těch nebude málo), tak ty záznamy o aktualizaci tam nevidí, pak by tam asi neměl ani vidět v tom prostředním kombu tu volbu "Aktualizováno", protože nebude tušit, co a jak se mu řadí, když to nevidí. Bychom se měli domluvit, jestli to "Aktualizováno" bude vůbec nějak smysuplně využíváno nebo to z toho komba odstranit. Tak teď jsem byl na obědě a náhodou jsem tam potkal Milana Jakubce a pobavili jsme se a vylezlo z něj, že to řazení dle "Aktualizace" záznamů byl právě požadavek ústředního dispečera.

**Comment by Sundin18** [comment]
Já bych se přimlouval za "checkboxy". V podstatě to jen "rozšiřuje" možnosti "buttonů", není to nic proti ničemu. Vždycky se dá vybrat jen jeden druh. 

Řazení podle aktualizace bylo i přání analýzy tady v Ústí. Já myslím, že to není nic proti ničemu. I když nepřihlášený uživatel nevidí, kdo kdy aktualizoval. Třeba si může všimnout změny na základě textu.

**Comment by Sentinel65** [comment]
No právě, že když se u těch checkboxů zapomeneš a neodškrtneš, tak ti to nebude souhlasit. A ještě bych i k těm typům závady přidal ta čísla, značící počet.

To řazení v tom prostředním kombu tedy necháme, jak je.

**Comment by zachyunl** [comment]
Řazení podle aktualizace bych nechal, dává mi to smysl.

**Comment by Sundin18** [comment]
> No právě, že když se u těch checkboxů zapomeneš a neodškrtneš, tak ti to nebude souhlasit. A ještě bych i k těm typům závady přidal ta čísla, značící počet.
> 
To mohu zapomenout i buttonů. Bude tam muset být button "vše", který bude defaultně vybrán a pak, na něj bude potřeba kliknout, abych zrušil jiný výběr. To vyjde nastejno, jestli mám odškrnout checkbox nebo zaškrtnout button.

**Comment by Sentinel65** [comment]
Myslím si, že ne ...
Není to nastejno, u té volby "button" volíš úmýslně  jen ten jeden konkrétní filtr, jiný se ti do toho neplete.
U "Checkboxu" si můžeš vybírat z několika nabízených filtrů a kombinovat je spolu dohromady, to u "button"  nejde a v tom je právě ten rozdíl.

**Comment by Sundin18** [comment]
Ju to chápu, ale nevylučuje to tu volbu vybrat jen jeden jako u buttonu, naopak to rozšiřuje a třeba můžu hledat záznam u kterého si nejsem jist jestli byl zapsán jako porucha SZZ nebo TZZ (to mě tak napadlo, třeba se to neděje)

**Comment by Sundin18** [comment]
A moje chyba, ty myslíš filtr ke "stavu", já pořád měl na mysli filtr "druh MU"

**Comment by Sentinel65** [comment]
Ano :D

**Comment by Sentinel65** [comment]
Nakonec jsme se přeci jen domluvili :-D

**Comment by Sundin18** [comment]
Ale i tak tam budu muset přidat button "vše", aby se pak daly zobrazit všechny záznamy bez vybraného filtru.

**Comment by Sentinel65** [comment]
Ano, to bude třeba, jinak k té sekci MU s těmi checkboxy doplň prosím tě taky ta čísla s počtem záznamů

**Comment by Sundin18** [comment]
Pozměněno a doplněno. Verze 19.08.1

**Comment by Sentinel65** [comment]
Tak jsem na to koukal a mám k tomu několik připomínek. Předně jsem si uvědomil, že bude potřeba ty požadavky specifikovat opravdu podrobněji a přesněji. Zrovna u tohoto jsem přehlédnul souvislost a provázanost s požadavkem **#10**, kde jsem psal o doplnění položek do formuláře - Zastavený provoz. V momentě, kdy bude dopracovaný i požadavek **#10**, tak je potřeba v sekci **Stav** přidat ještě další položku (radio button):

: Vše (číselná notifikace ne)
: Zastavený provoz (číselná notifikace ano)
: Neukončené (číselná notifikace ano)
: Šetření trvá (číselná notifikace ??)
: Šetření ukončeno (číselná notifikace ne)

Tak a teď k tomu, co jsi udělal za změny v sekci **Stav**. Ta číselná notifikace tam nyní funguje špatně. Klikám-li na jednotlivé přepínače (radio buttony) v této sekci, tak se mi tam mění hodnoty v té číselné notifikaci (vyzkoušej si to). To je špatně. Hodnoty se musí počítat pouze z nastavení filtru v sekci **Oblast** ! Pokud tam něco označím / odznačím, tak **pouze** podle toho by se měly měnit hodnoty té číselné notifikace v sekci **Stav.** Zpět k sekci **Stav**. Když jsem se nad tím zamyslel, tak by bylo vhodné, aby ta číselná notifikace byla pouze u volby "Zastavený provoz", "Neukončené" a možná "Šetření trvá". Tady záleží na tom, jak se k tomu postaví AJŘ v Praze, protože ty tam dneska s tím zásadně nic nedělali tzn. že za pražskou oblast tam bylo u všech záznamů "Šetření trvá". Pak by nemělo asi smysl, aby se tam ten údaj objevoval.
Sekce **Druh mimořádné události** tady bych prosil tu číselnou notifikaci přesunout **za název položky**, jako je to v sekci **Stav**. Jednak to "kosmeticky" nevypadá moc dobře, když nahoře to je vpravo za textem položky a dole vlevo před textem položky a pak mě napadlo, co když tam bude víceciferné číslo a proto jsem tam nadatloval to "Narušení výluky" a jak jsem předpokládal, tak se celý ten řádek hnul doprava.

**Comment by Sundin18** [comment]
Upraveno. (Verze 19.08.1)

**Comment by Sentinel65** [comment]
No pořád to nefunguje, jak by mělo. To co jsem psal o sekci **Stav**, platí pochopitelně i o sekci **Druh mimořádné události** tzn. ta **číselná indikace se bere pouze** podle filtru v sekci **Oblast**.
Tady zase zaškrtnu checkbox "Narušení výluky" a ostatní číselné hodnoty se mi vynulují, to je špatně.  Jestli by šlo tam dát ta čísla s bílou černou grafikou, jak jsi je měl přestím vlevo před těmi checkboxy, přišlo mi to decentnější, to modré už je jak omalovánky.

**Comment by Sundin18** [comment]
Změněno (verze 19.08.2)

**Comment by Sentinel65** [comment]
Šikula, teď už to funguje, jak má. Požadavek možno uzavřít ...
