### ISSUE TITLE
Přihlášení

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#71]
Ahoj Petře,

ráno se mi ozval vedoucí dispečer. Po přihlášení na Šedivák v prohlížeči Chrome se mu v přihlášení objeví u funkce text Head Dispatcher místo českého textu Vedoucí dispečer. dělá mu to na obou PC.

![image](https://user-images.githubusercontent.com/54531291/70844411-055e6000-1e41-11ea-8e69-929a876d86f9.png)

**Comment by Sundin18** [comment]
opraveno
