### ISSUE TITLE
10.99.164.38/rp/oorp-production

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#72]
záložky Příkazy:
- DP, ST i PZ vyplním. dám uložit, hodí to vpravo dole červenou hlášku, uložený záznam se zobrazí až po refresh stránky (to samé platí o opravě)

záložka Neprojeté trasy
- při vyplnění se záznam uloží, při opravě to hodí červenou chybovou hlášku err 500, záznam se neuloží

**Comment by Sentinel65** [comment]
Po změně verze PHP, je to již OK

Nově jsem dneska zjistil při psaní toho manuálu, že kontrolér CDP nevidí pohled PMD

**Comment by Sundin18** [comment]
Hotovo (verze 19.12.02)

**Comment by Sentinel65** [comment]
Tak bohužel máme zase problém :-(

Na Microsoft Edge nejdou zapisovat záznamy v Neprojetých trasách, chyba kód 500, na Chrome to funguje

![image](https://user-images.githubusercontent.com/54531291/71069864-e120bd00-2179-11ea-8690-f52bb83b87e2.png)

**Comment by Sundin18** [comment]
A na 39 to v edge funguje?

**Comment by Sentinel65** [comment]
Stejný problém je i na serveru 39 - ZaMU, Příkazy, PMD, SZO nejde ukládat.
