### ISSUE TITLE
Manuál nového Šediváku

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#73]
Tak jsem dneska ještě projel ten manuál, opravil nějaké překlepy a trochu učesal slovosled.
Šloby to převést do formátu html a pověsit to jako odkaz hned vedle toho HelpDesku ?
[Popis aplikace Šedivák.docx](https://github.com/Sundin18/backend/files/3977108/Popis.aplikace.Sedivak.docx)

**Comment by zachyunl** [comment]
Pověsíme aktuální verzi na github do kódu, ať se udržuje aktuální verze pouze na 1 místě. Může na tom pracovat průběžně kdokoliv z nás 3 a udržíme aktuálnost.

**Comment by Sundin18** [comment]
Upraven pro zobrazování, verze 19.12.04
