### ISSUE TITLE
SZO

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#76]
Petře jedna kosmetická, netuším jak se to teď zobrazuje na vetším monitoru - možná to tam je v pořádku, testuji z NTB, ale v tomto pohledu první dvě tabulky (zvláště ta druhá prostřední) sloupec OŘ -  je tam nutné to zalamování textu v tomto sloupci, když těch sloupců je tam méně a vešlo by se to v pohodě na řádek v tabulce ? V té třetí je to jasné, tam je 8 sloupců, ale v té prostřední jen 5.

**Comment by Sundin18** [comment]
Ten sloupec rozšířit můžu, ale potom ti zase nebude sedět zarovnání sloupečků tabulek pod sebou jak jsi chtěl. Já mám HD rozlišení, což je jako u nás v práci tuším a zatím se vejde i PO České Budějovice na jeden řádek.
![Snímek obrazovky pořízený 2019-12-26 11-45-05](https://user-images.githubusercontent.com/20888257/71472982-74d73680-27d5-11ea-85be-b0657594def8.png)

**Comment by Sentinel65** [comment]
OK, nech to bejt, když zmenším velikost v prohlížeči na 80 procent, tak je to v jednom řádku. Na vetším monitoru s vyšším rozlišením to bude ok.
