### ISSUE TITLE
Replikace databází

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#78]
Ahoj kluci, tak se mi konečně po delším časovém vývoji podařilo uchodit replikaci DB. 
Funguje to následovně pokud se něco zapíše, případně změní v DB na form.rp.szdc.cz (master), tak se to automaticky zreplikuje na 10.99.164.38 (slave). 
Vše probíhá na úrovni binárních logů, takže to je nezávislé na aplikaci šediváku. Samozřejmě se nám to propíše i do aplikace. Zkusil jsem si cvičně 2 události a vše proběhlo. 

Případně si to otestujte také. 

Předpokládám, že to také pustíme rovnou při přechodové noční.

Ještě bych rád rozeběhnul pro replikaci Jail (https://en.wikipedia.org/wiki/FreeBSD_jail), což je oddělené prostředí od kernelu, ale to asi až později. Zde jsem ještě nezačal načítat dokumentaci, všechny tyto věci jsou dosti časově náročné na nastudování a následné otestování a implementaci. Jsou to desítky hodin a do přechodové noční bych rád udělal jiné věci. Ten Jail je něco jako virtualizované prostředí uprostřed systému, takže bych mohl umístit do naší virtuálky jail jenom s DB, kam se nám bude replikovat ostrá databáze.

**Comment by Sentinel65** [comment]
Jirko, tak jsem to právě teď 9:15 porovnal a ta data nejsou shodná, tzn. nevím jestli se to replikuje okamžitě při změně nebo v nějakém čase.

![image](https://user-images.githubusercontent.com/54531291/71639465-5363c800-2c77-11ea-8454-9bbeaf737808.png)

a ta 38

![image](https://user-images.githubusercontent.com/54531291/71639469-68d8f200-2c77-11ea-8fbe-38aa3f2a8af7.png)

**Comment by zachyunl** [comment]
O problému vím, bohužel replikace spadla na obě záložní databáze. 
![image](https://user-images.githubusercontent.com/47257941/71639554-ebae7c80-2c78-11ea-93a5-f3a8280409ae.png)

Zde si můžeš zkontrolovat stav a je tam vidět přímo i chyba na které to vyhučelo, hledal jsem to na netu a doporučený postup je export dat ze staré a import do nové a spuštění nové replikace. Tzn. odstavení cca na 5min hlavního šediváku. Možná to udělám dnes večer, nebo zítra přes den. Nechci teď do toho hrabat, protože se s tím všichni učí.

Jinak primární záloha běží na 10.99.164.33, zde to je bez šediváku a je tam připravena jenom MariaDB pro synchronizace. Je tam stejná chyba při rozpadlém spojení.

**Comment by Sentinel65** [comment]
OK, dej info, až to bude srovnané, porovnám to pak.

**Comment by Sentinel65** [comment]
No nevím, porovnávám ostrý server s tou 38 a pořád mi to nesedí, netuším, jestli to náíhodou není i tím, že tam nejsou stejné verze (na té 38 je 19.12.02)
Každopádně teď mám pocit, že tam je něco špatně.
Na té 38 je u Prahy poslední záznam 11:00 záznam 41665

![image](https://user-images.githubusercontent.com/54531291/71640629-e0198080-2c8d-11ea-9bc5-d55e9aee0280.png)

Paradoxně to číslo záznamu na ostrém serveru nemohu najít (41665 v 11:00))

**Comment by Sentinel65** [comment]
Tak beru zpět, je to vše OK, nevšiml jsem si, že jsem měl u té 38 zapnuté ty spodní filtry vpravo. Shodil jsem prohlížeč, znovu nahodil obě stránky, zkontroloval filtry a nastavil je na stejno a záznamy už jsou v pořádku.

**Comment by zachyunl** [comment]
Rozpadnutá replikace z důvodu stejné tabulky jako naposledy.
![image](https://user-images.githubusercontent.com/47257941/72202406-62a8f980-345f-11ea-82db-5946eb35b0d5.png)

Na masteru byl restart MariaDB, který rozsypal DB a proto došlo i ke shození replikace vůči slave.
K problému rozsypání DB na masteru nám log ukazuje tyto řádky:
`Starting shutdown...
2020-01-10 23:03:55 0 [Note] InnoDB: Dumping buffer pool(s) to /var/db/mysql/ib_    buffer_pool
2020-01-10 23:03:55 0 [Note] InnoDB: Instance 0, restricted to 2003 pages due to     innodb_buf_pool_dump_pct=25
2020-01-10 23:03:55 0 [Note] InnoDB: Buffer pool(s) dump completed at 200110 23:    03:55
2020-01-10 23:03:56 0 [Note] InnoDB: Shutdown completed; log sequence number 202    264257; transaction id 29130
2020-01-10 23:03:56 0 [Note] InnoDB: Removed temporary tablespace data file: "ib    tmp1"
2020-01-10 23:03:56 0 [Note] /usr/local/libexec/mysqld: Shutdown complete
`
Je to na větší analýzu, zatím mám domněnku, že příčina mohla být, že restartem bylo něco smáznuto z paměti a tím došlo k nekonzistenci dat, nebo samotný restart narušil DB či něco úplně jiného.

**Comment by zachyunl** [comment]
Udělán manuál pro nastavení replikací DB - https://github.com/Sundin18/backend/blob/master/doc/synchronizace%20DB.md
