### ISSUE TITLE
Změna číslování PMD

### ISSUE THREAD

**Issue by Sundin18** [Sundin18/backend#79]
Číslování PMD je "vynulováno" k začátku nového roku, dle CDP Přerov.
Hotovo (verze 19.12.07)

**Comment by zachyunl** [comment]
To číslování nuluješ ve všech oblastech nebo jenom pro Přerov?

**Comment by Sentinel65** [comment]
Číslování se teď bude nulovat ve všech oblastech podle Přerova, které to nuluje už někdy od roku 2016 dle staré DB, Praha se přizpůsobila, Ústí s tím začíná, dělali to na papíře.
