### ISSUE TITLE
Závady a mimořádné události - refresh

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#8]
Závady a mimořádné události. Objevil jsem chybku. Pod účtem aunl@szdc.cz jsem 3x po sobě upravoval záznam, abych odzkoušel to řazení "Aktualizováno" v prostředním kombu, no a všiml jsem si, že u ostatních záznamů se mi ten jejich poslední (jako nejčerstvějsí) přepsal datumem, časem, jménem a CN jako u toho, který jsem fyzicky měnil. Ono se to dokonce chová vůbec podivně :grinning: když si dám na té stránce refresh, tak se mi ty poslední změnové záznamy přepíšou aktuálním časem a to i když se odhlásím od účtu aunl a přihlásím se jiným třeba vdunl. Dám refresh a opět se mi tam přepíše ten datum a čas. Dám změnu u jiného záznamu a přepíšou se mi časy u všech posledních změnových záznamů
![MU01](https://user-images.githubusercontent.com/47257941/63690462-fe1d3300-c80c-11e9-9d94-e4e3955a037c.png)

Přepsání u jiných záznamů, než jsem měnil
![MU02](https://user-images.githubusercontent.com/47257941/63690512-260c9680-c80d-11e9-9f8d-43a1aba69ac5.png)

**Comment by Sundin18** [comment]
Opraveno. Verze 19.08.1

**Comment by Sentinel65** [comment]
ok, možno uzavřít
