### ISSUE TITLE
Notifikace pro ÚD

### ISSUE THREAD

**Issue by Sundin18** [Sundin18/backend#80]
Navrhuji, že by při vytvoření/změně záznamu v ZaMU byl zároveň ústřednímu dispečerovi poslán email, jak byli zvyklý s tím, že by bylo v textu emailu napsáno jen o které číslo (ID) záznamu se jedná a on už by si to vyhledal třeba pomocí zobrazení rozdílů, co se změnilo.

**Comment by Sundin18** [comment]
Tak už to mám na téměř hotové. Jen potřebuju vědět na jakou emailovou adresu se to má zasílat. Díky.

**Comment by zachyunl** [comment]
Petře dej tomu po doplnění již nové číslo verze s rokem 2020 - 20.01.0

**Comment by Sentinel65** [comment]
Petře, doplň pro ty ÚD oprávnění, aby viděli také pohled **Neprojeté trasy**.

**Comment by Sentinel65** [comment]
Petře, ta adresa na posílání těch závad a veškerých změn v závadách je:
OORPhldisp@szdc.cz
Je to adresa na hlavního dispečera.

**Comment by Sundin18** [comment]
Ok, pokusím se to dodělat ještě dnes.

**Comment by Sundin18** [comment]
Zpřístupnění stránky "Neprojeté trasy" pro ÚD hotovo (verze 20.01.0)

**Comment by Sentinel65** [comment]
Ještě zprovoznit ty maily.

**Comment by Sundin18** [comment]
Hotovo, stejná verze 20.01.0

**Comment by Sentinel65** [comment]
Petře díky, mělo by to být už vše ok, mluvil jsem s ním po telefonu a udělal malou změnu, mail jim přišel.

**Comment by Sentinel65** [comment]
Petře, ještě bych v těch mailech změnil ten text minimálně v tom předmětu tak aby bylo patrné, že jde o nový záznam nebo změnu záznamu asi tak, jako to máme v Příkazech.  Bude to pro ty dispečery jednoznačnější. Teď z toho mailu opravdu bez nějakého porovnání nepoznám, jestli jde o nový záznam nebo změnu.
Navrhuji Aplikace Šedivák záznam #12345, případně Aplikace Šedivák záznam #12345@změna

**Comment by Sundin18** [comment]
Hotovo

**Comment by Sentinel65** [comment]
Ok
