### ISSUE TITLE
ZaMU - zobrazování titulu u jména

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#81]
Petře teď ráno projíždím záznamy a všimnul jsem si, že u některých záznamů v ZaMU v položce zapsal se nezobrazí titul. Přitom u starších to máme, tam nevím jestli to nebylo importem? 
![image](https://user-images.githubusercontent.com/47257941/71639056-8e61fd80-2c6f-11ea-89ca-163f0d512595.png)

**Comment by Sentinel65** [comment]
Importem to není, protože se ten titul neobjevil ani po zapsání záznamu po půlnoci s datem 1.1.2020 (nikoliv datum zapsání). Naopak v opravě pod záznamem tam titul JE.

**Comment by Sundin18** [comment]
U starého se to ukládalo s titulem, u nového ukládám jen jméno. To tedy změním, aby se tam ukládal i titul.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.0

**Comment by Sentinel65** [comment]
Petře, otevírám to znovu, stejný problém máme i u Příkazů, zde se nám ty tituly také nezobrazují viz.Jan Kozumplík DP 15

![image](https://user-images.githubusercontent.com/54531291/71740362-47852b00-2e5c-11ea-9ab8-26127c1c2dd2.png)

**Comment by Sundin18** [comment]
hotovo, verze 20.01.04, je to na 38

**Comment by Sentinel65** [comment]
Na 38 ok, počkáme až se tam ukáží v záznamech další titulanti a pak to překlopíme na ostrý.
