### ISSUE TITLE
Manuál

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#82]
Doplnit do manuálu u PMD, že se počítadlo resetuje na nulu s novým kalendářním rokem

**Comment by zachyunl** [comment]
Můžeš to přímo dopsat, zde je poslední zdroj backend/doc/Popis_aplikace_Sedivak.html a Petr to pak jenom nahraje na server.

**Comment by Sentinel65** [comment]
OK, dopsáno přímo ve zdroji manuálu.

**Comment by Sundin18** [comment]
Hotovo

**Comment by zachyunl** [comment]
Doplnit vyhledávání v ZaMU dle ID, dopsat roli vyšetřovatel a možnosti co má přístupné.

**Comment by Sentinel65** [comment]
Petře, manual.md je aktualizován, doplnil jsem tam, co psal Jirka, je možné ho podhodit.

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.02)

**Comment by Sentinel65** [comment]
Soubor manual.md opět aktualizován, dopsáno rozšíření formátu přílohy v ZaMU při uzavřené položce Šetření ukončeno na soubory ms word a excel. Doplněny filtry zobrazení dat v Neprojetých trasách.

**Comment by Sentinel65** [comment]
ok

**Comment by Sentinel65** [comment]
Petře, až to půjde, podhoď ten manuál ještě jednou. V Nehodách tam je ještě jedna úprava.

**Comment by Sentinel65** [comment]
V manuálu /doc/Popis_aplikace_Sedivak.html jsem doplnil do bodu 2 Příkazy bod 8 ohledně Nepřiřazených příkazů tento text:


<li>
                            Přidána funkcionalita, která umožní nastane-li situace, kdy se vydá Příkaz, který nelze objektivně přiřadit k žádnému uloženému záznamu v ZaMU a nemá žádnou příčinu pro založení záznamu nového, aby VD rozhodl, že 
                            tomuto Příkazu dá <strong>příznak</strong>, aby se <strong>nepřiřazoval</strong>. Toto se provede <strong>zaškrtnutím checkboxu</strong> u položky <strong>Nepřiřazovat k záznamu</strong> (poslední položka v detailu
                            Příkazu, kterou vidí POUZE role <strong>VD</strong> a <strong>analyzátor</strong>). Příkaz po obnovení stránky zmizí z přehledu Nepřiřazených příkazů, v pohledu <strong>Příkazy</strong> bude normálně vidět v seznamu.
                            Při využití této funkcionality nejsou příkazy odesílány emailem na adresy PO resp. OŘ.
                        </li>

**Comment by Sentinel65** [comment]
Možno aktualizovat Manuál, doplněn odsek 9 v bodě 2. Příkazy

<li>
                            Na tabulkou jsou pole pro vyhledání konkrétního čísla příkazu, filtr pro zadání datumu nebo konkrétního období od - do, pole pro vyhledání jména, kdo příkaz vydal, filtr pro zadání pracoviště, které příkaz vydalo. 
                            V záhlaví samotné tabulky se seznamem lze myší kliknout na sloupce <strong>Číslo</strong> nebo <strong>Datum události</strong>, čímž dojde k vzestupnému resp. sestupnému řazení záznamů tabulky dle těchto sloupců. 
                            Poslední nastavení si prohlížeč pamatuje.
                        <-li>
