### ISSUE TITLE
Filtry

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#83]
Kluci, zatím jsem to s nikým z VD a PD neprobíral, Petře mohl by ses k tomu jako PD vyjádřit i sám.
Osobně bych chtěl změnu v ZaMU u fitrů a to takovou, aby si stránka např. pomoci cookies pamatovala moje nastavení filtru.
Pokud si nastavím například filtr Řadit dle a vyberu Pořadové číslo nebo Aktualizováno, tak při jakémkoli refresh stránky nebo přepnutí do jiného pohledu a následném vrácení se do pohledu ZaMU, tak se mi tam vždy nastaví filtr Řadit dle: Zahájeno.
Je zajímavé, že toto funguje, pokud použiji filtry vpravo ze sekcí Stav, Oblast nebo Druh mimořádné události.

**Comment by Sundin18** [comment]
Já to moc nepoužíval. Navíc člověk byl zvyklý, že je to seřazeno jen podle "Zahájeno". 
Jediný filtr k zapamatování jsem udělal na výběr oblasti. Tak to tedy rozšířím na všechny filtry. Jen si nejsem jist, jestli to stihnu ještě dnes.

**Comment by Sentinel65** [comment]
Petře, tohle není nejvyšší priorita. Potřebujeme opravit ty věci ohledně ústředního dispečera (posílání mailů a zobrazení Neprojetých tras).

**Comment by Sentinel65** [comment]
ok
