### ISSUE TITLE
Nová role - Vyšetřovatel

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#85]
Pro Odbor O18 je třeba založit novou roli - vyšetřovatel

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.01)

**Comment by Sentinel65** [comment]
Petře, nezapomeň to dát i do toho comba Funkce u řádku se jménem přihlášeného uživatele.

**Comment by Sundin18** [comment]
To se ti tam zobrazí. Musíš si tu roli přidat v administraci. A pak si obnov prohlížeč.

**Comment by Sentinel65** [comment]
Nojo, já zapomněl, už to mám díky.
