### ISSUE TITLE
Ukládání pdf po výběru vybrat vše

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#89]
Ahoj Petr Novotný přišel asi na další problém. Pokud si v ZaMU vyberu dle nějakých parametrů filtr např. konference a poté si dám vybrat vše, tak se to označí. Ale zde již nefunguje vytvořit PDF. Nevím zda je to takto zamýšleno, nebo to je bug?

**Comment by Sentinel65** [comment]
To vypadá na BUG, protože když si zadám ten fitlr časový a dám označit ručně třeba 30 záznamů, tak to vtvoření PDF funguje

**Comment by zachyunl** [comment]
Bug to bude určitě, teď to testovali u nás na O18 v Ústí a pokud si zadají filtr MÚ a poté si vyberou jenom jednu událost, tak také ukládání do pdf nechodí. Ještě to zkouším na starší verzi na 10.99.164.39 a tam to vypadá, že to chodilo dobře.

**Comment by Sentinel65** [comment]
Hm, Jirko já teďna té 39 zrušil úplně ten časový filtr a dal Vybrat vše a to PDF se negeneruje ani tam.

**Comment by Sundin18** [comment]
Opraveno (verze 20.01.02)

**Comment by Sentinel65** [comment]
Petře na ostrém mám stále 20.01.01 a nefunguje a to jsem shodil a nahodil prohlížeč

**Comment by Sundin18** [comment]
tam jsem to nenahrál, dám to teď alespoň na 38. Na ostrý asi až zase večer a nebo bych potřeboval mít jistotu, že se zrovna netrefím při nahrávání, aby někdo něco nepsal nebo nepoužíval

**Comment by zachyunl** [comment]
Nejdříve to otestujeme pořádně na 38 z více variant. Nahrajeme to na ostrý večer a u tohoto shodíme při nahrávání opravy i Apache, ať nemáme ještě problém s daty. Klidně to okoučujeme přes emaily, že to shodíme. Nemáš zítra Petře denní, že by to počkalo na zítřek?

**Comment by Sentinel65** [comment]
Kluci, to PDF nemá takovou prioritu jako ten excel, je pátek 10 dopoledne a ty analyzátoři s tím pracují celý den, když to necháme na večer, odsouváme to až na pondělí. Udělejte klidně nejdříve 38, já to s ním vyzkouším na dálku a pak to podhodíme na ostrý.

**Comment by Sentinel65** [comment]
Není problém na VD rozeslat e-mail, že se aktualizuje Šedivák v tolik a tolik a že bude vypnutý cca 5 minut (ve skutečnosti to bude rychlejší). Nejdříve to můžeme otestovat na té 38

**Comment by zachyunl** [comment]
musíš to poslat ještě na hlavního a ústředního jen pro doplnění. Jenom na vysvětlenou co hoří s excelem? Ty jsi měl něco takového ve starém?

**Comment by Sentinel65** [comment]
Oni v Přerově ty analyzátoři odesálají soubory na ty adresy a používají excel a ten tam teď není podporovaný. Ano toto jsme dělali i v Plzni

**Comment by Sundin18** [comment]
Já to tam už nahrál, byl jsem rychlejší než jsem si to tady přečetl :-)

**Comment by Sentinel65** [comment]
Vyzkoušeno, funkční
