### ISSUE TITLE
design stránky oddělování vlastních záznamů od změnových

### ISSUE THREAD

**Issue by zachyunl** [Sundin18/backend#9]
Kosmetická záležitost: to  `<hr>,` které odděluje vlastní záznam od změnových záznamů, kdyby mohlo končit někde na konci toho tlačítka "Odstranit". V sekci Oblast a v samotném záznamu položka Oblast vymaž prosím tě to OŘ u těch názvů. To budeš mít v DB jako názvy těch oblastí.

**Comment by Sentinel65** [comment]
Moc hezké, tady se to označení kódu zobrazí jako obrázek. Tak aby Petr věděl, jde o tu čáru v kódu HTML je to > hr >

**Comment by zachyunl** [comment]
Aha to mi uteklo, on se kod nejak specialne pise.

**Comment by Sundin18** [comment]
Hotovo (Verze 19.08.1)

**Comment by Sentinel65** [comment]
Ok, možno uzavřít
