### ISSUE TITLE
Nehody, Neprojeté trasy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#92]
V obou těchto pohledech, když si otevřu kliknutím na tlačítko s číslem ZaMU daný záznam, tak se mi v kolonce Zapsal zobrazuje za jménem CHYBNĚ ČAS (systémový, místo toho skutečného, kdy byl záznam pořízen). Na 38 to dělá také.

![image](https://user-images.githubusercontent.com/54531291/71721829-e858f380-2e26-11ea-8f50-977942740edc.png)

![image](https://user-images.githubusercontent.com/54531291/71721839-f9a20000-2e26-11ea-8391-31cfc857fce0.png)

**Comment by Sentinel65** [comment]
Při té opravě, kdyby jsi tam ještě u obou pohledů do toho okna při tom otevření detailu záznamu ze ZaMU doplnil za text v záhlaví toho okna  Záznam MU a za to doplnit #xx (číslo záznamu).
Přeci jen při tom dlouhém seznamu se může ukliknout vybere jiné tlačítko záznamu, tak aby měl kontrolu.

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.03)

**Comment by Sentinel65** [comment]
na 38 ok
