### ISSUE TITLE
Nepřiřazené příkazy

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#93]
DP 13 -  typ příkazu, který nelze vhodně přiřadit k žádnému pořízenému záznamu v ZaMU.
Návrh - ve formuláři v Příkazech (pokud by to šlo pouze u analyzátora) vytvořit vespod formuláře checkbox, který by měl při zaškrtnutí funkci podobnou té, kdy je příkaz přidělen v ZaMU k záznamu, že zmizí z Nepřidělených příkazů.

**Comment by Sundin18** [comment]
Na 38 je to hotové, verze 20.01.05. Je to tedy udělané tak, že vedoucí dispečer nebo analyzátor mají možnost v detailu (okně) příkazu, zaškrtnout checkbox "Nepřiřazovat k záznamu". Checkbox vidí jen tyto role a navíc jen u příkazu, který není přiřazen k záznamu.

**Comment by Sentinel65** [comment]
OK Petře, na té 38 to funguje, jen dotaz - nešlo by, aby se po uzavření toho okna Detailu vyvolal refresh aktuální stránky, aby se to VD hned projevilo a ten Nepřiřazený příkaz mu zmizel ?
Jo to jsem do toho shrnutí zapomněl dopsat, že tato zněma Příkazu nesmí vyvolat odeslání Příkazu na přiřazené adresy PO resp. OŘ.

**Comment by Sentinel65** [comment]
Jinak na 210 ověřeno, že se ten checbox v Detailu zobrazuje jen rolím VD a analyzátora. Byl jsem tam pod účtem a  rolí dispečera a nezobrazuje se tam.

**Comment by Sentinel65** [comment]
Až to budeš podhazovat na ostrý, tak tam podhoď znovu i manuál, je tam doplněn test ohledně této funkcionality.

**Comment by Sundin18** [comment]
Ok, verze 20.01.05 nahrána na ostrý server i s manuálem.
