### ISSUE TITLE
Příkazy - řazení

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#96]
V pohledu Příkazy doplnit možnost řazení podle Datumu nebo Pořadového čísla příkazu

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.05 (zatím jen na 38)

**Comment by Sentinel65** [comment]
No super, přesně tohle jsem měl na mysli i u ostatních tabulek, tzn. řazení vzestupně / sestupně jednotlivých sloupců tabulky.

**Comment by Sentinel65** [comment]
Tak ještě jedna připomínka, myslím, že hlavně z pohledu analyzátorů - ti by to mohli využívat více.
Už jsi mi to udělal myslím v ZaMU, takže šlo by přes cookies nastavit ten filtr řazení tak, aby si to v tom prohlížeči pamatovalo posldní nastavení seřazení dle pořdoého čísla příkazu ?
Teď klikneš na jiný pohled a vrátíš se do pohledu Příkazy a je to zase srovnáno dle Datumu události. Tohle by mohlo analyzátorům pomoci v přehlednosti, pokud by ten seznam byl řazen sestupně, byť by to nebyla kontinuální řada, protože tam vidí čisla příkazů jen za svoji oblast.

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.06

**Comment by Sentinel65** [comment]
Super na 38 funguje. Možno podhodit na ostrý spolu s aktualizací Manuálu.

**Comment by Sundin18** [comment]
Je to tam
