### ISSUE TITLE
ZaMU - ukládání záznamů při opravě

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#97]
Ahoj Petře, tak první den v práci a u analyzátorů jsme dostali nějaké požadavky.
Asi ten nejdůležitější je, že jim vadí, když se probírají tím seznamem zpět v historii a jak jsme po nich chtěli chtějí uzavřít šetření, tak pak po uložení toho záznamu se jim refreshne stránka a oni jsou nahoře u toho posledního.
Oni by chtěli a je pravda, že mně to u toho starého šediváku takto fungovalo, když dali opravit záznam, že když se záznam uložil, tak se jim zobrazila stránka se svodkou přesně na tom záznamu, který před tím opravili. Neskákalo to nahoru.
Zkus se na to mrknou, jestli by s tím nešlo něco udělat, **aby se ta stránka načetla s indexem toho pořadového čísla záznamu, které opravili a tím pádem by byli na tom místě, kde skončili.** Takto neustále musí skrolovat stránku dolů.
V tomto jim musím dát za pravdu, že to je hrozně otravné a hlavně to zdržuje.

**Comment by Sentinel65** [comment]
Koukám se na script na původním šediváku, kdy se dělala oprava záznamu a tam to načzení hlavní stránky po změně záznamu bylo ošetřeno tímto kódem (načítal to  konkrétní id):

> <script>location.replace('./index.php?or=".$_GET['or']."&offset=".((isset($_GET['offset'])? $_GET['offset'] : "0"))."#".$_GET["id"]."');</script>

**Comment by Sundin18** [comment]
Hotovo (verze 20.01.08). Zatím nasazeno jen na 38.

**Comment by Sentinel65** [comment]
Supeeer, paráda, to budou mít analyzátoři radost. Funguje na 38

**Comment by Sentinel65** [comment]
Petře opět dopiš tam do toho editačního okna v záhlaví **Přidat změnu záznamu #číslo**

**Comment by Sentinel65** [comment]
Akorát teda jeden problém, nepřišel mi mail poté, co jsem dal Šetření ukončeno, skočilo mi to na to číslo záznamu, ale mail mi nepřišel (záznamy 42366, 42369 na 38)

**Comment by Sentinel65** [comment]
Nebo to máte na té 38 v ZaMU zablokované, aby se mi to posílalo ?

**Comment by Sundin18** [comment]
Tam je to zablokované, adresa hlavního dispečera je totiž přímo v kódu. Jinak je tam tedy doplněno i to číslo ZaMU v záhlaví a je to už i na ostrém serveru.

**Comment by Sentinel65** [comment]
ok funkční

**Comment by Sentinel65** [comment]
Petře, mrkni se znovu na toto, už nám to chodilo i na ostrém a dneska mi na analýze řekli, že při změně nebo když chtějí ukončit šetření, tak jim to po odeslání zase skáče na začátek stránky a nezůstává to na tom opraveném záznamů, jak už jsi to jednou udělal.

**Comment by Sundin18** [comment]
A stává se jim to pokaždé? Nebylo to jen jednou zrovna, když došlo k načtení záznamů (10 minutový interval)

**Comment by Sentinel65** [comment]
Určitě ne, byl jsem u toho a Bohunka tam zkoušela ukončení šetření u třech čtyřech záznamů a pokaždé to skončilo na ten první. Stejné to bo i když jsem vymazal cache prohlížeče.

**Comment by Sundin18** [comment]
Já to teď testoval na 38 a funguje to.

**Comment by Sentinel65** [comment]
No teď jsem to na 38taky zkoušel a tam to jde, ale na ostrém to nejde, byl jsem u toho, kdy tam opravdu upravovala aspoň 4 záznamy a skákalo to pak na první záznam.
