### ISSUE TITLE
Příkazy - PZ (chybné generování PDF)

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#98]
V příkazech PZ se nám chybně generuje v PDF text - viz. obrázek - u položek: 

- Provozní závadu sepsal:
- Traťový (provozní) dispečer:

Při delším textu v položce **Popis závady se navíc v PDF nezalamuje text**, takže tam není vidět celý text, který byl napsán. Na 38 je to stejné. 
**Dále nejde zrušit záznam u ST a PZ, DP zrušit jde.** - hodí to chybu "**Dispečerský příkaz se nepodařilo zrušit!**" stejné na 38 i ostrém.

Teď jsme navíc zjistili, že při normálním vyplnění DP a následném zaškrtnutí checkboxu Nepřiřazení k záznamu **se vymaže text** v položce **Ovlivněn vlak** a **Poznámka.** Zkoušeno opět na 38, ale fakticky to je i na ostrém - konkrétně DP 27.

![Prikazy_PZ_10_02012020](https://user-images.githubusercontent.com/54531291/71815316-5bf53d80-307f-11ea-9b40-0ba7280d35dc.png)

![Prikazy_PZ_26_06012020](https://user-images.githubusercontent.com/54531291/71815323-61528800-307f-11ea-81cf-1524e60b3367.png)

**Comment by Sundin18** [comment]
Hotovo, verze 20.01.07

**Comment by Sentinel65** [comment]
OK
