### ISSUE TITLE
Příkazy - PZ nový požadavek

### ISSUE THREAD

**Issue by Sentinel65** [Sundin18/backend#99]
U CDP Praha v **Příkazech - PZ**:

- Pracoviště PD1 PHA doplnit Příjemce na DS4A, DS4B
- Pracoviště PD3 PHA doplnit Příjemce na DS4A, DS4B

**Comment by Sundin18** [comment]
Hotovo, je to na ostrým, bude ve verzi 20.01.07

**Comment by Sentinel65** [comment]
OK
